<!--sass --watch C:\Users\Admin\Desktop\cdmobile\css\style.scss:C:/Users/Admin/Desktop/cdmobile/css/style.css-->
<?php
require_once('../../../define.php');
$domain=domain;
$phone1=phone1;
$link_gioithieu=link_mobile_gioithieu;
$link_kythuat=link_kythuat;
$link_diachi=link_mobile_diachi;
$link_skype=link_skype;
$popup=m_popup();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title> Chuyên đề giải phóng mobie </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i"
          rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <meta charset="UTF-8">
    <base target="_blank">
    <?= ico_shortcut;?>
</head>
<body>
<div class="pages">
    <header>
        <div class="top">
            <div class="top_l">
                <img style="" class="img-responsive" src="images/top_logo.png" alt="">
            </div>
            <div class="top_r">
                <img style="margin-top: 7%;" class="img-responsive" src="images/top_sdt.png" alt="">
            </div>
        </div>
        <div class="menu">
            <ul>
                <li>
                    <a href="<?= $domain;?>"> Trang chủ </a>
                </li>
                <li>
                    <a href="<?= $link_gioithieu;?>"> Giới thiệu </a>
                </li>
                <li>
                    <a href="<?= $link_kythuat;?>"> Kỹ thuật </a>
                </li>
                <li>
                    <a href="<?= link_tuvan;?>"> Bác sĩ </a>
                </li>
                <li>
                    <a href="<?= $link_diachi;?>"> Địa chỉ </a>
                </li>
            </ul>
        </div>
        <div class="banner">
            <div class="banner_img">
                <img src="images/banner.jpg">
            </div>
        </div>
    </header>
    <div class="main_item main_item1">
        <div class="main_item1_tit">
            <p>Khám Bệnh đến với phòng khám giải phóng</p>
            <p><b>Thiết bị đầy đủ - Điều trị hiểu quả -  Chi phí thấp</b></p>
        </div>
        <div class="loimodau">
            <div class="loimodau_l">
                <img src="images/loimodau.png">
            </div>
            <div class="loimodau_r">
                <div class="loimodau_r_txt">
                    Phòng khám đa khoa Giải Phóng Hà Nội đã và luôn là một đơn vị tiên phong trong lĩnh vực y tế, chăm sóc dịch vụ cộng đồng với nhiều phương pháp điều trị tiên tiến. Cùng với những kỹ thuật hiện đại được nhập khẩu từ các nước có nền y học phát triển bậc nhất, chúng tôi đã giải quyết dứt điểm nhiều căn bệnh khó chữa. Hãy đến với phòng khám đa khoa 709 Giải Phóng Hà Nội để tận hưởng dịch vụ chăm sóc sức khỏe chuyên nghiệp do đội ngũ chuyên gia nhiều năm kinh nghiệm trực tiếp tiến hành điều trị NGAY HÔM NAY.
                </div>
            </div>
        </div>
    </div>
    <div class="main_item main_item2">
        <div class="main_item2_tit">
            <label class="color_black">3 Hạng mục miễn phí</label>
            <label class="color_yellow">Bạn nhận được</label>
        </div>
        <ul>
            <li>
                <div class="main_item2_l">
                    <img src="images/main_item2_dh.png">
                </div>
                <div class="main_item2_r">
                    <h3>Đặt hẹn bác sỹ</h3>
                    <p>Bạn có thể đặt hẹn miễn phí để nhận được sự tư vấn và khám bệnh bởi đội ngũ bác sĩ chuyên môn cao </p>
                </div>
            </li>
            <li>
                <div class="main_item2_l">
                    <img src="images/main_item2_tv.png">
                </div>
                <div class="main_item2_r">
                    <h3>Tư vấn</h3>
                    <p>Tư vấn miễn phí dành cho người bệnh khi đến khám và chữa bệnh cùng các bác sĩ chuyên khoa </p>
                </div>
            </li>
            <li>
                <div class="main_item2_l">
                    <img src="images/main_item2_tk.png">
                </div>
                <div class="main_item2_r">
                    <h3>Tái khám</h3>
                    <p>Phòng khám miễn phí tái khám với mong muốn dành cho bạn những trải nghiệm dịch vụ chuyên nghiệp.</p>
                </div>
            </li>
        </ul>
    </div>
    <div class="main_item main_item3">
        <div class="main_item3_tit">
            <img src="images/main_item3_tit.png">
            <label>CHÚNG TÔI CÓ THIẾT BỊ VÀ MÔI TRƯỜNG THỦ THUẬT MÀ NHỮNG NƠI KHÁC KHÔNG THỂ SO SÁNH</label>
        </div>
        <div class="main_item3_img">
            <img src="images/main_item3_1.png">
        </div>
        <div class="main_item3_c">
            <div class="main_item3_txt">
                Khâu kiểm tra bệnh tại phòng khám được thực hiện theo đúng trình tự, gồm khâu kiểm tra lâm sàng đến làm xét nghiệm, điển hình như xét nghiệm máu, xét nghiệm nước tiểu, xét nghiệm mẫu vật...cùng nhiều xét nghiệm chuyên môn khác. Qúa trình kiểm tra được thực hiện trực tiếp bởi các bác sỹ đầu ngành, áp dụng máy móc kỹ thuật tân tiến, cho phép chẩn đoán bệnh chính xác trong thời gian ngắn nhất
            </div>
            <div class="main_item3_img">
                <img src="images/main_item3_2.jpg">
            </div>
            <div class="main_item3_txt">
                Vì sự an toàn của bạn, hi vọng mọi người nâng cao cảnh giác, lựa chọn cẩn thận! Không nên tin tưởng các phòng khám tư nhân nhỏ lẻ và không chính quy, khi làm thủ thuật nhất định phải lựa chọn phòng khám chính quy, có chất lượng, quy mô lớn...
            </div>
        </div>
        <div class="main_item_sdt">
            <div class="main_item_sdt_l">
                <a href="<?= rewrite_number_phone($phone1);?>">
                    <img src="images/sdt_tv.png">
                </a>
            </div>
            <div class="main_item_sdt_r">
                <a href="<?= link_tuvan;?>">
                    <img src="images/btn_tv.png">
                </a>
            </div>
        </div>
    </div>
    <div class="main_item main_item4">
        <div class="main_item4_tit">
            <img src="images/main_item4_tit.png">
        </div>
        <div class="main_item4_img">
            <img src="images/main_item4_1.png">
        </div>
        <div class="main_item4_txt">
            <h3>THẤU HIỂU ĐƯỢC NHỮNG KHÓ KHĂN VÀ NHU CẦU KHÁM CHỮA BỆNH CỦA BỆNH NHÂN NGÀY CÀNG CAO.</h3>
            <div class="main_item4_des">
                Sau chặng đường nhiều năm phát triển,phòng khám đa khoa Giải Phóng đã khẳng định được vị thế trong lĩnh vực chăm sóc sức khỏe, với phương châm đặt sức khỏe của bệnh nhân lên hàng đầu và nhằm giảm bớt gánh nặng cho người bệnh, phòng khám triển khai chương trình ưu đãi mừng xuân mới. Dành riêng cho những bệnh nhân có đặt hẹn trước với nhiều hạng mục hấp dẫn.
            </div>
        </div>
        <div class="main_item4_img">
            <img src="images/main_item4_2.png">
        </div>
        <div class="main_item_sdt">
            <div class="main_item_sdt_l">
                <a href="<?= rewrite_number_phone($phone1);?>">
                    <img src="images/sdt_tv_red.png">
                </a>
            </div>
            <div class="main_item_sdt_r">
                <a href="<?= link_tuvan;?>">
                    <img src="images/btn_tv.png">
                </a>
            </div>
        </div>
    </div>
    <div class="main_item main_item5">
        <div class="main_item5_tit">
            <img src="images/main_item5_tit.png">
        </div>
        <div class="main_item5_img">
            <img src="images/main_item5_1.png">
        </div>
        <div class="main_item5_txt">
            <h3>THẤU HIỂU ĐƯỢC NHỮNG KHÓ KHĂN VÀ NHU CẦU KHÁM CHỮA BỆNH CỦA BỆNH NHÂN NGÀY CÀNG CAO
                </h3>
            <div class="main_item4_des">
                Phòng khám Giải Phóng Hà Nội trong nhiều năm qua phòng khám đã và luôn là một đơn vị tiên phong trong lĩnh vực y tế, chăm sóc dịch vụ cộng đồng với nhiều phương pháp điều trị tiên tiến. Kết hợp với đội ngũ y bác sĩ hùng hậu, phòng khám đa khoa Giải Phóng đầu tư các trang thiết bị, máy móc, hiện đại, luôn được cập nhật và đổi mới không ngừng để nắm bắt các động thái, xu hướng chữa bệnh mới nhất của nền y học thế giới, trang thiết bị này đều được phòng khám nhập khẩu trực tiếp từ các quốc gia có nền y học phát triển như Anh, Mỹ, Đức, Nhật Bản, Hàn Quốc... thông qua sự kiểm định của bộ y tế Việt Nam. Nhờ áp dụng những kỹ thuật tân tiến, chúng tôi đã giải quyết dứt điểm một số căn bệnh phức tạp khó chữa và kết quả khám chữa bệnh được nâng cao một cách rõ rệt.
            </div>
        </div>
        <div class="main_item5_img">
            <img src="images/main_item5_2.png">
        </div>
        <div class="main_item_sdt">
            <div class="main_item_sdt_l">
                <a href="<?= rewrite_number_phone($phone1);?>">
                    <img src="images/sdt_tv.png">
                </a>
            </div>
            <div class="main_item_sdt_r">
                <a href="<?= link_tuvan;?>">
                    <img src="images/btn_tv.png">
                </a>
            </div>
        </div>
    </div>
    <div class="main_item main_item6">
        <div class="main_item6_tit">
            <h3><span>Phòng khám</span> Chuyên nghiệp</h3>
        </div>
        <div class="main_item6_c">
            <ul>
                <li>
                    <div class="main_item6_img">
                        <img src="images/main_item6_1.jpg">
                    </div>
                    <div class="main_item6_t">
                        Năng lực được chứng nhận
                    </div>
                    <div class="main_item6_txt">
                        Là phòng khám chuyên khoa tai mũi họng được chứng nhận và cấp phép bởi Sở Y tế Hà Nội trong việc điều trị, phòng ngừa và bảo vệ sức khỏe cho mọi người.
                    </div>
                </li>
                <li>
                    <div class="main_item6_img">
                        <img src="images/main_item6_2.jpg">
                    </div>
                    <div class="main_item6_t">
                        Trang thiết bị hiện đại
                    </div>
                    <div class="main_item6_txt">
                        Luôn tiên phong trong việc điều trị cho bệnh nhân bằng các trang thiết bị và công nghệ hiện đại đã và đang được ứng dụng trên thế giới.
                    </div>
                </li>

            </ul>
            <ul>
                <li>
                    <div class="main_item6_img">
                        <img src="images/main_item6_3.jpg">
                    </div>
                    <div class="main_item6_t">
                        Yêu cầu về trình độ
                    </div>
                    <div class="main_item6_txt">
                        Đội ngũ bác sĩ được đào tạo sâu về các kĩ thuật điều trị tai mũi họng và đã có nhiều năm kinh nghiệm với hàng ngàn ca điều trị thành công.
                    </div>
                </li>
                <li>
                    <div class="main_item6_img">
                        <img src="images/main_item6_4.jpg">
                    </div>
                    <div class="main_item6_t">
                        Đảm bảo an toàn
                    </div>
                    <div class="main_item6_txt">
                        Người bệnh được điều trị trong môi trường khám chữa đảm bảo vô trùng, đúng tiêu chuẩn, chuyên nghiệp và đầy đủ tiện nghi.
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="main_item main_item7">
        <a href="<?= link_tuvan;?>">Bạn muốn tư vấn<br>đặt hẹn</a>
    </div>
<footer>
    <ul>
        <li>
            <a href="<?= $link_skype;?>">
                <img src="images/footer_skype.png">
                <p>Skype</p>
            </a>
        </li>
        <li>
            <a href="<?= link_tuvan;?>">
                <img src="images/footer_datkham.png">
                <p>Đặt khám</p>
            </a>
        </li>
        <li>
            <a href="tel:0363528899">
                <img src="images/footer_dt.png">
                <p>Điện thoại</p>
            </a>
        </li>
        <li>
            <a href="<?= link_tuvan;?>">
                <img src="images/footer_henkham.png">
                <p>đặt lịch</p>
            </a>
        </li>
    </ul>
</footer>
</div>
<?= $popup;?>
</body>
</html>