<?php 
$link_trangchu = "http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-de-suc-khoe/";
$link_tv = "http://swt.pk709.com/LR/Chatpre.aspx?id=KTF27288478&lng=en";
$link_gioithieu = "http://phongkhamgiaiphong.com/cd6/gioi-thieu/";
$link_tuyenduong = "http://phongkhamgiaiphong.com/cd6/lo-trinh-kham/";
$link_kythuat = "http://khamnamkhoahanoi.vn/ky-thuat";
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="css/style.css">
	 <base target="_blank">
	 <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.3.1/css/hover-min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" />
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>  Chuyện đề giải phóng </title>
</head>
<script>
              new WOW().init();
</script>

<body>
	<div class="pages">
		 <div class="container">
		 	 <header>
				    <div class="flex flex1 justify-content-between" style="height: 65px;">
				        <div class="flex1col1">
				            <h2 class="text-container-center logo">
				                <a href="http://khamnamkhoahanoi.vn"><img src="http://trihanoi.com/public/frontend/home/image/header-1.png" alt=""></a>
				            </h2>
				        </div>
				        <div class="flex1col2">
				            <div class="flex flex2 justify-content-between">
				                <div class="flex2col1 text-container-center">
				                	<a href=""><img src="http://trihanoi.com/public/frontend/home/image/header-2.png" alt=""></a>
				                </div>
				                <div class="flex2col1 text-container-center">
				                	<a href="">
				                		<img src="http://trihanoi.com/public/frontend/home/image/header-3.png" alt="">
				                	</a>
				                </div>
				                <div class="flex2col1 text-container-center">
				                	<a href="/lo-trinh-den-phong-kham">
				                		<img src="http://trihanoi.com/public/frontend/home/image/header-4.png" alt="">
				                	</a>
				                </div>
				            </div>
				        </div>
				    </div>
			 </header> <!-- end header  -->
		 </div>
           <div class="menu"> <!-- begin menu  -->
	           <div class="container">
	                <div class="row justify-content-center text-center">
	                    <div class="col h-100 p-3 custom_bg"><a href="<?= $link_trangchu?>" class="text-light"> Trang chủ </a></div>
	                    <div class="col h-100 p-3 custom_bg"><a href="<?= $link_gioithieu?>" class="text-light"> Giới thiệu  </a></div>
	                    <div class="col h-100 p-3 custom_bg"><a href="<?= $link_kythuat?>" class="text-light"> Kỹ thuật  </a></div>
	                    <div class="col h-100 p-3 custom_bg"><a href="<?= $link_tv?>" class="text-light"> Bác sỹ  </a></div>
	                    <div class="col h-100 p-3 custom_bg"><a href="<?=$link_tuyenduong?>" class="text-light"> Tuyến xe  </a></div>
	                    <div class="col h-100 p-3 custom_bg"><a href="<?= $link_tv?>" class="text-light"> Đăng ký trực tuyến </a></div>
	                </div>
	           </div>
      	   </div>
	  	   <div class="banner">
	  	   	 <img src="images/banner.jpg" alt="" class="mw-100">
	  	   </div>
	  	   <div class="t_home1">
	  	   	 <div class="container">
	  	   	 	 <div class="row">
	  	   	 	 	 <div class="title_t_1 p-2 text-light h-100 text-uppercase w-100 wow bounceInDown" style="font-size: 19px;"> 
                          <span class="font-weight-normal"> Khám tai mũi họng hãy đến với phòng khám đa khoa giải phóng  </span> <strong class="font-weight-bold">thiết bị đầy đủ - Điều trị hiệu quả - chi phí thấp    </strong> 
	  	   	 	 	 </div>
	  	   	 	 </div>
	  	   	 </div>
	  	   </div> <!-- end home 1 -->
	  	   <!-- home 2 -->
	  	   <div class="t_home_2 p-3">
	  	   	 <div class="container">
	  	   	 	 <div class="row">
	  	   	 	 	 <div class="col-md-2">
	  	   	 	 	 	 <img class="wow slideInLeft" src="images/bs_home2.png" alt="">
	  	   	 	 	 </div>
	  	   	 	 	 <div class="col-md-10">
	  	   	 	 	 	 <div class="descriton_t_home_2 px-3 py-3 wow slideInRight">
	  	   	 	 	 	 	 Nhằm hưởng ứng lời kêu gọi của Bộ Y tế: giảm giá chi phí dịch vụ y tế, Phòng khám Đa Khoa giải Phóng Hà Nội thực hiện giảm giá chi phí kiểm tra Tai Mũi Họng, toàn bộ chi phí kiểm tra chỉ 100.000, không có khoản phụ thu khác, thiết bị và chất lượng phục vụ không ngừng được nâng cao, giúp quần chúng nhân dân tiết kiệm chi phí, kiểm tra được bệnh, bỏ ra chi phí thấp nhất, tận hưởng dịch vụ chăm sóc tốt nhất, Đồng thời cảm ơn sự ủng hộ và tin tưởng của bệnh nhân trong suốt thời gian qua . Chúng tôi sẽ tiếp tục cung cấp cho người bệnh những dịch vụ chăm sóc sức khỏe và điều trị tốt hơn nữa, Nếu có vấn đề có thể liên hệ đến số điện thoại chăm sóc của chúng tôi, luôn luôn đặt bệnh nhân lên hàng đầu.
	  	   	 	 	 	 </div>
	  	   	 	 	 </div>
	  	   	 	 </div>
	  	   	 </div>
	  	   </div>
	  	   <!-- end home 2  -->
	  	   <div class="t_home_3 p-5">
	  	   	 <div class="container">
	  	   	 	 <div class="row text-center justify-content-center">
	  	   	 	 	 <div class="title_t_home3 pb-5 text-uppercase"> <span class="text-light"> 3 hạng mục miễn phí</span> <strong class="text-warning"> bạn nhận được </strong></div>
	  	   	 	 </div>
	  	   	 	 <div class="row">
	  	   	 	 	 <div class="col-md-4">	
                          <div class="cover p-3 hvr-float-shadow wow flipInX">
                          	 <div class="row">
                          	 	 <div class="col-md-3">
                          	 	 	 <div class="icon">
                          	 	 	 	<img src="images/icon_h3.png" alt="">
                          	 	 	 </div>
                          	 	 </div>
                          	 	 <div class="col-md-9 pr-0 pl-4">
                          	 	 	<div class="content_h3">
                          	 	 		 <strong class="tt_ct_h3"> Đặt  hẹn bác sỹ </strong>
                          	 	 		 <div class="des_ct_h3"> Bạn có thể đặt hẹn miễn phí để nhận được sự tư vấn và khám bệnh bởi đội ngũ bác sĩ chuyên môn cao </div>
                          	 	 	</div>
                          	 	 </div>
                          	 </div>
                          </div>
	  	   	 	 	 </div>
	  	   	 	 	 <div class="col-md-4">
                      <div class="cover cover_hai p-3 hvr-float-shadow wow flipInX">
                          	 <div class="row">
                          	 	 <div class="col-md-3">
                          	 	 	 <div class="icon">
                          	 	 	 	<img src="images/icon_h3_2.png" alt="">
                          	 	 	 </div>
                          	 	 </div>
                          	 	 <div class="col-md-9 pr-0 pl-4">
                          	 	 	<div class="content_h3">
                          	 	 		 <strong class="tt_ct_h3"> Tư vấn  </strong>
                          	 	 		 <div class="des_ct_h3"> Tư vấn miễn phí dành cho người bệnh khi đến khám và chữa bệnh cùng các bác sĩ chuyên khoa </div>
                          	 	 	</div>
                          	 	 </div>
                          	 </div>
                          </div>
	  	   	 	 	 </div>
	  	   	 	 	 <div class="col-md-4">
	  	   	 	 	 	<div class="cover cover_ba p-3 hvr-float-shadow wow flipInX">
                          	 <div class="row">
                          	 	 <div class="col-md-3">
                          	 	 	 <div class="icon">
                          	 	 	 	<img src="images/icon_h3_3.png" alt="">
                          	 	 	 </div>
                          	 	 </div>
                          	 	 <div class="col-md-9 pr-0 pl-4">
                          	 	 	<div class="content_h3">
                          	 	 		 <strong class="tt_ct_h3"> Tái khám  </strong>
                          	 	 		 <div class="des_ct_h3"> Phòng khám miễn phí tái khám với mong muốn dành cho bạn những trải nghiệm dịch vụ chuyên nghiệp.</div>
                          	 	 	</div>
                          	 	 </div>
                          	 </div>
                          </div>
	  	   	 	 	 </div>
	  	   	 	 </div>
	  	   	 </div>
	  	   </div> 
	  	   <!-- home 4 -->
	  	   <div class="t_home_4 p-5">
	  	   	 <div class="container"> 
                <div class="row">
                	 <div class="col-md-7 wow zoomIn">
                	 	  <div class="content_t_home4">
                	 	  	<div class="title_ct_home4 text-uppercase py-5">
                	 	  		 <strong class="text-warning"> Chi phí kiểm tra sức khỏe </strong><strong class="text-muted"> Thấp nhất hà nội </strong>
                	 	  	</div>
                	 	  	<img src="images/km_home4.jpg" class="w-75" alt="">
                	 	  	<div class="text-col-7 py-5">
                	 	  		Khâu kiểm tra tai - mũi - họng tại phòng khám đa chính là cơ hội để bạn kiểm tra sức khỏe của mình hoặc điều trị tại cơ sở chuyên khoa tai mũi họng hàng đầu tại Hà Nội. Quy trình bao gồm kiểm tra tai, xét nghiệm kiểm tra mũi, nội soi tai - mũi - họng kết hợp với màn hình tivi, máy đo thính lực.... Đây là việc làm cần thiết giúp đánh giá tình trạng tai mũi họng chung; phát hiện sớm dấu hiệu của các bệnh lý tai mũi họng tư¬ vấn điều trị dự phòng và phát hiện sớm ung thư.
                	 	  	</div>
                	 	  </div>
                	 </div>
                	 <div class="col-md-5 wow zoomIn">
                	 	 <img class="pt-5" src="images/bs_home4.png" alt="">
                	 </div>
                </div>
	  	   	 </div>
	  	   </div>
	  	   <!-- home 5 -->
	  	   <div class="t_home5">
	  	   	  <div class="container">
	  	   	  	 <div class="row">
	  	   	  	 	<div class="col-md-8 py-5 wow slideInLeft">
	  	   	  	 		<div class="tt_home5 w-75 text-uppercase py-4">
	  	   	  	 	 	 <strong class="text-warning"> chi phí </strong> <strong class="text-danger">  thủ thuật giảm </strong> <img src="images/30_home5.png" alt="">
	  	   	  	 	 </div>
	  	   	  	 	 <strong class="tt_home5_hai text-uppercase text-light">THẤU HIỂU ĐƯỢC NHỮNG KHÓ KHĂN VÀ NHU CẦU KHÁM CHỮA BỆNH CỦA BỆNH NHÂN.</strong>
	  	   	  	 	 <div class="descrtion_home5 text-light py-4 text-justify">Ưu đãi giảm 30% chi phí phẫu thuật áp dụng cho tất cả bệnh nhân tiến hành phẫu thuật tai mũi họng tại phòng khám đa khoa 709 Giải Phóng Hà Nội. Đặc biệt, đây là một trong những ưu đãi lớn cho người bệnh khi tiến hành các thủ thuật như: thủ thuật sửa chữa màng nhĩ, thủ thuật chỉnh hình vách ngăn mũi, thủ thuật loại bỏ polyp thanh quản… Khi đăng kí thực hiện dịch vụ, khách hàng sẽ được trải nghiệm những ưu điểm vượt trội về chất lượng y tế của một phòng khám hàng đầu với phong cách phục vụ chuyên nghiệp.</div>
	  	   	  	 	 <div class="row">
	  	   	  	 	 	 <div class="col-md-6">
	  	   	  	 	 	 	 <img src="images/img_home5_1.jpg" alt="" style="width: 98%;">
	  	   	  	 	 	 </div>
	  	   	  	 	 	 <div class="col-md-6">
	  	   	  	 	 	 	 <img src="images/img_home5_2.jpg" alt="" style="width: 98%;">
	  	   	  	 	 	 </div>
	  	   	  	 	 </div>
	  	   	  	 	</div>
	  	   	  	 	<div class="col-md-4 wow slideInRight">
	  	   	  	 		 <img src="images/box_home5.jpg" alt="">
	  	   	  	 	</div>
	  	   	  	 </div>
	  	   	  </div>
	  	   </div>
	  	    <!-- home 6 -->
	  	   <div class="t_home5 t_home6">
	  	   	  <div class="container">
	  	   	  	 <div class="row">
	  	   	  	 	<div class="col-md-4 wow bounceInUp">
	  	   	  	 		 <img src="images/box_home5_2.jpg" alt="">
	  	   	  	 	</div>
	  	   	  	 	<div class="col-md-8 py-5 wow bounceInUp">
	  	   	  	 		<div class="tt_home5 w-75 text-uppercase py-4">
	  	   	  	 	 	 <strong class="text-warning"> chi phí </strong> <strong class="text-danger">  Điều trị </strong> <img src="images/30_home5.png" alt="">
	  	   	  	 	 </div>
	  	   	  	 	 <strong class="tt_home5_hai text-uppercase text-danger">THẤU HIỂU ĐƯỢC NHỮNG KHÓ KHĂN VÀ NHU CẦU KHÁM CHỮA BỆNH CỦA BỆNH NHÂN.</strong>
	  	   	  	 	 <div class="descrtion_home5 text-secondary py-4 text-justify">Thấu hiểu nhu cầu khám chữa bệnh của người dân, phòng khám đa khoa 709 Giải Phóng Hà Nội cũng dành tặng 30% chi phí điều trị. Với ưu đãi này, nỗi lo lắng khi bị mắc phải các bệnh lý về tai mũi họng gây ảnh hưởng tới sức khỏe cũng như sức khỏe của người bệnh sẽ được phòng khám chúng tôi gánh vác giúp quý khách hàng phần nào.</div>
	  	   	  	 	 <div class="row">
	  	   	  	 	 	 <div class="col-md-6">
	  	   	  	 	 	 	 <img src="images/bs-home_6_1.jpg" alt="" style="width: 98%;">
	  	   	  	 	 	 </div>
	  	   	  	 	 	 <div class="col-md-6">
	  	   	  	 	 	 	 <img src="images/bs_home6_2.jpg" alt="" style="width: 98%;">
	  	   	  	 	 	 </div>
	  	   	  	 	 </div>
	  	   	  	 	</div>
	  	   	  	 </div>
	  	   	  </div>
	  	   </div>
	  	   <!-- home7 -->
	  	   <div class="t_home7 p-5  ">
	  	   	 <div class="container">
	  	   	 	 <div class="row justify-content-center wow zoomIn">
	  	   	 	 	 <div class="tt_home7 text-uppercase py-3">
	  	   	 	 	 	 <strong class="text-warning"> Phòng khám </strong> <strong> chuyên nghiệp </strong>
	  	   	 	 	 </div>
	  	   	 	 </div>
	  	   	 	 <div class="row  wow zoomIn">
	  	   	 	 	 <div class="col-md-8 mx-auto">
	  	   	 	 	 	 <div class="descriton_md text-center pb-5">
	  	   	 	 	 	 	 Phòng khám là nơi hội tụ đội ngũ y bác sỹ có trình độ chuyên môn cao, hệ thống trang thiết bị hiện đại, dịch vụ chăm sóc tận tình, chu đáo luôn làm hài lòng mọi bệnh nhân. Phòng khám đa khoa 709 Giải Phóng Hà Nội đã và đang cố gắng phấn đấu trở thành một đơn vị chăm sóc sức khỏe có quy mô lớn, khẳng định vị thế và thương hiệu của mình trong lĩnh vực khám, hỗ trợ chữa bệnh.
	  	   	 	 	 	 </div>
	  	   	 	 	 </div>
	  	   	 	 </div>
	  	   	 	 <div class="row">
	  	   	 	 	 <div class="col-md-3 text-center">
	  	   	 	 	 	<div class="nd_block_3 hvr-float-shadow wow flipInX">
	  	   	 	 	 		 <img src="images/img_home6_1.jpg" alt="">
	  	   	 	 	 		 <div class="nd_sub">
		  	   	 	 	 		  <div class="tt_strong py-2"><strong> Năng lực được công nhận </strong></div>
		  	   	 	 	 		  <div class="descrtion_nd">
		  	   	 	 	 		  	 Là phòng khám chuyên khoa tai mũi họng được chứng nhận và cấp phép bởi Sở Y tế Hà Nội trong việc điều trị, phòng ngừa và bảo vệ sức khỏe cho mọi người.
		  	   	 	 	 		  </div>
	  	   	 	 	 		  </div>
	  	   	 	 	 	</div>
	  	   	 	 	 </div>
	  	   	 	 	 <div class="col-md-3 text-center">
	  	   	 	 	 	<div class="nd_block_3 nd_block_3_hai hvr-float-shadow wow flipInX">
	  	   	 	 	 		 <img src="images/img_home6_2.jpg" alt="">
	  	   	 	 	 		  <div class="nd_sub nd_sub_2 text-light">
		  	   	 	 	 		  <div class="tt_strong py-2"><strong> Trang thiết bị hiện đại  </strong></div>
		  	   	 	 	 		  <div class="descrtion_nd">
		  	   	 	 	 		  	Luôn tiên phong trong việc điều trị cho bệnh nhân bằng các trang thiết bị và công nghệ hiện đại đã và đang được ứng dụng trên thế giới.
		  	   	 	 	 		  </div>
	  	   	 	 	 		  </div>
	  	   	 	 	 	</div>
	  	   	 	 	 </div>
	  	   	 	 	 <div class="col-md-3 text-center">
	  	   	 	 	 	<div class="nd_block_3 hvr-float-shadow wow flipInX">
	  	   	 	 	 		 <img src="images/img_home6_3.jpg" alt="">
	  	   	 	 	 		  <div class="nd_sub">
		  	   	 	 	 		  <div class="tt_strong py-2"><strong> yêu cầu về trình độ  </strong></div>
		  	   	 	 	 		  <div class="descrtion_nd">
		  	   	 	 	 		  	Đội ngũ bác sĩ được đào tạo sâu về các kĩ thuật điều trị tai mũi họng và đã có nhiều năm kinh nghiệm với hàng ngàn ca điều trị thành công.
		  	   	 	 	 		  </div>
	  	   	 	 	 		  </div>
	  	   	 	 	 	</div>
	  	   	 	 	 </div>
	  	   	 	 	 <div class="col-md-3 text-center">
	  	   	 	 	 	<div class="nd_block_3 nd_block_3_hai hvr-float-shadow wow flipInX">
	  	   	 	 	 		 <img src="images/img_home6_4.jpg" alt="">
	  	   	 	 	 		  <div class="nd_sub nd_sub_2 text-light">
		  	   	 	 	 		  <div class="tt_strong py-2"><strong> Bảo đảm an toàn </strong></div>
		  	   	 	 	 		  <div class="descrtion_nd">
		  	   	 	 	 		  	Người bệnh được điều trị trong môi trường khám chữa đảm bảo vô trùng, đúng tiêu chuẩn, chuyên nghiệp và đầy đủ tiện nghi.
		  	   	 	 	 		  </div>
	  	   	 	 	 		  </div>
	  	   	 	 	 	</div>
	  	   	 	 	 </div>
	  	   	 	 </div>
	  	   	 </div>
	  	   </div> 
	  	  <!--  home 8 -->
	  	  <div class="t_home8 p-5">
	  	  	 <div class="container">
	  	  	 	 <div class="row justify-content-center">
	  	  	 	 	  <h2 class="tt_home8 text-warning text-uppercase mb-0">Thắm khám bệnh lưu ý </h2>
	  	  	 	 	  
	  	  	 	 </div>
	  	  	 	 <div class="row justify-content-center">
	  	  	 	 	 <h2 class="tt_home8_hai text-light text-uppercase">
	  	  	 	 	  	 phòng khám chuyên nghiệp 
	  	  	 	 	 </h2>
	  	  	 	 </div>
	  	  	 	 <div class="row">
	  	  	 	 	 <div class="col-md-10 mx-auto">
	  	  	 	 	 	<div class="des_mx_8 text-center text-light p-3 ">
	  	  	 	 	 		Phòng khám đa khoa Giải Phóng với trang thiết bị hiện đại, kỹ thuật tiên tiến, điều trị hiệu quả cao, chi phí thấp.
Không phải phòng khám nào cũng có thể áp dụng kỹ thuật xâm lấn tối thiểu Chỉ có những phòng khám chuyên nghiệp, toàn diện, cơ cấu trang thiết bị và năng lực về y tế chính quy toàn diện mới có đủ tư cách áp dụng
	  	  	 	 	 	</div>
	  	  	 	 	 </div>
	  	  	 	 </div>
	  	  	 	 <div class="row pt-5">
	  	  	 	 	 <div class="col-md-4 wow slideInLeft">
	  	  	 	 	 	<div class="sub_cd">
	  	  	 	 	 	 <ul>
	  	  	 	 	 	 	<li class="text-right">  
                                <div class="tt_menu">
                                	 Năng lực được công nhận 
                                </div>
                                <div class="nd_cover1 text-light pt-2">
                                	 Phòng khám đa khoa Giải Phóng với trang thiết bị hiện đại, kỹ thuật tiên tiến, điều trị hiệu quả cao, chi phí thấp
                                </div>
	  	  	 	 	 	 	</li>
	  	  	 	 	 	 	<li class="text-right">  
                                <div class="tt_menu text-warning">
                                	Yêu cầu về trình độ  
                                </div>
                                <div class="nd_cover2 text-light pt-2">
                                	Nhằm đảm bảo thực hiện thủ thuật an toàn và hiệu quả cao, thực hiện thủ thuật cần có: 
                                	<div class="nd_cv_1">
                                		 1. Bác sỹ có Trình độ thủ thuật cao 
                                	</div>
                                	<div class="nd_cv_2">
                                		2. Bác sỹ thực hiện hàng ngàn ca thủ thuật không để xuất hiện sự cố 
                                	</div>
                                	<div class="nd_cv_2">
                                		3. Làm trong ngành 20 năm trở lên 
                                	</div>
                                </div>
	  	  	 	 	 	 	</li>
	  	  	 	 	 	 </ul>
	  	  	 	 	 	 </div>
	  	  	 	 	 </div>
	  	  	 	 	 <div class="col-md-4">
	  	  	 	 	 	<img src="images/img_home8.png" class="mw-100 pt-5 wow zoomIn" style="width: 90%;margin: auto; display: block;" alt="">
	  	  	 	 	 </div>
	  	  	 	 	 <div class="col-md-4 wow slideInRight">
	  	  	 	 	 	<div class="sub_cd">
	  	  	 	 	 	 <ul>
	  	  	 	 	 	 	<li class="text-left">  
                                <div class="tt_menu text-warning">
                                	Trang thiết bị hiện đại
                                </div>
                                <div class="nd_cover3 text-light pt-2">
                                	 Phòng khám đa khoa Giải Phóng, nhập khẩu trang thiết bị hiện đại, đảm bảo tính an toàn và hiệu quả điều trị
                                </div>
	  	  	 	 	 	 	</li>
	  	  	 	 	 	 	<li class="text-left">  
                                <div class="tt_menu">
                                	Bảo đảm an toàn  
                                </div>
                                <div class="nd_cover4 text-light pt-2 ">
                                
                                	<div class="nd_cv_1">
                                		- Môi trường được đảm bảo - phòng thủ thuật sạch sẽ vô khuẩn 
                                	</div>
                                	<div class="nd_cv_2">
                                		- Bác sỹ được đảm bảo - với đội ngũ y bác sỹ có trên 20 năm kinh nghiệm lâm sàng 
                                	</div>
                                	<div class="nd_cv_2">
                                		- Kinh nghiệm được đảm bảo - với hàng ngàn ca thủ thuật không sự cố 
                                	</div>
                                </div>
	  	  	 	 	 	 	</li>
	  	  	 	 	 	 </ul>
	  	  	 	 	 	 </div>
	  	  	 	 	 </div>
	  	  	 	 </div>
	  	  	 	 <div class="row justify-content-center">
	  	  	 	 	<a href="<?= $link_tv;?>"><button class="btn btn-warning nutbt hvr-push">Click tư vấn đặt hẹn </button></a>
	  	  	 	 </div>
	  	  	 </div>
	  	  </div>
	  	  <!-- footer -->
	  	  <footer class="p-5">
	  	  	  <div class="container">
	  	  	  	 <div class="row">
	  	  	  	 	 <div class="col-md-3">
	  	  	  	 	 	 <div class="nd_ft_1">
	  	  	  	 	 	 	 <img src="images/img_ft_1.png" alt="">
	  	  	  	 	 	 </div>
	  	  	  	 	 </div>
	  	  	  	 	 <div class="col-md-3 text-center">
	  	  	  	 	 	<div class="nd_khoi_2_ft">
	  	  	  	 	 	<div class="tt_ft_2 text-uppercase text-light">
	  	  	  	 	 		 <strong> Trung tâm có uy tín </strong>
	  	  	  	 	 	</div>
	  	  	  	 	 	<div class="menu_f">
	  	  	  	 	 		 <ul>
	  	  	  	 	 		 	 <li>
	  	  	  	 	 		 	 	 <a href="http://phongkhamgiaiphong.com/cd6/gioi-thieu/"> Giới thiệu phòng khám </a>
	  	  	  	 	 		 	 </li>
	  	  	  	 	 		 	 <li>
	  	  	  	 	 		 	 	 <a href="<?= $link_tv;?>">Thiết bị hiện đại </a>
	  	  	  	 	 		 	 </li>
	  	  	  	 	 		 	 <li>
	  	  	  	 	 		 	 	 <a href=""> Trường hợp khỏi bệnh  </a>
	  	  	  	 	 		 	 </li>
	  	  	  	 	 		 	 <li>
	  	  	  	 	 		 	 	 <a href="<?= $link_tv;?>"> Tư vấn chi phí  </a>
	  	  	  	 	 		 	 </li>
	  	  	  	 	 		 	 <li>
	  	  	  	 	 		 	 	 <a href="<?= $link_tv;?>"> Liên hệ với chúng tôi </a>
	  	  	  	 	 		 	 </li>	
	  	  	  	 	 		 	 <li>
	  	  	  	 	 		 	 	 <a href="<?= $link_tv;?>"> Đăng ký trực tuyến  </a>
	  	  	  	 	 		 	 </li>
	  	  	  	 	 		 </ul>
	  	  	  	 	 	</div>
	  	  	  	 	 	</div>
	  	  	  	 	 </div>
	  	  	  	 	 <div class="col-md-6">
	  	  	  	 	 	<div class="nd_ft_3">
	  	  	  	 	 		 <div class="tt_ft_3 text-center text-light"> <strong> Liên hệ chúng tôi </strong></div>
	  	  	  	 	 		 <div class="left_ft float-left">
	  	  	  	 	 		 	 <img src="http://taimuihonghanoi.net/wp-content/themes/168mauxanh/images/tel1.png" alt="">
	  	  	  	 	 		 </div>
	  	  	  	 	 		 <div class="float-right">
	  	  	  	 	 		 	 <img src="images/img_footer_3.png" alt="">
	  	  	  	 	 		 </div>
	  	  	  	 	 		 <div class="box30">
			                    <a href="<?= $link_tv;?>" target="_blank">
			                    	<img src="http://taimuihonghanoi.net/wp-content/themes/168mauxanh/images/i14.png">Hỏi bệnh tình
			                    </a> 
			                    <a href="<?= $link_tv;?>" target="_blank">
			                    	<img src="http://taimuihonghanoi.net/wp-content/themes/168mauxanh/images/i15.png">Hỏi điều trị
			                    </a> 
			                    <a href="<?= $link_tv;?>" target="_blank">
			                    	<img src="http://taimuihonghanoi.net/wp-content/themes/168mauxanh/images/i16.png">Hỏi chi phí
			                    </a>
               				 </div>
               				 <div class="copy">
               				 	 Copyright @ 2009-2018. Phong Kham Da Khoa Giai Phong. All rights reserved
               				 </div>
               				 <div class="copy">
               				 	ĐỊA CHỈ: 709 Giải Phóng - Hoàng Mai - HÀ NỘI
               				 </div>
               				 <div class="copy">
               				 	 Sở hữu bản quyền phòng khám Đa Khoa Giải Phóng, nội dung website này chỉ để tham khảo không làm căn cứ chẩn đoán y tế.Tôn trọng ý kiến bác sĩ
               				 </div>
	  	  	  	 	 	</div>
	  	  	  	 	 </div>
	  	  	  	 </div>
	  	  	  </div>
	  	  </footer>
	</div>
</body>
</html>