
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Điều trị</title>
    <script src="bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <link href="css/style.css" type="text/css" rel="stylesheet"/>
    <link href="css/custorm.css" type="text/css" rel="stylesheet"/>
    <script type="text/javascript"  src="js/bigpicroll.js"></script>
    <script type='text/javascript' src="js/jquery-1.4.4.min.js"></script>
    <script type="text/javascript"  src="js/js.js"></script>
    <script src="js/simplefoucs.js" type="text/javascript"></script>
    <base target="_blank">
</head>
<?php require_once('../../define.php'); ?>
<?php
$domain=domain;
$link_gioithieu=link_gioithieu;
$link_kythuat=link_kythuat;
$link_thietbi=link_thietbi;
$link_diachi=link_diachi;
$link_tuvan=link_tuvan;
$link_lotrinhdenkham=link_lotrinhdenkham;
$line_chat=line_chat();
?>
<body>
<div class="fram">
<div class="head">
    <?= cd_menu_top();?>
    <div class="banner" style="background: url('images/bg_banner.jpg') repeat-x">
        <div style="background:url(images/banner.jpg) no-repeat top center; overflow:hidden;width: 100%;height: 530px;">
            <div  style="width:1000px; margin:auto; height:100px;margin-top: 330px;">
                <a href="<?= $link_tuvan;?>" ><div style="width:240px; margin-left:40px; height:100px;"></div></a>
            </div>
        </div>
    </div>
</div>
<div class="" style="margin-top: -20px;">
    <div class="main_item main_item1">
        <div class="tit1"></div>
        <div class="clear2"></div>
        <div class="content">
            <div class="content_l">
                <p>Nguyên nhân phát bệnh trĩ chủ yếu có những loại sau: mệt mỏi quá độ, ngồi lâu, đứng lâu, ngồi xổm lâu, đi lại quá lâu... Ăn quá nhiều đồ ăn có chất béo, đồ ăn cay, uống rượu quá nhiều; đi đại tiện quá nhiều, thời gian quá lâu; huyết áp cao, gan xơ cứng, xơ vữa động mạch, viêm mãn tính trực tràng hậu môn... Biểu hiện triệu chứng như sau:</p>
                <div class="clear3"></div>
                <div class="">
                    <img src="images/item1_1.jpg" alt="">
                </div>
            </div>
            <div class="content_r">
                <h3>tại sao trĩ <span class="color_red">lại tái phát nhiều lần?</span></h3>
                <p>
                    <b>Thói quen không tốt như đừng nhiều ngồi nhiều cũng dễ dẫn đến trĩ </b><br>
                    Ngồi lâu sẽ gây ra trĩ, ngồi thời gian quá lâu, sự hồi lưu máu của  tĩnh mạch trực tràng hậu môn bị ảnh hưởng sẽ gây ra trĩ.
                </p>
                <p>
                    <b>Trĩ một khi đã hình thành thường sẽ không tự khỏi </b><br>
                    Trĩ nếu thời gian dài không điều trị, sẽ không thể tự khỏi, sẽ dẫn tới các biến chứng khác. Vì vậy khi bị trĩ, cần phải kịp thời đến các bệnh viện để kiểm tra điều trị.
                </p>
                <div style="margin-left: 16px;">
                    <ul>
                        <li>Đau khi đại tiện</li>
                        <li>Chảy dịch</li>
                        <li>Ngứa</li>
                        <li>Sa búi trĩ</li>
                        <li>Đại tiện khó</li>
                        <li>Đại tiện chảy máu</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="clear2"></div>
        <div class="canhbao">
            <img src="images/canhbao.png" alt="canh bao" style="float: left">
            <p>thông thường mọi người tìm hiểu, trĩ chỉ là một bệnh thường gặp. Không điều trị cũng không sao, cố gắng chịu sẽ qua, nhưng không biết đến mức độ nghiêm trọng của bệnh trĩ, tình trạng bình thường sẽ không thể tự khỏi, theo thời gian, tình trạng sẽ ngày càng nghiêm trọng hơn.</p>
        </div>
    </div>
    <div class="main_item main_item2">
        <div class="tit_vang">
            <div class="tit_vang_c" style="width: 400px;">
                <div class="tit_vang_l"><img src="images/bg_tit_vang_l.jpg" alt=""></div>
                <div class="tit_txt">Hình ảnh quá trình hình thành trĩ </div>
                <div class="tit_vang_r"><img src="images/bg_tit_vang_r.jpg" alt=""></div>
            </div>
        </div>
        <div>
            <img src="images/item2_1.jpg" alt="" style="text-align: center;margin-top: 15px;">
        </div>
    </div>
    <div class="clear3"></div>
    <div class="main_item main_item3">
        <div class="tit_vang">
            <div class="tit_vang_c" style="width: 365px;">
                <div class="tit_vang_l"><img src="images/bg_tit_vang_l.jpg" alt=""></div>
                <div class="tit_txt">Bệnh trĩ của bạn ở mức độ nào?</div>
                <div class="tit_vang_r"><img src="images/bg_tit_vang_r.jpg" alt=""></div>
            </div>
        </div>
        <div class="clear"></div>
        <div class="des">
            <b>Theo giai đoạn kiểm tra! Theo giai đoạn chủng loại trĩ</b>
            <p>
                Trĩ phân thành trĩ ngoại huyết khối, trĩ ngoại giãn tĩnh mạch, trĩ ngoại sưng mạch máu, trĩ ngoại tổ chức liên kết, trĩ nội u tĩnh mạch, phân thành: giai đoạn đầu, giai đoạn giữa và giai đoạn cuối
            </p>
        </div>
        <div class="clear3"></div>
        <div>
            <ul>
                <li>
                    <h3>giai đoạn đầu</h3>
                    <div>
                        <div class="tit3">
                            <div style="padding-left: 60px;">
                                <img src="images/ico_chamdo.png" alt=""><span>Trĩ nội độ II</span>
                            </div>
                        </div>
                        <p>
                            Hậu môn trướng tức, sưng và đau, búi trĩ khá to, khi đại tiện sa ra ngoài hậu môn
                        </p>
                        <p>
                            <img src="images/item3_1.jpg" alt="" style="text-align: center">
                        </p>
                    </div>
                    <div>
                        <div class="tit3">
                            <div style="padding-left: 60px;">
                                <img src="images/ico_chamdo.png" alt=""><span>Trĩ nội độ III</span>
                            </div>
                        </div>
                        <p>
                            Búi trĩ to lên, tăn sinh tổ chức liên kết, niêm mạc dày hơn, sau khi sa ra ngoài không thể tự co lại được.
                        </p>
                        <p>
                            <img src="images/item3_2.jpg" alt="" style="text-align: center">
                        </p>
                    </div>
                </li>
                <li>
                    <h3>giai đoạn giữa</h3>
                    <div>
                        <div class="tit3">
                            <div style="padding-left: 40px;">
                                <img src="images/ico_chamdo.png" alt=""><span>Trĩ ngoại huyết khối</span>
                            </div>
                        </div>
                        <p>
                            Đứt tĩnh mạch hậu môn, máu chảy ra ngoài hình thành huyết khối dưới da. Đặc điểm là đau dữ dội
                        </p>
                        <p>
                            <img src="images/item3_3.jpg" alt="" style="text-align: center">
                        </p>
                    </div>
                    <div>
                        <div class="tit3">
                            <div style="padding-left: 28px;">
                                <img src="images/ico_chamdo.png" alt=""><span>trĩ ngoại giãn tĩnh mạch</span>
                            </div>
                        </div>
                        <p>
                            Ảnh hưởng do táo bón và tiêu chảy, áo lực bụng kéo dài liên tục tăng cao, dẫn tới tĩnh mạch giãn, tụ máu.
                        </p>
                        <p>
                            <img src="images/item3_4.jpg" alt="" style="text-align: center">
                        </p>
                    </div>
                </li>
                <li>
                    <h3>giai đoạn cuối</h3>
                    <div>
                        <div class="tit3">
                            <div style="padding-left: 40px;">
                                <img src="images/ico_chamdo.png" alt=""><span>Trĩ hỗn hợp nhiều loại</span>
                            </div>
                        </div>
                        <p>
                            Đại tiện khó khăn, hậu môn có 1 vòng búi trĩ, thường có tình trạng đại tiện ra máu
                        </p>
                        <p>
                            <img src="images/item3_5.jpg" alt="" style="text-align: center">
                        </p>
                    </div>
                    <div>
                        <div class="tit3">
                            <div style="padding-left: 40px;">
                                <img src="images/ico_chamdo.png" alt=""><span>trĩ hỗn hợp phức tạp</span>
                            </div>
                        </div>
                        <p>
                            Triệu chứng chủ yếu là đại tiện ra máu, đau trực tràng hậu môn, trĩ hậu môn sa ra
                        </p>
                        <p>
                            <img src="images/item3_6.jpg" alt="" style="text-align: center">
                        </p>
                    </div>
                </li>
                <li>
                    <h3>biến chứng</h3>
                    <div>
                        <div class="tit3">
                            <div style="padding-left: 60px;">
                                <img src="images/ico_chamdo.png" alt=""><span>Viêm nhiễm</span>
                            </div>
                        </div>
                        <p>
                            Sau khi búi trĩ bị bó lại, dễ làm cho viêm nhiễm lây lan, gây ra dưới niêm mạc hoặc quanh hậu môn sưng có mủ
                        </p>
                        <p>
                            <img src="images/item3_7.jpg" alt="" style="text-align: center">
                        </p>
                    </div>
                    <div>
                        <div class="tit3">
                            <div style="padding-left: 75px;">
                                <img src="images/ico_chamdo.png" alt=""><span>hoại tử </span>
                            </div>
                        </div>
                        <p>
                            Trĩ nội huyết khối lan rộng ra, vùng hoại tử lan sang thành trực tràng, trong khoang chậu gây ra
                        </p>
                        <p>
                            <img src="images/item3_8.jpg" alt="" style="text-align: center">
                        </p>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="clear3"></div>
    <div class="main_item main_item4">
        <div class="tit_den">
            <div class="tit_den_c" style="width: 490px;">
                <div class="tit_den_l"><img src="images/bg_tit_den_l.jpg" alt=""></div>
                <div class="tit_txt">Phương pháp loại bỏ truyền thống, nguy hại lớn</div>
                <div class="tit_den_r"><img src="images/bg_tit_den_r.jpg" alt=""></div>
            </div>
        </div>
        <div class="clear3"></div>
        <div class="tiem4_content">
            <div class="tiem4_content_l">
                <div style="float: left">
                    <img src="images/item4_1.jpg" alt="">
                </div>
                <div style="float: left;width: 420px;">
                    <div style="padding-left: 20px;">
                        <b>Thủ thuật truyền thống: <span class="color_red">tổn thương hậu môn điều trị cơ bản không điều trị tổng thể</span></b><br>
                        <b>Uống thuốc</b>
                        <p><span class="color_red">Hiệu quả: </span>hiệu quả chậm, thời gian uống thuốc kéo dài, chi phí cao </p>
                        <p><span class="color_red">Nhược điểm: </span>uống trong thời gian dài, nhiều tác dụng phụ, dừng thuốc là tái phát. Có lúc có thể cầm máu được nửa năm.</p>
                        <b>Dùng ngoài</b>
                        <p><span class="color_red">Hiệu quả: </span>: có thể cải thiện triệu chứng, hiệu quả nhanh, nhưng dễ tái phát, điều trị cơ bản không điều trị tổng thể</p>
                        <p><span class="color_red">Nhược điểm: </span>trên thị trường có rất nhiều loại ghi có thể điều trị khỏi trĩ, thực ra những sản phẩm này chỉ có thể làm giảm triệu chứng.</p>
                    </div>
                </div>
                <div class="clear2"></div>
                <b>Thủ thuật truyền thống</b>
                <p><span class="color_red">Hiệu quả: </span>thường khiến cho bệnh nhân khó chịu, cần nằm viện, người bệnh nghĩ đến thủ thuật sẽ sợ hãi.</p>
                <p><span class="color_red">Nhược điểm: </span>sau thủ thuật đau và nằm viện khá lâu, thời gian lâu để lành lại, có khả năng tái phát.</p>
                <div class="clear2"></div>
                <b class="color_red">NHẮC NHỞ</b>
                <p>Động viên người bệnh ăn uống thường xuyên, không nên vì khó khăn khi đại tiện mà ăn ít đi. Tránh ăn các đồ cay nóng,</p>
                <a href="<?= $link_tuvan;?>"><img src="images/btn_tvtt.png" alt="" style="float: right"></a>
            </div>
            <div class="item4_content_r">
                <div style="padding-left: 40px;">
                    <img src="images/docky.png" alt="" style="text-align: center;">
                    <p style="text-align: justify">Thủ thuật điều trị trĩ truyền thống gây thương tổn cho bộ phận vùng hậu môn, do thần kinh vùng trực tràng hậu môn phân bố khá dày, mạch máu phong phú, thần kinh, cơ bắp liên quan mật thiết, thủ thuật phá vỡ tính hoàn chỉnh của hệ thống biểu bì, do đó đau là điều tất nhiên. Các bác sỹ phòng khám đa khoa Giải Phóng Hà Nội giới thiệu, quá trình thủ thuật trĩ truyền thống vô cùng đau, thời gian phục hồi kéo dài, sau thủ thuật thường đau vùng hậu môn, hậu môn phù nề, xuất huyết.... Gây cho bệnh nhân sự đau đớn và ảnh hưởng vô cùng lớn.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="main_item main_item5">
        <div class="tit_vang">
            <div class="tit_vang_c" style="width: 390px;">
                <div class="tit_vang_l"><img src="images/bg_tit_vang_l.jpg" alt=""></div>
                <div class="tit_txt">Xâm lấn tối thiểu, an toàn triệt để</div>
                <div class="tit_vang_r"><img src="images/bg_tit_vang_r.jpg" alt=""></div>
            </div>
        </div>
        <div class="clear"></div>
        <div class="item5_content">
            <div style="width: 345px;margin-left: 125px;overflow: hidden;float: left;">
                <div style="margin-top: 37px;text-align: justify">
                    Có thể trực tiếp tìm chính xác được vị trí động mạch bên trong trực tràng, dùng kim chuyên dụng để thắt nút, từ đó chặn nguồn cung cấp máu cho búi trĩ, khiến cho búi trĩ tự nhiên hoại tử rụng ra.
                </div>
                <div style="margin-top: 60px;text-align: justify">
                    Do phân bố vị trí thủ thuật ở vùng thần kinh thực vật,người bệnh sẽ không phải chịu đựng đau đớn như thủ thuật truyền thống.
                </div>
                <div style="margin-top: 75px;text-align: justify">
                    Thời gian thủ thuật thường là 26.5 phút, chỗ thủ thuật cực nhỏ, đại đa số người bệnh sau thủ thuật nghỉ ngơi một lúc là có thể ra về, không ảnh hưởng đến sinh hoạt.
                </div>
            </div>
            <div style="width: 280px;float: right;">
                <b>Chỉ loại bỏ trĩ, không để lại thương tổn, trĩ không tái phát</b>
                <div class="clear2"></div>
                <p>phòng khám đa khoa Giải Phóng Hà Nội nhập khẩu kỹ thuật tiên tiến loai bỏ trĩ PPH, thành công với các ưu thế vượt trội: an toàn, không đau, thời gian ngắn, thương tổn ít, phạm vi chẩn trị rộng. Từ đó phòng khám trở thành địa chỉ tin cậy trong việc điều trị bệnh trĩ trong nước.</p>
            </div>
        </div>
    </div>
    <div class="main_item main_item6">
        <div class="tit_vang">
            <div class="tit_vang_c" style="width: 560px;">
                <div class="tit_vang_l"><img src="images/bg_tit_vang_l.jpg" alt=""></div>
                <div class="tit_txt">Thiết bị kĩ thuật chuyên nghiệp, bác sỹ giàu kinh nghiệm </div>
                <div class="tit_vang_r"><img src="images/bg_tit_vang_r.jpg" alt=""></div>
            </div>
        </div>
        <div class="clear"></div>
        <div class="item6_content">
            <img src="images/item6_1.jpg" alt="" style="text-align: center">
        </div>
    </div>
    <div class="main_item main_item7">
        <div class="tit_vang">
            <div class="tit_vang_c" style="width: 245px;">
                <div class="tit_vang_l"><img src="images/bg_tit_vang_l.jpg" alt=""></div>
                <div class="tit_txt">Nguyên lý loại bỏ</div>
                <div class="tit_vang_r"><img src="images/bg_tit_vang_r.jpg" alt=""></div>
            </div>
        </div>
        <div class="clear"></div>
        <div class="item7_content">
            <p style="text-align: center">Điều trị căn cứ vào mức độ bệnh trĩ</p>
            <p style="text-align: center">Quá trình thủ thuật bệnh trĩ</p>
        </div>
        <div class="item7_content1">
            <div style="text-align: center">
                <img src="images/item7_1.jpg" alt="">
                <div>
                    <ul>
                        <li style="margin-left: 40px;">Tiêm vào vùng niêm mạc trên búi trĩ,<br> loại bỏ triệt để búi trĩ</li>
                        <li style="margin-left: 60px;">Kỹ thuật PPH được dùng trong thủ thuật,<br> dùng mỏ vịt đưa vào trong ống hậu môn</li>
                        <li></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="clear2"></div>
        <div class="item7_content2" style="text-align: center">
            <img src="images/item7_2.jpg" alt="">
            <div class="clear2"></div>
            <b class="color_red">Loại trĩ không giống nhau, phương pháp thủ thuật cũng không giống nhau,<br>chẩn đoán sớm, điều trị sớm</b>
        </div>
        <div class="clear3"></div>
        <div class="item7_content3">
            <div class="w40" style="width: 50%;">
                <img src="images/item7_3.jpg" alt="">
            </div>
            <div class="w60" style="width: 50%">
                <b class="tit7">trĩ ngoại độ nặng</b>
                <div class="clear"></div>
                <p>Họ tên người bệnh: Nguyễn Văn Dũng    chức vụ: nhân viên công ty</p>
                <p>
                    <b><span class="color_red">Triệu chứng:</span> trĩ ngoại, đau 5 năm, gần đây triệu chứng nặng hơn</b>
                </p>
                <div class="clear"></div>
                <p style="text-align: justify">Trĩ ngoại, đau trong 5 năm, gần đây triệu chứng nặng hơn, đi lại khó khăn, đã đi nhiều nơi điều trị, thủ thuật 1 lần, hiệu quả không rõ rệt. Sau đó được người bạn gới thiệu đến phòng khám đa khoa Giải Phóng Hà Nội, được các bác sỹ trực tiếp thăm khám cho, bác sỹ tiến hành kiểm tra soi hậu môn, xác định trĩ ngoại độ nặng. Đề nghị bác sỹ thực hiện luôn thủ thuật xâm lấn tối thiểu HCPT để điều trị bệnh trĩ.</p>
            </div>
            <div class="clear"></div>
            <div class="tit_den2" style="text-align: center">
            </div>
            <div class="w60">
                <b class="tit7">Hình ảnh trĩ hỗn hợp dạng vòng</b>
                <div class="clear"></div>
                <p>Họ tên bệnh nhân: Phạm Thị Mai Hồng    Chức vụ: nhân viên công ty</p>
                <p>
                    <b><span class="color_red">Triệu chứng:</span>đi ngoài ra máu, màu đỏ tươi, dính ở giấy vệ sinh hoặc nhỏ giọt</b>
                </p>
                <div class="clear"></div>
                <p style="text-align: justify">
                    Nửa năm trước đại tiện ra máu không rõ rệt, máu màu đỏ tươi, nhỏ giọt hoặc có dính ở giấy vệ sinh, búi trĩ sa ra ngoài, sau khi đi vệ sinh có thể tự co lại, khi không đi vệ sinh đau hậu môn. Đã từng đi khám ở bệnh viện, được chẩn đoán là “trĩ hỗn hợp”, dùng thuốc bôi ngoài, triệu chứng có thuyên giảm. Trước đây 3 ngày do ăn đồ cay nóng, bệnh tình lại nặng hơn, búi trĩ sa ra ngoài phải dùng tay đẩy vào, kèm theo đau dữ dội, khi đại tiện có chảy máu thành giọt, màu đỏ tươi. Ngày hôm nay đến phòng khám đa khoa Giải Phóng Hà Nội để điều trị.
                </p>
            </div>
            <div class="w40">
                <img src="images/item7_4.jpg" alt="">
            </div>
            <div class="clear"></div>
            <div class="tit_den2" style="text-align: center">
            </div>
            <div class="w40">
                <img src="images/item7_5.jpg" alt="">
            </div>
            <div class="w60">
                <b class="tit7">trĩ - bệnh điển hình</b>
                <div class="clear"></div>
                <p>Họ tên người bênh: Trịnh Văn Mạnh     Chức vụ: nhân viên công ty</p>
                <p>
                    <b><span class="color_red">Triệu chứng người bệnh:</span>khi đi đại tiện không phát hiện ra triệu chứng phân có máu </b>
                </p>
                <div class="clear"></div>
                <p style="text-align: justify">
                    Nguyên nhân không đặc thù, khi đi đại tiện không phát hiện ra triệu chứng phân có máu, máu có màu đỏ tươi, có lúc nhỏ giọt, hoặc dính vào giấy vệ sinh, đại tiện ra máu đã bị 1 năm, còn kèm theo sa búi trĩ, không thể tự động co lại, cần dùng tay đẩy vào. Khi đại tiện thỉnh thưởng có cảm giác đau. Do thiếu kiến thức về bệnh trĩ, công việc khá bận rộng, nên không có thời gian đến bệnh viện để kiểm tra. Cho đến tháng 3 năm nay, bị chóng mặt hoa mắt, ngất trên bàn làm việc mới đến bệnh viện để kiểm tra.
                </p>
            </div>
        </div>
    </div>
    <div class="clear3"></div>
    <div class="main_item main_item8">
        <div class="tit_den">
            <div class="tit_den_c" style="width: 875px;">
                <div class="tit_den_l"><img src="images/bg_tit_den_l.jpg" alt=""></div>
                <div class="tit_txt">Thương hiệu và thực lực</div>
                <div class="tit_den_r"><img src="images/bg_tit_den_r.jpg" alt=""></div>
            </div>
        </div>
        <div class="clear3"></div>
        <div class="item8_content">
            <div class="w30">
                <ul>
                    <li>
                        <div class="border_l">
                            <b>Phòng khám trực tràng hậu môn chuyên nghiệp ở Hà Nội</b>
                            <p>Phòng khám quy mô lớn, thiết bị đầy đủ, bác sỹ giỏi, kỹ thuật tốt... Là phòng khám trực tràng hậu môn chuyên nghiệp ở Hà Nội, những năm gần đây đã điều trị khỏi cho hàng vạn bệnh nhân, sau thủ thuật phục hồi nhanh, hiệu quả tốt.</p>
                            <img src="images/item8_1.jpg" alt="">
                        </div>
                    </li>
                    <li>
                        <div class="border_l">
                            <b>Bác sỹ chuyên nghiệp</b>
                            <p>Phòng khám có các bác sỹ chuyên nghiệp với hơn 20 kinh nghiệm lâm sàng trực tiếp khám bệnh, thực hiện hàng vạn ca thủ thuật không sự cố, đảm bảo an toàn, kết hợp kỹ thuật tiên tiến quốc tế, điều trị có sự đảm bảo hơn.</p>
                            <img src="images/item8_2.jpg" alt="">
                        </div>
                    </li>
                    <li>
                        <div class="border_l">
                            <b>nhập khẩu kỹ thuật tiên tiến quốc tế đa hạng mục</b>
                            <p>Bao gồm kỹ thuật xâm lấn tối thiểu HCPT, kỹ thuật COOK, kỹ thuật xâm lấn tối thiểu PPH,  máy soi trực tràng hậu môn điện tử DR.C Hàn Quốc...</p>
                            <img src="images/item8_3.jpg" alt="">
                        </div>
                    </li>
                </ul>
            </div>
            <div class="w70">
                <div style="text-align: center;width: 80%;margin: auto">
                    <b>Nhập khẩu kỹ thuật trực tràng hậu môn,<br>mở ra thời đại mới trong việc loại bỏ trĩ xâm lấn tối thiểu</b>
                    <p style="padding: 10px 0">phòng khám đa khoa Giải Phóng Hà Nội thực tiễn lâm sàng nhiều năm cho thấy thủ thuật truyền thống không đủ đáp ứng, theo đặc điểm kỹ thuật quốc tế hiện nay, qua thực nghiệm khoa học và nghiên cứu, thực hiện loại bỏ trĩ tiên tiến quốc tế.</p>
                    <b>Điều trị nhằm đúng bệnh, triệu chứng khác nhau áp dụng điều trị khác nhau</b>
                </div>
                <div class="clear3"></div>
                <div style="text-align: center">
                    <img src="images/item8_4.jpg" alt="">
                </div>
                <div class="clear3"></div>
                <div class="item8_content_3" style="text-align: center">
                    <b>Tiêu chuẩn dịch vụ cá nhân hóa</b>
                    <div class="clear2"></div>
                    <ul>
                        <li>
                            <div>
                                <img src="images/item8_5.jpg" alt="">
                                <b>Phòng khám không ngày nghỉ</b>
                                <p>Phòng khám thực hiện không ngày nghỉ, làm việc cả chủ nhật và ngày lễ </p>
                            </div>

                        </li>
                        <li>
                            <div>
                                <img src="images/item8_6.jpg" alt="">
                                <b>Thời gian hợp lý hơn</b>
                                <p>Thời gian làm việc từ <br>7h30 - 20h00</p>
                            </div>
                        </li>
                        <li>
                            <div>
                                <img src="images/item8_8.jpg" alt="">
                                <b>Hình thức chẩn trị hiện đại</b>
                                <p>Phương thức khám một bác sỹ một bệnh nhân, tư vấn cho bệnh nhân chu đáo</p>
                            </div>
                        </li>
                        <li>
                            <div>
                                <img src="images/item8_9.jpg" alt="">
                                <b>Hướng dẫn toàn bộ quá trình</b>
                                <p>Toàn bộ quá trình có lễ tân hướng dẫn, giúp bạn trải nghiệm dịch vụ đặc biệt</p>
                            </div>
                        </li>
                        <li>
                            <div>
                                <img src="images/item8_10.jpg" alt="">
                                <b>Bảo mật thông tin</b>
                                <p>Bảo mật thông tin, đảm bảo sự riêng tư, người bệnh yên tâm khám bệnh</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="clear3"></div>
    <div class="main_item main_item9">
        <div class="item9_content">
            <div style="width: 545px;margin-left: 40px;">
                <div style="width: 160px;text-align: right;margin-top: 170px;margin-left: 210px;">
                    <b style="text-transform: uppercase;">giải đáp nhiệt tình</b>
                    <p>Toàn bộ quá trình đều là một bệnh nhân một bác sỹ phục vụ cho bạn</p>
                </div>
                <div class="clear3"></div>
                <ul>
                    <li class="l color_red">
                        Hỏi
                    </li>
                    <li class="r">
                        <p>
                            gần đây tôi bị đại tiện ra máu, đi khám bác sỹ thì được biết bị trĩ hỗn hợp, nứt kẽ hậu môn, vậy có nghiêm trọng không?
                        </p>
                    </li>
                    <div class="clear"></div>
                    <li class="l">
                        Trả lời
                    </li>
                    <li class="r">
                        <p>
                            nếu những triệu chứng này đều có, thì khá nghiêm trọng. Đến giai đoạn này, thuốc đã không còn có tác dụng, thủ thuật sẽ có hiệu quả tốt, sau thủ thuật bệnh thường không tái phát, nhưng không thể loại bỏ những khả năng khác.
                        </p>
                        <a href="<?= $link_tuvan;?>"> >>>Bác sỹ phòng khám đa khoa Giải Phóng Hà Nội</a>
                    </li>
                </ul>
                <div class="bg_hoidap"></div>
                <ul>
                    <li class="l color_red">
                        Hỏi
                    </li>
                    <li class="r">
                        <p>
                            mông đau cứng, hình như là có một cục thịt ở đó, tôi phải làm sao?
                        </p>
                    </li>
                    <div class="clear"></div>
                    <li class="l">
                        Trả lời
                    </li>
                    <li class="r">
                        <p>
                            rất nhiều bệnh nhân không biết ở hậu môn có cục thịt thò ra là đang bị làm sao, từ đó dẫn đến chẩn đoán và điều trị sai. Trên lâm sàng việc dẫn đến ở hậu môn có cục thịt có rất nhiều nguyên nhân, trĩ ngoại viêm nhiễm, trĩ ngoại huyết khối, nứt kẽ hậu môn... Nhất định phải điều trị kịp thời. Hậu môn có cục thịt nhất định cần phải kiểm tra sớm, có thể áp dụng kỹ thuật điều trị HCPT
                        </p>
                        <a href="<?= $link_tuvan;?>"> >>>Bác sỹ phòng khám đa khoa Giải Phóng Hà Nội</a>
                    </li>
                </ul>
                <div class="bg_hoidap"></div>
                <ul>
                    <li class="l color_red">
                        Hỏi
                    </li>
                    <li class="r">
                        <p>
                            đại tiện ra máu có phải bị trĩ hay không?
                        </p>
                    </li>
                    <div class="clear"></div>
                    <li class="l">
                        Trả lời
                    </li>
                    <li class="r">
                        <p>
                            đại tiện ra máu cần xem xét có liên quan đến bệnh trĩ, đề nghị bác sỹ kiểm tra hậu môn. Điều trị trĩ đầu tiên cần phải đảm bảo đại tiện thông suốt, thức ăn dễ tiêu hóa, hạn chế ăn thức ăn cay nóng, ăn đồ ăn cần nhai kí, sau đại tiện cần ngâm rửa nước ấm, cục bộ cần bôi thuốc trĩ. Nếu triệu chứng nặng hơn nhất định phải điều trị bằng thủ thuật, có thể áp dụng điều trị tiêm, điều trị xâm lấn tối thiểu hoặc vật lý trị liệu.
                        </p>
                        <a href="<?= $link_tuvan;?>"> >>>Bác sỹ phòng khám đa khoa Giải Phóng Hà Nội</a>
                    </li>
                </ul>
                <div class="bg_hoidap"></div>
                <ul>
                    <li class="l color_red">
                        Hỏi
                    </li>
                    <li class="r">
                        <p>
                            nữ giới có bị trĩ hay không, có thì phải làm thế nào?
                        </p>
                    </li>
                    <div class="clear"></div>
                    <li class="l">
                        Trả lời
                    </li>
                    <li class="r">
                        <p>
                            đại tiện ra máu là triệu chứng chủ yếu của bệnh trĩ, có cảm giác đau. Táo bón, nóng trong, ngồi lâu, ăn không điều độ đều là nguyên nhân dẫn đến bệnh trĩ. Điều trị trĩ cần phải điều chỉnh ăn uống, không ăn đồ cay nóng, không uống rượu bia, không thức thâu đêm, vận động nhiều, ăn nhiều rau xanh, nếu triệu chứng kéo dài thì mà không thuyên giảm thì cần phải xem xét làm thủ thuật điều trị trĩ.
                        </p>
                        <a href="<?= $link_tuvan;?>"> >>>Bác sỹ phòng khám đa khoa Giải Phóng Hà Nội</a>
                    </li>
                </ul>
                <div class="bg_hoidap"></div>
                <ul>
                    <li class="l color_red">
                        Hỏi
                    </li>
                    <li class="r">
                        <p>
                            điều trị trĩ khỏi rồi lại tái phát, nếu làm thủ thuật xâm lấn tối thiểu có tái phát nữa không?
                        </p>
                    </li>
                    <div class="clear"></div>
                    <li class="l">
                        Trả lời
                    </li>
                    <li class="r">
                        <p>
                            bệnh trĩ là tụ máu của tĩnh mạch dưới trực tràng, triệu chứng chủ yếu là đại tiện ra máu, đại tiện đau, hậu môn xuất hiện búi trĩ. Kiêng ăn đồ cay nóng, kiêng uống bia rượu, hình thành thói quen tốt, thủ thuật thông thường không tái phát.
                        </p>
                        <a href="<?= $link_tuvan;?>"> >>>Bác sỹ phòng khám đa khoa Giải Phóng Hà Nội</a>
                    </li>
                </ul>
                <div class="bg_hoidap"></div>
            </div>
        </div>
    </div>
</div>
<?= cd_footer();?>
</div>
</body>
</html>
