<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <title>Xuất tinh sớm</title>
      <meta name="description" content="Xuất tinh sớm hãy đến phòng khám Giải Phóng hà nội">
      <meta name="keywords" content="Xuật tinh sớm,xuat tinh som">
      <link href="images/main.css" rel="stylesheet" type="text/css">
      <link href="images/main(1).css" rel="stylesheet" type="text/css">
      <link rel="stylesheet" href="images/share_style2_24.css" />
	  <base target="_blank" />
   </head>
   <body>
   <?php require_once('../../define.php');?>
   <?php
   $domain=domain;
   $link_gioithieu=link_gioithieu;
   $link_thietbi=link_thietbi;
   $link_kythuat=link_kythuat;
   $link_tuvan=link_tuvan;
   $link_diachi=link_diachi;
   $link_skype=link_skype;
   $link_facebook=link_facebook;
   $line_chat=line_chat();
   ?>
      <div id="nav">
         <div class="nav_in">
            <div class="logo"><a href="#/" target="_blank"><img src="http://khamnamkhoahanoi.vn/public/frontend/img/home/logo.png"></a></div>
            <div class="nav_list fwryh">
               <div class="nav_list_bg" style="opacity: 0; left: 649.63px;"><span style="display: none;"></span></div>
               <ul class="bg">
                  <li class="f"></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
               </ul>
               <ul class="txt">
                  <li class="f">
                     <a href="<?= $domain;?>" target="_blank">
                        <div class="box">
                           <p>Trang chủ</p>
                           <span>HOME</span>
                        </div>
                     </a>
                  </li>
                  <li class="">
                     <a href="<?= $link_gioithieu;?>" target="_blank">
                        <div class="box">
                           <p>Giới thiệu</p>
                           <span>INTRODUCE</span>
                        </div>
                     </a>
                  </li>
                  <li class="">
                     <a href="<?= $link_tuvan;?>" target="_blank">
                        <div class="box">
                           <p>Bác Sĩ</p>
                           <span>EXPERTS</span>
                        </div>
                     </a>
                  </li>
                  <li class="">
                     <a href="<?= $link_kythuat;?>" target="_blank">
                        <div class="box">
                           <p>Kỹ thuật</p>
                           <span>TECHNOLOGY</span>
                        </div>
                     </a>
                  </li>
                  <li class="">
                     <a href="<?= $link_thietbi;?>" target="_blank">
                        <div class="box">
                           <p>Thiết bị</p>
                           <span>CASE</span>	
                        </div>
                     </a>
                  </li>
                  <li class="last">
                     <a href="<?= $link_diachi;?>" target="_blank">
                        <div class="box">
                           <p>Địa chỉ</p>
                           <span>GUIDE</span>
                        </div>
                     </a>
                  </li>
               </ul>
            </div>
         </div>
      </div>
      <div id="banner" style="text-align:center;background: #f3f3f3;">
			<img src="images/banner.jpg" border="0" usemap="#Map8">
        
      </div>
      <div id="title">
         <div class="tt">
            <span>
               <img src="images/title.jpg" border="0" usemap="#Map7">
			     <a href="<?= $link_tuvan;?>">
               <map name="Map7" id="Map7" style="width: 168px;  height: 29px;float: right;position:absolute;right: 0;   top: 41px;">
                
               </map>
			   </a>
            </span>
            <h3>3 cách giúp bạn nhận biết xuất tinh sớm </h3>
         </div>
         <div class="box">
            <span><img src="images/m_pic.jpg" width="346" height="198"></span> <strong>Nghĩa là trong số lần quan hệ tình dục có hơn nửa không mang lại khoái cảm cho đối phương, thời gian xuất tinh khoảng trên 10 phút và dưới 15 phút</strong> <span style="margin-top:5px;"><img src="images/m1_pic4.jpg"></span>
            <p>Nhu cầu: cao&nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
            <p>Thời gian: khoảng 10-15 phút&nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
            <p>Độ hài lòng: bình thường &nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
            <p>Mức độ tự tin: bình thường &nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
         </div>
         <div class="box">
            <span><img src="images/m_pic2.jpg" width="346" height="198"></span> <strong>Dương vật đưa vào âm đạo chuyển động liên tục không được 60 lần, thời gian khoảng từ 5-10 phút liền xuất tinh.</strong> <span style="margin-top:5px;"><img src="images/m1_pic4.jpg"></span>
            <p>Nhu cầu: bình thường&nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
            <p>Thời gian:khoảng 5-10 phút &nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
            <p>Độ hài lòng: không hài lòng lắm &nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
            <p>Mức độ tự tin: bình thường &nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
         </div>
         <div class="box" style="margin-right:0">
            <span><img src="images/m_pic3.jpg" width="346" height="198"></span> <strong>Dương vật sau khi cương cứng, chưa kịp đưa vào âm đạo hoặc cho vào khoảng 5 phút đã xuất tinh</strong> <span style="margin-top:5px;"><img src="images/m1_pic4.jpg"></span>
            <p>Ham muốn: thấp &nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
            <p>Thời gian: khoảng 5 phút &nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
            <p>Độ hài lòng: không hài lòng &nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
            <p>Mức độ tự tin: thấp &nbsp;&nbsp;&nbsp;<font style="color:#ca771d">★★★</font></p>
         </div>
         <div class="line"><span><a href="<?= $link_tuvan;?>">Bạn thuộc mức độ nào?<br> Hãy nói với bác sỹ để có cách giải quyết! </a></span></div>
      </div>
      <div id="box2">
         <div class="hexagon">
            <span><img src="images/img_.png"></span>
            <p class="t1"><a href="<?= $link_tuvan;?>">Không thể kéo dài <br> hoặc cương cứng không lâu
               </a>
            </p>
            <p class="t2"><a href="<?= $link_tuvan;?>">Xuất tinh ngược dòng </a></p>
            <p class="t2"><a href="<?= $link_tuvan;?>">Quy đầu chạm vào đau </a></p>
            <p class="t1"><a href="<?= $link_tuvan;?>">Căng thẳng bất an<br> lo lắng <br>
               </a>
            </p>
            <p class="t2"><a href="<?= $link_tuvan;?>">Nhu cầu thấp </a></p>
         </div>
         <div class="hexagon2">
            <p class="t2"><a href="<?= $link_tuvan;?>">Dương vật không <br>sưng đau </a></p>
            <p class="t1"><a href="<?= $link_tuvan;?>">Đau tinh hoàn 
               </a>
            </p>
            <p class="t2"><a href="<?= $link_tuvan;?>">Thời gian xuất tinh ngắn </a></p>
            <p class="t2"><a href="<?= $link_tuvan;?>">Xuất tinh không<br> có lực </a></p>
            <p class="t2"><a href="<?= $link_tuvan;?>">Đau lưng mỏi gối </a></p>
         </div>
      </div>
      <div id="title2">
         <div class="mian">
            <div class="tt">
               <span>
                  <img src="images/title2.jpg" border="0" usemap="#Map6">
			     <a href="<?= $link_tuvan;?>">
               <map name="Map7" id="Map7" style="width: 168px;  height: 29px;float: right;position:absolute;right: 0;   top: 41px;">
                
               </map>
			   </a>
               </span>
               <h3>Xuất tinh sớm tại sao lại xảy ra với bạn</h3>
			   <p style="    text-align: center;text-transform: uppercase; color: #999;"> Giới thiệu kỹ thuật </p>
            </div>
            <div class="box">
               <span><img src="images/m2_pic.jpg"></span>

               <p>Bao quy đầu dài do bao quy đầu dài hoặc bao quy đầu trong thời gian dài bị bao phủ bởi lớp da quy đầu, ít tiếp xúc với các vật bên ngoài, khi quan hệ tình dục....
               </p>
               <font><a href="<?= $link_tuvan;?>">Tư vấn chi tiết&gt;&gt;</a></font> 
            </div>
            <div class="box">
               <span><img src="images/m2_pic2.jpg"></span>

               <p>Độ nhạy cảm ở dây thần kinh quy đầu cao do cảm giác dương vật quá nhạy cảm hoặc dây thần kinh cảm giác hưng phấn tăng cao, trong khi xuất tinh .....
               </p>
               <font><a href="<?= $link_tuvan;?>">Tư vấn chi tiết&gt;&gt;</a></font> 
            </div>
            <div class="box">
               <span><img src="images/m2_pic3.jpg"></span>

               <p>Bệnh biến cơ quan sinh dục dẫn đến dị tật bẩm sinh cơ quan sinh dục, viêm nhiễm bao quy đầu, dương vật, viêm niệu đạo, viêm dương vật... 
               </p>
               <font><a href="<?= $link_tuvan;?>">Tư vấn chi tiết&gt;&gt;</a></font> 
            </div>
         </div>
      </div>
      <div id="title3">
         <div class="tt">
            <span>
               <img src="images/title3.jpg" border="0" usemap="#Map5">
			     <a href="<?= $link_tuvan;?>">
               <map name="Map7" id="Map7" style="width: 168px;  height: 29px;float: right;position:absolute;right: 0;   top: 41px;">
                
               </map>
			   </a>
            </span>
            <h3>Bạn không có nhu cầu, ai thỏa mãn cho cô ấy? </h3>
            <p>Nguy hại của xuất tinh sớm khiến bạn không thể ngẩng cao đầu trước đối phương được. </p>
         </div>
         <div class="box">
            <span><img src="images/m3_pic.jpg"></span>
			<p>
Trong quan hệ tình dục không thể “hết mình”, đối phương không cảm nhận thấy khoái cảm, không được thỏa mãn, tất yếu sẽ trở thành mối tiềm ẩn tan vỡ gia đình. </p>
         </div>
         <div class="box2">

            <p>Xuất tinh sớm ảnh hưởng đến sinh sản, không thể hoàn thành việc tinh trùng đưa vào trong tử cung nữ giới, từ đó dẫn đến vô sinh. </p>
            <span><img src="images/m3_pic2.jpg"></span>
         </div>
         <div class="box">
            <span><img src="images/m3_pic3.jpg"></span>
            <p>Dẫn đến các bệnh khác, xuất tinh sớm còn dẫn đến suy yếu thần kinh, và gây ra các biến chứng khác như viêm tiền liệt tuyến, lâu dài còn dẫn đến rối loạn chức năng cương cứng, liệt dương... </p>
         </div>
         <div class="box2">

            <p>Làm mất tự tin: xuất tinh sớm làm cho rất nhiều nam giới cảm thấy không hài lòng bản thân, từ đó gây ra rối loạn tâm lý, giảm sự tự tin, bệnh tình nặng thêm, hình thành tuần hoàn ác tính. </p>
            <span><img src="images/m3_pic4.jpg"></span>
         </div>
         <div class="line"><span><a href="<?= $link_tuvan;?>">Bạn gái cho rằng bạn không được<br> làm sao để thỏa mãn cô ấy? </a></span></div>
      </div>
      <div id="title4">
         <div class="mian">
            <div class="tt">
               <span>
                  <img src="images/title4.jpg" border="0" usemap="#Map4">
			     <a href="<?= $link_tuvan;?>">
					<map name="Map7" id="Map7" style="width: 168px;  height: 29px;float: right;position:absolute;right: 0;   top: 41px;">
					</map>
					</a>
               </span>
               <h3>Điều trị xuất tinh sớm cần phải kiểm tra chính xác, bạn có biết không? </h3>
               <p>phòng khám đa khoa Giải Phóng Hà Nội nhập khẩu thiết bị hiện đại hàng đầu từ nước ngoài:<br>máy kiểm tra thần kinh nhạy cảm của Mỹ để kiểm tra các mục, kiểm tra chính xác nguyên nhân bệnh, có thể giảm chi phí và thời gian điều trị. </p>
            </div>
            <div class="box">
               <p>Kiểm tra thể hang dương vật là việc kiểm tra trực tiếp sự bất thường của hệ thống tĩnh mạch dương vật, có thể phản ánh được sự hồi lưu tĩnh mạch dương vật, sự thay đổi bệnh lý và kết cấu trong thể hang dương vật</p>
               <font> Kiểm tra thể hang dương vật là kiểm tra trực tiếp sự bất thường hệ thống tĩnh mạch dương vật, có thể biểu hiện chính xác quá trình thay đổi về phương diện xuất tinh. </font>
            </div>
         </div>
      </div>
      <div id="t4_box">
         <h3>Sợ phiền phức? Việc kiểm tra thực ra rất đơn giản </h3>
         <div class="box">
            <span><img src="images/m4_pic5.jpg"></span>
            <p>10 phút sẽ có kết quả kiểm tra, tiết kiệm thời gian</p>
            <font><a href="<?= $link_tuvan;?>">Tư vấn trực tuyến&gt;&gt;</a></font>
         </div>
         <div class="box">
            <span><img src="images/m4_pic6.jpg"></span>
            <p>Căn cứ vào mức độ xuất tinh sớm có thể kiểm tra 2-3 mục, rất đơn giản</p>
            <font><a href="<?= $link_tuvan;?>">Tư vấn trực tuyến&gt;&gt;</a></font>
         </div>
         <div class="box">
            <span><img src="images/m4_pic7.jpg"></span>
            <p>Chi phí kiểm tra không cao, chi phí thấp yên tâm điều trị </p>
            <font><a href="<?= $link_tuvan;?>">Tư vấn trực tuyến&gt;&gt;</a></font>
         </div>
      </div>
      <div id="title5">
         <div class="tt">
            <span>
               <img src="images/title5.jpg" border="0" usemap="#Map3">
			     <a href="<?= $link_tuvan;?>">
					<map name="Map7" id="Map7" style="width: 168px;  height: 29px;float: right;position:absolute;right: 0;   top: 41px;">
					</map>
					</a>
            </span>
            <h3>Điều trị xuất tinh sớm, cần điều trị đúng</h3>
			<p style="    text-align: center;text-transform: uppercase; color: #999;"> Giới thiệu kỹ thuật </p>
         </div>
         <div class="box">
            <span><img src="images/m5_pic.jpg"></span> <font>Hẹp bao quy đầu dẫn <br/> đến xuất tinh sớm </font>
			<p class="gioi-thieu-thiet-bi">Giới thiệu thiết bị</p>
            <h3>Kỹ thuật chỉnh hình bao quy đầu dương vật không đau công nghệ Châu Âu</h3>
            <p>Mỹ quan tự nhiên, kéo dài cuộc yêu </p>
         </div>
         <div class="box">
            <span><img src="images/m5_pic2.jpg"></span> <font>Viêm tiền liệt tuyến<br/>dẫn đến xuất tinh sớm </font><p class="gioi-thieu-thiet-bi" style="left: 17px;">Giới thiệu thiết bị</p>
            <h3>Hệ thống điều trị hiệu ứng đa năng tiền liệt tuyến</h3>
            <p>Không tái phát, liệu trình ngắn</p>
         </div>
         <div class="box">
            <span><img src="images/m5_pic3.jpg"></span> <font>Viêm nhiễm đường tiết niệu<br/> dẫn đến xuất tinh sớm </font><p class="gioi-thieu-thiet-bi" style="left: 17px;">Giới thiệu thiết bị</p>
            <h3>Hệ thống phục hồi Gene viêm nhiễm bộ phận sinh dục GPH</h3>
            <p>Hiệu quả nhanh, diệt khuẩn toàn diện, không tái phát</p>
         </div>
         <div class="box">
            <span><img src="images/m5_pic4.jpg"></span> <font>Yếu tố tâm lý dẫn<br> đến xuất tinh sớm </font>
<p class="gioi-thieu-thiet-bi" style="left: 22px;">Giới thiệu thiết bị</p>           
		   <h3>Vợ chồng cùng điều trị, điều chỉnh tâm lý, chỉ đọa hành vi</h3>
            <p>Không thủ thuật, không tiêm, hiệu quả tốt </p>
         </div>
      </div>
      <div id="t5_box">
         <div class="tt">
            <font>Quy đầu dương vật nhạy cảm dẫn đến xuất tinh sớm </font>
            <h3>Giới thiệu kỹ thuật: thủ thuật chặn dây thần kinh lưng dương vật thế hệ mới</h3>
            <p>Đầu tiên thông qua máy kiểm tra thần kinh nhạy cảm dương vật để xác định giá trị van hãm, dưới hệ thống định vị hiển vi của Mỹ định vị chính xác số lượng tổ chức thần kinh lưng dương vật, bác sỹ có thể thông qua màn hình điện tử, phân biệt chính xác thần kinh khoái cảm và thần kinh nhạy cảm của cơ quan sinh dục, tiến hành lựa chọn giảm đi số lượng và vị trí thần kinh nhạy cảm, áp dụng thủ thuật xâm lấn tối thiểu, tiến hành cắt thần kinh lưng dương vật dư thùa, nâng cao giá trị van hãm kích thích thần kinh, kéo dài thời gian xuất tinh, thời gian thủ thuật được rút ngắn tối thiểu, sau thủ thuật Thời gian quan hệ có thể kéo dài khoảng 5-20 phút... [<a href="<?= $link_tuvan;?>">Xem thêm</a>]</p>
         </div>
         <div class="left">
            <span><img src="images/m5_img.jpg"></span>
            
         </div>
         <div class="right">
		 <h3>Thủ thuật chặn dây thần kinh lưng dương vật thế hệ mới, thực hiện “chi tiết hóa” thủ thuật xuất tinh sớm. </h3>
            <p> </p>
            <dl>
               <dt><img src="images/m5_pic6.jpg"></dt>
               <dd>Chính xác: lâm sàng cho thấy, thủ thuật chặn dây thần kinh lưng dương vật thế hệ mới được thực hiện dưới hệ thống định vị hiển vi của Mỹ, gần như không gây thương tổn mạch máu, mạch bạch huyết, phân tích chính xác thần kinh nhạy cảm và thần kinh khoái cảm, thao tác an toàn và nhanh gọn.</dd>
            </dl>
            <dl style="border:none; margin-bottom:20px;">
               <dt style="    padding-top: 11px"><img src="images/m5_pic7.jpg"></dt>
               <dd>Thủ thuật được thực hiện dưới hệ thống định vị hiển vi của Mỹ, vị trí thủ thuật được phóng to gấp 100 lần, vết thương nhỏ hơn, ngoại quan dương vật không thay đổi, hiệu quả điều trị cao. </dd>
            </dl>
            <font><a href="<?= $link_tuvan;?>">Tư vấn trực tuyến tìm hiểu chi tiết tình trạng bệnh &gt;&gt;</a></font> 
         </div>
      </div>
      <div id="t5_box2">
         <h3>6 tiêu chuẩn lớn, loại bỏ nỗi lo lắng của bạn!</h3>

         <div class="box">
            <span><img src="images/m5_pic11.jpg"></span> <font>Tính chính xác </font>
            <p>Căn cứ vào thần kinh nhạy cảm có thể kiểm tra được </p>
         </div>
         <div class="box">
            <span><img src="images/m5_pic12.jpg"></span> <font>Tính thích ứng </font>
            <p>Nam giới tuổi trưởng thành đều có thể làm được thủ thuật</p>
         </div>
         <div class="box">
            <span><img src="images/m5_pic13.jpg"></span> <font>Tính chuyên nghiệp</font>
            <p>Cải tiến theo đặc trưng nam giới Châu Á </p>
         </div>
         <div class="box">
            <span><img src="images/m5_pic14.jpg"></span> <font>Độ tin cậy  </font>
            <p>Bác sỹ nổi tiếng, phòng thủ thuật vô khuẩn </p>
         </div>
         <div class="box">
            <span><img src="images/m5_pic15.jpg"></span> <font>Tính triệt để  </font>
            <p>BĐiều trị chính xác, điều trị tận gốc bệnh  </p>
         </div>
         <div class="box">
            <span><img src="images/m5_pic16.jpg"></span> <font>Tính an toàn</font>
            <p>Thủ thuật xâm lấn tối thiểu, vết thương nhỏ  </p>
         </div>
         <div class="line"><span><a href="<?= $link_tuvan;?>">Bạn gái cho rằng bạn không được<br>làm sao để thỏa mãn cô ấy? </a></span></div>
      </div>
      <div id="t5_box3">
         <h3>4 điều bất ngờ lớn, bạn đời chủ động đòi hỏi</h3>
         <div class="box">
            <span><img src="images/m5_pic17.jpg"></span>
            <p><b>Kéo dài khoái cảm</b> <br>
               Kéo dài thời gian 5-20 phút
            </p>
         </div>
         <div class="box2">
            <p><b>Kéo dài khoái cảm</b><br>
               Số lần dương vật chuyển động tăng lên
            </p>
            <span><img src="images/m5_pic18.jpg"></span>
         </div>
         <div class="box">
            <span><img src="images/m5_pic19.jpg"></span>
            <p><b>nâng cao tinh lực </b><br>
               Số lần yêu tăng lên  
            </p>
         </div>
         <div class="box2">
            <p> <b>Khống chế xuất tinh</b><br>
               Muốn xuất lúc nào được lúc đó, làm chủ cuộc yêu 
            </p>
            <span><img src="images/m5_pic20.jpg"></span>
         </div>
		 <!--
         <span><a href="#"><img src="./images/m5_pic21.jpg"></a></span> 
		 -->
      </div>
      <div id="title6">
         <div class="tt">
            <span>
               <img src="images/title6.jpg" border="0" usemap="#Map2">
				<a href="<?= $link_tuvan;?>">
					<map name="Map7" id="Map7" style="width: 168px;  height: 29px;float: right;position:absolute;right: 0;   top: 41px;">
					</map>
					</a>
            </span>
            <h3>Đội ngũ y tá bác sỹ lớn mạnh </h3>

         </div>
         <div class="content" style="padding-left: 71px;">
           
            <div class="ccon">
               <div class="ccon_in">
			   <img src="images/m6_pic3.jpg" >
               </div>

            </div>

         </div>
		             <p style="    padding: 10px 117px;
    text-align: center;">phòng khám đa khoa Giải Phóng Hà Nội với đội ngũ y bác sỹ chuyên nghiệp, các bác sỹ nổi tiếng trực tiếp khám chữa bệnh, kinh nghiệm lâm sàng phong phú, kỹ thuật chuyên nghiệp, vận dụng linh hoạt khái niệm y tế tiên tiến nhất, khoa học nhất trong thực tiễn lâm sàng.</p>
      </div>
      <div id="title7">
         <div class="tt">
            <span>
               <img src="images/title7.jpg" border="0" usemap="#Map">
				<a href="<?= $link_tuvan;?>">
					<map name="Map7" id="Map7" style="width: 168px;  height: 29px;float: right;position:absolute;right: 0;   top: 41px;">
					</map>
					</a>
            </span>
            <h3>Lắng nghe cuộc sống hạnh phúc của cô ấy/ anh ấy</h3>
         </div>
         <div class="box">
            <span><img src="images/m7_pic.jpg"></span> <span class="t1">Bệnh nhân: Trần văn Mạnh/ 25 tuổi/ Lập trình viên<br><br>
            Tiền sử bệnh: kết hôn 1 năm/ không có tiền sử bệnh đặc trưng</span> <font>Xuất tinh sớm đã chữa khỏi, tạm biệt anh Trung 2 phút</font>
            <p>Do bất lực khiến gia đình đổ vỡ, vừa mới kết hôn 1 năm, mỗi lần quan hệ kéo dài 2-6 phút, vợ thường xuyên oán trách, có lần bột miếng nói ra muốn li hôn...<b>
			<a class="chi-tiet" href="<?= $link_tuvan;?>">[Chi tiết]</a> </b></p>
         </div>
         <div class="box2">
            <span><img src="images/m7_pic2.jpg"></span> <span class="t1">Bệnh nhân: Lưu Thị Hoa/ 35 tuổi/ bà chủ doanh nghiệp tư nhân <br/><br>
            Tiền sử bệnh: kết hôn 1 năm/ tiền sử bệnh không đặc trưng</span> <font>Tôi có thể kéo dài được 20 phút</font>
            <p>Tôi có sự nghiệp, do còn trẻ tuổi nên ăn uống vui chơi không điều độ, tôi bị bệnh xuất tinh sớm, sau một tháng điều trị thông qua thủ thuật kéo dài thời gian giảm nhạy cảm bằng máy hiển vi xuất tinh sớm JCI...<b>
			<a class="chi-tiet" href="<?= $link_tuvan;?>">[Chi tiết]</a> </b></p>
         </div>
         <div class="box" style="border:none;">
            <span><img src="images/m7_pic3.jpg"></span> <span class="t1">Người chia sẻ <br/><br/>
            Bà Thái/ 30 tuổi</span> <font>Tôi mỗi đêm đều có cao trào</font>
            <p>Chồng tôi 2 năm trước mắc bệnh xuất tinh sớm, mỗi lần không được 1 phút là đã xuất tinh, sau khi điều trị ở phòng khám Giải Phóng Hà Nội, hiện tại mỗi lần....<b>
			<a class="chi-tiet" href="<?= $link_tuvan;?>">[Chi tiết]</a> </b></p>
         </div>
         <div class="box2" style="border:none;">
            <span><img src="images/m7_pic5.jpg"></span> <span class="t1">Bệnh nhân: Ngô Văn Quý/ 28 tuổi/ giám đốc kinh doanh <br><br/>
            Tiền sử bệnh: kết hôn 3 năm/ vô sinh </span> <font>Điều trị khỏi xuất tinh sớm, tôi đã được làm bố </font>
            <p>Vừa mới kết hôn, tôi đã biết mình “ không ổn”, kết hôn 3 năm vợ tôi mãi không mang thai, vợ tôi đi kiểm tra không có vấn đề gì, sau đó đến phòng khám đa khoa Giải Phóng Hà Nôi tôi mới biết....<b>
			<a class="chi-tiet" href="<?= $link_tuvan;?>">[Chi tiết]</a> </b></p>
         </div>
      </div>
      <div style="clear:both;"></div>
      <div id="footer_line"></div>
   <?= menu_footer();?>
	<script type="text/javascript" src="images/jquery-1.8.0.min.js"></script>
      <script type="text/javascript" src="images/jquery.easing.1.3.js"></script>
      <script type="text/javascript" src="images/fun.js"></script>
      <script type="text/javascript" src="./images/jquery.scrollLoading-min.js1"></script>
   <?= Addleft();?>
        <script>
            $(document).ready(function(){
                $("#swt_lt_right_box li").hover(function(){
                    $(this).addClass("hover");
                },function(){
                    $(this).removeClass("hover");
                });
            })
        </script>
<style>
.left_s {
	display:block !important;
}
</style>
      <script type="text/javascript">
         $(function(){
         	nav1Tab();
         });
         ltMoveDiv2({
         	"top_box":"#title6 .content",
         	"move_box":"#title6 .content .ccon .ccon_in ul",
         	"move_box_li":"#title6 .content .ccon .ccon_in ul li",
         	"width":780,
         	"height":338,
         	"interval_time":10000,
         	"speed":500,
         	"page":1,
         	"move_irection":1,
         	"move_tab":"#title6 .content .ccon .ccon_tab",
         	"prev_btn":"#title6 .content .cleft",
         	"next_btn":"#title6 .content .cright"
         });
      </script>
   </body>
</html>
<?= $line_chat;?>