<?php
    require_once('../../../define.php');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>chuyen muc suc khoe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="bootstrap-3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://phongkhambenhxahoi.vn/mobile/cdsuckhoe/chuyen-muc-suc-khoe/css/style.css">
    <script src="bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <?= ico_shortcut;?>
</head>
<body>
<div class="container">
    <div class="main_item top">
        <div class="top_left">
            <a href="<?= domain;?>">
                <img src="http://phongkhambenhxahoi.vn/public/mobile/imgs/logo_top.png" alt="logo">
            </a>
        </div>
        <div class="top_right">
            <a href="<?= rewrite_number_phone(phone1);?>">
                <img src="images/top_dt.png" alt="dien thoai">
            </a>
        </div>
    </div>
    <div class="main_item menu">
        <ul>
            <li><a href="<?= domain;?>">Trang chủ</a> </li>
            <li><a href="<?= link_gioithieu;?>">Giới thiệu</a> </li>
            <li><a href="<?= link_kythuat;?>">Kĩ thuật</a> </li>
            <li><a href="<?= link_lotrinhphongkham;?>">Liên hệ</a> </li>
        </ul>
    </div>
    <div class="main_item banner">
        <img src="http://phongkhambenhxahoi.vn/mobile/cdsuckhoe/chuyen-muc-suc-khoe/images/banner.jpg" alt="banner">
    </div>
    <div class="main_item1">
        <div class="main_item">
            <div class="loidan">
                <div class="loidan_main">
                    <script src="http://phongkhamgiaiphong.com/cd/js/des.js"></script>
                </div>
            </div>
            <div class="main_item1_1">
                <div class="main_item_tit">
                    <div class="main_item_tit_content">
                        <h3>Những hạng mục ưu tiên miễn phí</h3>
                    </div>
                </div>
                <div class="item1_main">
                    <img src="images/item1_img.png" alt="dang ky">
                </div>
            </div>
            <div class="main_item1_2">
                <div class="main_item_tit">
                    <div class="main_item_tit_content">
                        <h3>giảm <b>30</b>% chi phí xét nghiệm</h3>
                        <p>Những hạng mục ưu đãi bạn chỉ cần đăng ký qua mạng</p>
                    </div>
                </div>
                <div class="main_item1_2_item">
                    <div class="main_item1_2_item_tit">
                        chúng tôi có thiết bị và môi trường thủ thuật
                        mà những nơi khác không thể so sánh
                    </div>
                    <div class="main_item1_2_item_img">
                        <img src="images/item1_img1.jpg" alt="phong kham">
                    </div>
                    <div class="main_item1_2_item_txt">
                        Phòng thủ thuật của phòng khám vô khuẩn tuyệt đối, các y bác sỹ chấp hành nghiêm khắc quy trình thao tác kỹ thuật vô khuẩn và chế độ vô khuẩn, hàng tuần đều tiến hành kiểm tra hiệu quả vô khuẩn của phòng thủ thuật, có hiệu quả trong việc phòng tránh nhiễm trùng trong thủ thuật, nâng cao độ an toàn của thủ thuật.
                    </div>
                    <div class="main_item1_2_item_btn">
                        <a href="<?= link_tuvan;?>">Click tư vấn về kỹ thuật</a>
                        <a href="<?= link_tuvan;?>">Click tư vấn bệnh tình</a>
                    </div>
                </div>
                <div class="main_item1_2_item">
                    <div class="main_item1_2_item_img">
                        <img src="images/item1_img2.jpg" alt="phong kham">
                    </div>
                    <div class="main_item1_2_item_txt">
                        Vì sự an toàn của bạn, hi vọng mọi người nâng cao cảnh giác, lựa chọn cẩn thận! Không nên tin tưởng các phòng khám tư nhân nhỏ lẻ và không chính quy, khi làm thủ thuật nhất định phải lựa chọn phòng khám chính quy, có chất lượng, quy mô lớn...
                    </div>
                    <div class="main_item1_2_item_btn">
                        <a href="<?= link_tuvan;?>">Click tư vấn về kỹ thuật</a>
                        <a href="<?= link_tuvan;?>">Click tư vấn bệnh tình</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="main_item2">
        <div class="main_item">
            <div class="main_item_tit">
                <div class="main_item_tit_content">
                    <h3>giảm <b>30</b>% chi phí thủ thuật</h3>
                    <p>Những hạng mục ưu đãi bạn chỉ cần đăng ký qua mạng</p>
                </div>
            </div>
            <div class="main_item2_main">
                <div class="main_item2_main_img">
                    <img src="images/item2_img1.jpg" alt="phong kham">
                </div>
                <div class="main_item2_main_c">
                    <div class="main_item2_main_c_tit">
                        THẤU HIỂU ĐƯỢC NHỮNG KHÓ KHĂN VÀ NHU CẦU KHÁM CHỮA BỆNH CỦA BỆNH NHÂN NGÀY CÀNG CAO.
                    </div>
                    <div class="main_item2_main_c_txt">
                        <p>
                            Phòng khám ngay từ khi mới đi vào hoạt động đã luôn chú trọng đến việc đầu tư các trang thiết bị máy móc tiên tiến hiện đại như: máy móc siêu âm, máy xét nghiệm, dụng cụ y tế... Phần lớn được nhập khẩu từ các nước có nền y khoa phát triển trên thế giới như: Mỹ, Ý, Nhật, Hàn Quốc...Cùng với kinh nghiệm lâu năm của các bác sĩ tại phòng khám đa khoa Giải Phóng đã không ngừng học hỏi, áp dụng thành công những thành tựu khoa học trong ngành y để đưa vào thực tiễn, giúp bệnh nhân tiết kiệm được thời gian cũng như chi phí điều trị, ....
                        </p>
                        <a href="<?= link_tuvan;?>">Click tư vấn thủ thuật</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="main_item">
            <div class="main_item_tit">
                <div class="main_item_tit_content">
                    <h3>giảm <b>30</b>% chi phí điều trị</h3>
                    <p>Những hạng mục ưu đãi bạn chỉ cần đăng ký qua mạng</p>
                </div>
            </div>
            <div class="main_item2_main">
                <div class="main_item2_main_img">
                    <img src="images/item2_img2.jpg" alt="phong kham">
                </div>
                <div class="main_item2_main_c">
                    <div class="main_item2_main_c_tit">
                        Nhập khẩu các thiết bị chẩn trị tiên tiến, loại bỏ các vấn đề khó khăn trong điều trị bệnh
                    </div>
                    <div class="main_item2_main_c_txt">
                        <p>
                            Tạo dựng thương hiệu phòng khám đa khoa hàng đầu trong khu vực Hà Nội, phòng khám đa khoa 168 Hà Nội nhập khẩu các thiết bị tiên tiến nhất như: máy hiển vi phóng đại đa chức năng, máy trị liệu hồng ngoại, máy trị liệu (CRS) sóng ngắn, máy trị liệu vi ba, máy chẩn đoán siêu âm màu, hệ thống trị liệu đẳng li tử nhiệt độ thấp của Mỹ, máy phân tích chất lượng tinh trùng, máy soi trực tràng hậu môn của Đức... Đưa ra các dữ liệu khoa học có lợi nhất, có lợi trong việc điều trị sức khỏe cho người bệnh.
                        </p>
                        <a href="<?= link_tuvan;?>">Click tư vấn điều trị</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="main_item3">
        <div class="main_item">
            <div class="main_item_tit">
                <div class="main_item_tit_content">
                    <h3>Phòng khám chuyên nghiệp</h3>
                    <p>Chúng tôi luôn cố gắng nỗ lực để có thể phục vụ bệnh nhân tốt nhất</p>
                </div>
            </div>
            <div class="main_item3_main">
                <div class="main_item3_main_img">
                    <img src="http://phongkhambenhxahoi.vn/mobile/cdsuckhoe/chuyen-muc-suc-khoe/images/pk_1.jpg" alt="phong kham">
                </div>
                <div class="main_item3_main_txt">
                    <h3>PHÒNG KHÁM ĐA KHOA CHUYÊN NGHIỆP</h3>
                    <p>
                        Chuyên điều trị các bệnh, bảo vệ sức khỏe bản thân
                    </p>
                </div>
            </div>
            <div class="main_item3_main">
                <div class="main_item3_main_img">
                    <img src="images/pk_2.jpg" alt="phong kham">
                </div>
                <div class="main_item3_main_txt">
                    <h3>ĐỘI NGŨ Y TẾ LỚN MẠNH</h3>
                    <p>
                        Tập hợp các bác sỹ nổi tiếng trong và ngoài nước, đội ngũ y bác sỹ hùng hậu
                    </p>
                </div>
            </div>
            <div class="main_item3_main">
                <div class="main_item3_main_img">
                    <img src="images/pk_3.jpg" alt="phong kham">
                </div>
                <div class="main_item3_main_txt">
                    <h3>KỸ THUẬT CHẨN TRỊ TIÊN TIẾN TOÀN DIỆN</h3>
                    <p>
                        Nhập khẩu các loại kỹ thuật chẩn trị, nâng cao hiệu quả điều trị bệnh
                    </p>
                </div>
            </div>
            <div class="main_item3_main">
                <div class="main_item3_main_img">
                    <img src="images/pk_4.jpg" alt="phong kham">
                </div>
                <div class="main_item3_main_txt">
                    <h3>ĐẾN THĂM KHÁM LÀ ĐƯỢC HƯỞNG ƯU ĐÃI</h3>
                    <p>
                        Người bệnh đến khám sẽ được hưởng ưu đãi, tiết kiệm chi phí
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="main_item4">
        <div class="main_item4_bg_top">
            <img src="images/item4_bg2.png" alt="bg">
        </div>
        <div class="main_item">
            <div class="main_item_tit">
                <div class="main_item_tit_content">
                    <h3>thăm khám bệnh lưu ý lựa chọn phòng khám chuyên nghiệp</h3>
                </div>
            </div>
            <div class="main_item4_tit">
                phòng khám đa khoa Giải Phóng Hà Nội với trang thiết bị hiện đại, kỹ thuật tiên tiến, điều trị hiệu quả cao, chi phí thấp
            </div>
            <p>Không phải phòng khám nào cũng có thể áp dụng kỹ thuật xâm lấn tối thiểu</p>
            <p>Chỉ có những phòng khám chuyên nghiệp, toàn diện, cơ cấu trang thiết bị và năng lực về y tế chính quy toàn diện mới có đủ tư cách áp dụng.</p>
            <div class="main_item4_img">
                <img src="http://phongkhambenhxahoi.vn/mobile/cdsuckhoe/chuyen-muc-suc-khoe/images/item4_img1.png" alt="phong kham">
                <a href="<?= link_tuvan;?>">Click tư vấn đặt hẹn</a>
            </div>
            <div class="main_item4_main">
                <div class="main_item4_main_tit">
                    <h4><b>1</b>Năng lực được công nhận</h4>
                </div>
                <div class="main_item4_main_txt">
                    phòng khám đa khoa Giải Phóng Hà nội là phòng khám nghiên cứu và vận dụng trang thiết bị y tế lâm sàng hiện đại tại khu vực, đã được công nhận về tư cách và năng lực
                </div>
            </div>
            <div class="main_item4_main">
                <div class="main_item4_main_tit">
                    <h4><b>2</b>Bảo đảm an toàn</h4>
                </div>
                <div class="main_item4_main_txt">
                    <p>- Môi trường được đảm bảo - phòng thủ thuật sạch sẽ vô khuẩn</p>
                    <p>- Bác sỹ được đảm bảo - với đội ngũ y bác sỹ có trên 20 năm kinh nghiệm lâm sàng</p>
                    <p>- Kinh nghiệm được đảm bảo - với hàng ngàn ca thủ thuật không sự cố</p>
                </div>
            </div>
            <div class="main_item4_main">
                <div class="main_item4_main_tit">
                    <h4><b>3</b>Yêu cầu về trình độ</h4>
                </div>
                <div class="main_item4_main_txt">
                    Nhằm đảm bảo thực hiện thủ thuật an toàn và hiệu quả cao, bác sỹ thực hiện thủ thuật cần có:
                    <div style="padding-left: 15px">
                        <p>1. Bác sỹ có Trình độ thực hiện thủ thuật</p>
                        <p>2. Bác sỹ thực hiện hàng ngàn ca thủ thuật không để xuất hiện sự cố</p>
                        <p>3. Làm việc trong ngành y từ 20 năm trở lên</p>
                    </div>
                </div>
            </div>
            <div class="main_item4_main">
                <div class="main_item4_main_tit">
                    <h4><b>4</b>Trang thiết bị hiện đại</h4>
                </div>
                <div class="main_item4_main_txt">
                    phòng khám đa khoa Giải Phóng Hà Nội, nhập khẩu trang thiết bị hiện đại, đảm bảo tính an toàn và hiệu quả điều trị
                </div>
            </div>
        </div>
    </div>
    <div class="bando">
        <img src="http://phongkhambenhxahoi.vn/mobile/cdsuckhoe/chuyen-muc-suc-khoe/images/bando.png" alt="ban do">
    </div>
    <div class="footer">
        <ul>
            <li>
                <a href="<?= rewrite_number_phone(phone1);?>">
                    <img src="images/f_ico_dt.png" alt="dien thoai">
                    <span>tư vấn<br>điện thoại</span>
                </a>
            </li>
            <li>
                <a href="<?= link_tuvan;?>">
                    <img src="images/f_ico_tv.png" alt="dien thoai">
                    <span>tư vấn<br>trực tuyến</span>
                </a>
            </li>
            <li>
                <a href="#" class="backtotop">
                    <img src="images/f_ico_quaylai.png" alt="dien thoai">
                    <span>quay lại<br>đầu trang</span>
                </a>
            </li>
        </ul>
    </div>
</div>
<script>
    $(document).ready(function(){
        $(".backtotop").click(function () {
            $("body,html").animate({scrollTop: 0}, "slow");
        });
    })
</script>
<?= m_popup();?>
</body>
</html>