<?php
require_once("../../../define.php");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>kéo dài dương vật</title>
    <link href="css/main.css" rel="stylesheet" type="text/css" />
    <link href="css/style/main.css" rel="stylesheet" type="text/css" />
    <base target="_blank">
</head>
<body style="font-family: arial">
<div id="top_ts">
</div>
<div id="nav">
    <div class="nav_in">
        <div class="logo"><a href="/" target="_blank"><img src="image/logo.png" /></a></div>
        <div class="nav_list fwryh">
            <div class="nav_list_bg"><span></span></div>
            <ul class="bg">
                <li class="f"></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
            <?/*= menu_top();*/?>
            <ul class="txt">
                <li class="f">
                    <a href="<?= domain;?>"><div class="box"><p>TRANG CHỦ<br>PHÒNG KHÁM</p></div></a>
                </li>
                <li>
                    <a href="<?= link_gioithieu;?>"><div class="box"><p>GIỚI THIỆU<br>PHÒNG KHÁM</p></div></a>
                </li>
                <li>
                    <a href="<?= link_tuvan;?>"><div class="box"><p>BÁC SỸ<br>CHÍNH QUY</p></div></a>
                </li>
                <li>
                    <a href="<?= link_kythuat;?>"><div class="box"><p>KỸ THUẬT<br>HIỆN ĐẠI</p></div></a>
                </li>
                <li>
                    <a href="<?= link_thietbi;?>"><div class="box"><p>THIẾT BỊ<br>TIÊN TIẾN</p></div></a>
                </li>
                <li class="last">
                    <a href="<?= link_diachi;?>"><div class="box"><p>ĐỊA CHỈ<br>PHÒNG KHÁM</p></div></a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div id="banner">
    <img src="image/banner.jpg" alt="">
</div>
<div id="title">
    <h3><img src="image/title.jpg" /></h3>
    <p>Bạn biết tại sao phụ nữ nhiều khi giả vờ lên đỉnh không? Hãy thử hỏi bản thân có tạo cho cô ấy khoái cảm cô ấy cần không, dương vật ngắn nhỏ, nhu cầu yếu, bạn bảo cô ấy trải nghiệm cao trào thực sự như thế nào? Nam giới, bạn có ý thức được điều này?</p>
    <div class="mian">
        <div class="l">
            <div style="padding-right: 22px;">
                Cậu nhỏ kém xa so với bạn trai cũ, nhỏ như vậy cộng thêm không cương cứng được, nếu không phải vì thích anh ấy thì sớm đã chia tay rồi, có chút cảm giác mất mặt!
            </div>
        </div>
        <div class="r">
            <div style="padding-right: 33px;">
                Mỗi lần nhắc đến nam giới, tôi đều không dám nói đến chính mình, sợ các chị em cười sau lưng, vì bạn trai của các cô ấy đều rất tuyệt vời!
            </div>
        </div>
        <div class="r2">
            <div style="padding-right: 7px;">
                Mỗi lần lên giường đều không chạm đến điểm cao nhất của tôi, ở bên cạnh anh ấy chưa từng có cảm giác sung sướng, đây có phải là đàn ông không?
            </div>
        </div>
    </div>
</div>
<div id="title2">
    <div class="mian2">
        <h3><img src="image/title2.jpg" /></h3>
        <p>Từ khi làm thủ thuật kéo dài dương vật, cô ấy suốt đêm cứ “gạ gẫm” tôi, xem anh ấy trước và sau khi làm thủ thuật kéo dài dương vật xâm lấn tối thiểu CNT Châu Âu ở phòng khám đa khoa Giải Phóng, cô ấy biết sự thay đổi lớn như thế nào!</p>
        <span><a href="<?= link_tuvan;?>">CLICK TƯ VẤN, HẸN KHÁM</a></span></div>
    <div class="mian3">
        <div class="f1">Khi cho vào có cảm giác khoái cảm mà trước nay cô ấy chưa từng có, khiến cô ấy cả đêm sung sướng!</div>
        <div class="f2">Không chỉ phong độ, cô ấy ngày càng hài lòng với khả năng trên giường của tôi!</div>
        <div class="f1">Vô cùng tự tin, bạn của cô ấy vô cùng ngưỡng mộ cô ấy có người bạn trai lơi hại như vậy!</div>
        <div class="f2">Mua bao cao su đều phải to hơn, mỗi lần đều mua hai hộp, cô ấy nói thật hãnh diện vì tôi!</div>
    </div>
</div>
<div id="title3">
    <h3><img src="image/title3.jpg" /></h3>
    <p>Kỹ thuật kéo dài dương vật được phòng khám Giải Phóng nhập khẩu từ nước ngoài năm 2013, nhưng do chỉ có hiệu quả kéo dài, không nâng cao được chất lượng quan hệ tình dục. Do đó năm 2014 phòng khám đa khoa Giải Phóng Hà Nội mời các bác sỹ nổi tiếng của Mỹ nghiên cứu và cải tiến đồng bộ, hiện tại kỹ thuật đa chức năng vừa có thể kéo dài, làm to, nâng cao chất lượng quan hệ tình dục, kéo dài thời gian quan hệ...</p>
    <div class="mian">
        <div class="m1">
            <div class="l"> <span><img src="image/mian3_pic.jpg" /></span>
                <!--<span><img src="image/mian3_pic2.jpg" /></span>-->
               <!-- <h3>Lễ ký kết nhập khẩu<br>thiết bị kỹ thuật </h3>
                <h3 style="width:158px;">Giấy chứng nhận kỹ thuật</h3>-->
            </div>
            <div class="r">
                <h2>Quá trình nhập khẩu kỹ thuật</h2>
                <font>quá trình nhập khẩu kỹ thuật</font>
                <span>ĐẶC ĐIỂM KỸ THUẬT</span>
                <p>Kỹ thuật này không can thiệp vào tinh hoàn, không gây thương tổn chức năng suất tinh và niệu đạo, không ảnh hưởng đến chức năng sinh sản và chức năng tình dục, có thể kéo dài dương vật 3-5cm, không gây đau đớn, thời gian ngắn, phục hồi nhanh, mỹ quan tự nhiên, một lần là thành công...</p>
            </div>
        </div>
        <div class="m2">
            <div class="l">
                <h2>Nghiên cứu cải tiến kỹ thuật</h2>
                <p><b>Địa điểm nghiên cứu  ：</b><br />
                    Phòng thực nghiệm phòng khám đa khoa Giải Phóng Hà Nội <br />
                    <b>đội ngũ nghiên cứu ：</b><br />
                    Đội ngũ nghiên cứu trung tâm y học quốc tế liên hiệp phòng khám đa khoa Giải Phóng Hà Nội</p>
				<span>Trong vòng 6 tháng nghiên cứu được thực hiện nhiều lần, không ngừng áp dụng thực nghiệm nhiều lần các thiết bị</span> </div>
            <div class="r">
                <span><img src="image/mian3_pic3.jpg" /></span>
                <span><img src="image/mian3_pic4.jpg" /></span>
                <h3>Thảo luận nghiên cứu y học</h3>
                <h3>Đoàn nghiên cứu y học đang trong lúc nghiên cứu</h3>
            </div>
        </div>
        <div class="m3">
            <div class="l"> <span><img src="image/mian3_pic5.jpg" /></span> <span><img src="image/mian3_pic6.jpg" /></span>
                <h3>Đầu tư kỹ thuật thực nghiệm </h3>
                <h3>Mở rộng cơ cấu y tế</h3>
            </div>
            <div class="r">
                <h2>Đầu tư thử nghiệm kỹ thuật </h2>
                <font>Trải qua thực tiễn nhiều lần để hình thành được kỹ thuật kéo dài dương vật xâm lấn tối thiểu CNT Châu Âu</font>
                <p><b style="color:#177fc8">Nhận được sự quan tâm chú ý của các cơ sở ý tế：</b><br />
                    Từ sau khi kỹ thuật này được đưa vào sử dụng, đã nhận được sự quan tâm chú ý của các cơ sở y tế, có nhiều cơ sở đã đến phòng khám đa khoa Giải Phóng để học tập, cùng nghiên cứu thảo luận với đội ngũ bác sỹ. </p>
            </div>
        </div>
    </div>
</div>
<div id="title4">
    <div class="mian">
        <h3><img src="image/title4.jpg" /></h3>
        <p>Nguyên lý kỹ thuật: tận dụng kỹ thuật xâm lấn tối thiểu với độ chính xác cao, cắt chỉ dương vật, thăm dò dây hãm đến xương cụt, khiến cho thể hang vùi dưới xương cụt hình thành bộ phận tự do tách rời, từ đó tăng độ dài của dương vật.</p>
        <div class="left"> <span><img src="image/mian4_pic1.jpg" /></span>
            <h2>trước khi thủ thuật</h2>
            <font>Trước khi thủ thuật, chúng tôi sẽ đáp ứng đầy đủ yêu cầu của người bệnh. Kiểm tra chính xác dương vật của người bệnh, căn cứ vào tình trạng thực tế của bệnh nhận và yêu cầu của bệnh nhân để đưa ra phương án thủ thuật!
                <p>【Toàn bộ quá trình được bảo mật riêng tư】</p>
            </font></div>
        <div class="center">
            <p>Sau khi gây mê, trước khi thủ thuật cắt lớp da và màng, tách rời, khi đó có thể nhìn thấy 2-3 dây tĩnh mạch dưới của dương vật, sau khi tĩnh mạch được cắt, sẽ không gây khó khăn cho sự hồi lưu máu của dương vật.</p>
            <span><img src="image/mian4_pic2.jpg" /></span>
            <h2>trong thủ thuật</h2>
            <font>Phân tách theo hướng của xương mu, lộ ra dây chằng dương vật, tách màng và tổ chức mô liên kết lỏng của hai bên dây chằng, thắt chặt dây chằng gần xương mu hoàn toàn cắt đứt. Khi cắt đứt dây chằng để tránh thương tổn tĩnh mạch sâu trong dương vật và tránh dẫn tới khó khăn trong hồi lưu máu tĩnh mạch, gây ra hoại tử dương vật. </font> </div>
        <div class="right"> <span><img src="image/mian4_pic3.jpg" /></span>
            <h2>sau thủ thuật</h2>
            <font>Cắt loại bỏ nang lông phía gốc dương vật. Khi khâu vết thương tiến hành khâu chữ “Y” cách xa dương vật
                <p><a href="<?= link_tuvan;?>">Đọc không hiểu? Click tìm hiểu chi tiết!</a></p>
            </font></div>
    </div>
</div>
<div id="title5">
    <h3><img src="image/title5.jpg" /></h3>
    <div class="l"> <b>Anh Minh người bị dương vật ngắn nhỏ cho biết:</b>
        <p style="height: 175px;">Cuối cùng tôi cũng giống như những người đàn ông thực sự, có thể thể hiện bản lĩnh đàn ông trước mặt bạn gái của mình, thủ thuật mỹ quan không phát hiện ra vết khâu, không chỉ kéo dài dương vật, cô ấy còn vui sướng vì bản lĩnh trên giường của tôi...<a href="<?= link_tuvan;?>" target="_blank"> 【chi tiết】</a></p>
        <span><a href="<?= link_tuvan;?>">Tôi còn thắc mắc! Click tư vấn </a></span></div>
    <div class="c"> <b>Anh Đoan trước kia từng không hòa hợp trong quan hệ tình dục:</b>
        <p style="padding-right:8px;">Anh Thắng từ khi còn nhỏ do dương vật nhỏ nên thường bị trêu chọc, cũng do quan hệ tình dục không hòa hợp nên gia đình đứng trước nguy cơ đổ vỡ. Từ sau khi làm thủ thuật kéo dài dương vật ở phòng khám đa khoa Giải Phóng Hà Nội, anh ấy đã tự tin vô cùng khiến chất lượng quan hệ tình dục được nâng lên, gia đình từ đó mà hạnh phúc...<a href="<?= link_tuvan;?>"> 【chi tiết】</a></p>
        <span><a href="<?= link_tuvan;?>">Tôi còn thắc mắc! Click tư vấn</a></span></div>
    <div class="r"> <b>Nam giới độc thân - cuộc sống và công việc không điều độ:</b>
        <p style="padding-right:10px; height: 175px;">Kéo dài dương vật là mơ ước của anh Mạnh, và cuối cùng mơ ước đó cũng thành hiện thực. Điều này khiến cho anh nhận được sự quan tâm chú ý của các chị em, tìm được bạn gái...<a href="<?= link_tuvan;?>"> 【chi tiết】</a></p>
        <span><a href="<?= link_tuvan;?>">Tôi có thắc mắc! Click tư vấn</a></span></div>
    <div class="wx"><a href="<?= link_tuvan;?>"><img src="image/mian5_bg4.jpg" /></a></div>
</div>
<div id="title6">
    <h3><img src="image/title6.jpg" /></h3>
    <p>Để cho bạn sự trải nghiệm hoàn mỹ hơn, chúng tôi sẽ tiếp tục cố gắng, cho bạn và cô ấy sự yêu thương mãnh liệt hơn! Từ tháng 6 đến tháng 12 năm 2015, phòng khám đa khoa Giải Phóng Hà Nội nâng cấp thủ thuật kéo dài dương vật xâm lấn tối thiểu Hàn Quốc, đã hoàn thành thủ thuật kéo dài dương vật cho hơn 150 bệnh nhân, thu được kết quả tốt, báo cáo như sau: </p>
    <table class="t6_tab">
        <tr class="tr1">
            <td width="110" rowspan="2" class="td1">Tham số</td>
            <td colspan="2" class="td2">So sánh trạng thái khi bình thường</td>
            <td colspan="2" class="td3">So sánh trạng thái khi cương cứng</td>
            <td rowspan="2" class="td4">Độ kéo dài trung bình</td>
            <td rowspan="2" class="td4">Độ hài lòng trong quan hệ</td>
            <td rowspan="2" class="td5">Kết luận</td>
        </tr>
        <tr>
            <td>Trước thủ thuật</td>
            <td style="color:#FF0000;">Sau thủ thuật</td>
            <td>Trước thủ thuật</td>
            <td style="color:#FF0000;">Sau thủ thuật</td>
        </tr>
        <tr>
            <td height="53">Ngắn nhỏ bẩm sinh</td>
            <td width="110">4.0-5.5cm </td>
            <td width="110" style="color:#FF0000;">7.5-11.0cm </td>
            <td width="110">6.5-9.0cm </td>
            <td width="110" style="color:#FF0000;">10.0-14.5cm </td>
            <td width="110" rowspan="3" style="color:#177fc8;">3.5-5.5cm</td>
            <td width="110" rowspan="3" style="color:#177fc8;">98.29%</td>
            <td rowspan="3" div class="td6" valign="top" style="text-align: justify">
                Điện thoại phản hồi từ tháng 6 đến tháng 12 đều khá hài lòng với hiệu quả của thủ thuật, cảm thấy tự tin hơn, dương vật vừa dài vừa to, chất lượng quan hệ tình dục cũng được cải thiện. Đặc biệt có 2 trường hợp bị ung thư dương vật giai đoạn đầu sau khi làm thủ thuật đã không còn bị ung thư, có thể tiểu tiện đứng và có thể quan hệ tình dục.<br />
                <a href="<?= link_tuvan;?>" style="width: 100%;word-spacing: -1px;">Tư vấn hẹn khám, tôi muốn kéo dài luôn!</a>
            </td>
        </tr>
        <tr>
            <td height="53">Quan hệ không hào hợp</td>
            <td>5.5-10.0cm </td>
            <td style="color:#FF0000;">8.5-16.5cm </td>
            <td>10.0-13cm </td>
            <td style="color:#FF0000;">14.5-19.5cm </td>
        </tr>
        <tr>
            <td height="53">Ung thư dương vật thời kì đầu</td>
            <td>4.0-6.0cm</td>
            <td style="color:#FF0000;">8.0-12.1cm</td>
            <td>5.0-11.0cm</td>
            <td style="color:#FF0000;">9.0-14.5cm</td>
        </tr>
    </table>
</div>
<div id="title7">
    <h3><img src="image/title7.jpg" /></h3>
    <p>Mỗi chi tiết đều trải qua sự cải tiến không ngừng, để cho bạn sự đảm bảo an toàn hiệu quả cao hơn và cho bạn sự hoàn mỹ hơn.</p>
    <div class="s1">
        <h2>kiểm tra thủ thuật nghiêm ngặt</h2>
        <p>Trước thủ thuật chỉ cần làm tốt việc kiểm tra biến chứng bệnh, đảm bảo sức khỏe mới có thể tiến hành thủ thuật</p>
        <span><img src="image/m7_1.jpg" /></span>
        <p style="margin-bottom: 22px;">Kho thiết bị kiện toàn của phòng khám đa khoa Giải Phóng Hà Nội, mang lại nhiều ưu thế trong việc kiểm tra thủ thuật, có thể nhanh chóng kiểm tra ra tất cả các loại bệnh.</p>
        <b><a href="<?= link_tuvan;?>">tìm hiểu nhiều hơn</a> </b> </div>
    <div class="s1">
        <h2 style="background:url(image/s_b.jpg) no-repeat center top;">Bác sỹ thủ thuật</h2>
        <p>Thủ thuật kéo dài dương vật có yêu cầu nghiêm ngặt về phương diện vệ sinh sạch sẽ, đảm bảo toàn bộ quá trình thủ thuật không bị viêm nhiễm.</p>
        <span><img src="image/m7_2.jpg" /></span>
        <p>Thủ thuật kéo dài dương vật của phòng khám đa khoa Giải Phóng là thủ thuật được thực hiện trong phòng vô khuẩn, tất cả các thiết bị đều được diệt khuẩn ở nhiệt độ cao, luôn duy trì sạch sẽ vùng dương vật.</p>
        <b><a href="<?= link_tuvan;?>">tìm hiểu nhiều hơn</a> </b>
    </div>
    <div class="s1">
        <h2 style="background:url(image/s_c.jpg) no-repeat center top;">Toàn bộ quá trình vô khuẩn</h2>
        <p>Chỉ có bác sỹ thủ thuật kéo dài dương vật tay nghề cao mới có thể đảm bảo thủ thuật an toàn hoàn mỹ.</p>
        <span><img src="image/m7_3.jpg" /></span>
        <p style="margin-bottom: 43px;">Bác sỹ thủ thuật chính của phòng khám đa khao1 68 đều có tay nghề cao và có kinh nghiệm lâu năm trong ngoại khoa chỉnh hình khoa ngoại tiết niệu.</p>
        <b><a href="<?= link_tuvan;?>">tìm hiểu nhiều hơn</a> </b> </div>
    <div class="s1" style="margin-right:0;">
        <h2 style="background:url(image/s_d.jpg) no-repeat center top;">Ký kết trách nhiệm kỹ thuật</h2>
        <p>Quyền lợi của bệnh nhân chúng tôi luôn ghi nhớ, ký kết trách nhiệm kỹ thuật là đảm bảo trách nhiệm của chúng tôi với bạn.</p>
            <span><img src="image/m7_4.jpg" /></span>
        <p >Chuyên nghiệp hơn, chúng tôi luôn nỗ lực, để đảm bảo quyền lợi cho người bệnh, phòng khám đa khoa Giải Phóng đưa ra quy định ký kết trách nhiệm kỹ thuật đồng bộ.</p>
        <b><a href="<?= link_tuvan;?>">tìm hiểu nhiều hơn</a></b>
    </div>
</div>
<script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
<?= menu_footer();?>
<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="js/ltMove.js"></script>
<script type="text/javascript" src="js/fun.js"></script>
<script type="text/javascript">
    $(function(){
        nav1Tab();
    });
</script>
</body>
</html>
