<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>điều trị tiền liệt tuyến</title>
    <link href="css/main.css" rel="stylesheet" type="text/css" />
    <link href="css/style_main.css" rel="stylesheet" type="text/css" />
    <link href="css/custorm.css" rel="stylesheet" type="text/css" />
    <base target="_blank" />
</head>
<?php
require_once('../../../define.php');
$domain=domain;
$link_tuvan=link_tuvan;
?>
<body>
<?= Addtop();?>
<div id="top_ts">
    <ul>
        <li class="left" style="text-transform: uppercase;">phòng khám nam khoa Nhân Ái QUAN TÂM CHĂM SÓC SỨC KHỎE CỘNG ĐỒNG</li>
        <li class="right">TƯ VẤN MIỄN PHÍ : <?= phone1;?></li>
    </ul>
</div>
<?= menu_main();?>
<div id="banner">
    <div class="banner1">
        <div class="banner1_tv"><a href="<?= $link_tuvan;?>"> Click tư vấn</a></div>
    </div>
</div>
<div id="dy">
    <p>Chúng tôi đang nỗ lực cố gắng cho sự nghiệp và cho tình yêu, nhưng do thói quen và áp lực cuộc sống dẫn đến viêm tiền liệt tuyến. Bị viêm tiền liệt tuyến, chúng tôi phải làm thế nào? </p>
</div>
<div id="title" class="title">
    <div class="tt">
        <div class="tit_stt">01</div> Trường hợp dưới đây, bạn có muốn trải nghiệm?
    </div>
    <div class="left">
        <div class="t1">
            <div class="t1_l">
                <img src="images/mian_pic.jpg" class="af_load_pic" data-original="images/mian_pic.jpg" height="280" width="147" />
            </div>
            <div class="t1_r">
                <font>Trường hợp 1</font>
                <div class="clear"></div>
                <h3>Có cảm giác gọi là:<a class="color_red">Nhịn!nhịn!nhịn</a></h3>
                <p>Trong cuộc họp, đột nhiên muốn đi vệ sinh, nhưng khi đó không tiện đi! Các Sếp đều có ở đây, mọi người đang tập trung cho cuộc họp mà xin đi vệ sinh thì thật buồn cười, sau này còn nhìn mặt ai...</p>
                <p>Trong giờ giải lao... Nếu chạy ra ngoài mà khách hàng họ tức giận, hợp đồng lớn bị mất, vậy chỉ còn cách là “nhịn, nhịn...”</p>
            </div>
        </div>
        <div class="t1" style=" padding-top:40px; border-bottom:none; height:282px;">
            <div class="t1_l">
                <span style="margin-top:10px;"><img src="images/mian_pic3.jpg" class="af_load_pic" data-original="images/mian_pic3.jpg" height="271" width="147" /></span>
            </div>
            <div class="t1_r">
                <font>Trường hợp 3</font>
                <h3>Có cảm giác ấm ức gọi là: <a class="color_red">anh ấy quá kém </a></h3>
                <p>Sếp: Tâm đâu? Lại đi đâu rồi? <br />
                    Đồng nghiệp: hình như là đi vệ sinh rồi<br />
                    Sếp: cậu ấy về bảo cậu ấy qua phòng làm việc của tôi, cả ngày không nhìn thấy người đâu</p>
                <p>Anh Tâm thuật lại: tôi còn có cách nào nữa, tôi chăm chỉ làm việc nhưng bệnh tiểu rắt tiểu nhiều khiến tôi đi vệ sinh liên tục, tinh thần mệt mỏi, thường bị Sếp mắng, hiệu quả công việc ngày càng thấp, thật mệt mỏi...</p>
            </div>
        </div>
    </div>
    <div class="right">
        <div class="t1">
            <div class="t1_l">
                <span><img src="images/mian_pic2.jpg" class="af_load_pic" data-original="images/mian_pic2.jpg" height="249" width="176" /></span>
            </div>
            <div class="t1_r">
                <font>Trường hợp 2</font>
                <h3>Có sự khó chịu gọi là : <a class="color_red">"Tôi chịu đủ rồi"</a> </h3>
                <p>Trong lúc ngủ...trước kia có thể ngủ rất muộn, bây giờ trời chưa sáng đã phải dậy đi vệ sinh, mà còn rất khó chịu, ngủ không ngủ được! Còn làm cho vợ tỉnh giấc, suýt nữa là bị mắng rồi. </p>
                <p>Trong lúc hưng phấn...,lại đứt đoạn..., hứng thú không lên được,không phải tôi không yêu vợ! Tôi cũng khổ mà...</p>
            </div>
        </div>
        <div class="t1" style=" padding-top:40px; border-bottom:none; " >
            <div class="t1_l">
                <span style="margin-top:15px;"><img src="images/mian_pic4.jpg" class="af_load_pic" data-original="images/mian_pic4.jpg" height="254" width="190" /></span>
            </div>
            <div class="t1_r">
                <font>Trường hợp 4</font>
                <h3>Có cảm giác khó chịu gọi là:<a class="color_red">Nhà vệ sinh ở đâu?</a> </h3>
                <p>Bây giờ điều duy nhất tôi muốn là một cái nhà vệ sinh, vừa xuống bến xe là muốn chạy đến nhà vệ sinh, nếu ở những địa điểm du lịch, trên xe giữa chặng đường không có nhà vệ sinh hoặc nhà vệ sinh có nhiều người thì thật thê thảm... </p>
                <p>Thực sự không chịu nổi, là người đàn ông trưởng thành không thể tùy tiện tiểu tiện giống như trẻ nhỏ được? </p>
            </div>
        </div>
    </div>
    <div class="btn">
        <p><a href="<?= $link_tuvan;?>">Tôi đã từng <br>bị như vậy<br />
            Click tư vấn</a></p>
    </div>
</div>
<div id="title2" class="title">
    <div class="tt">
        <div class="tit_stt">02</div> Thiếu kiến thức, không tìm được đúng phương pháp?
        <p style="color: black;margin: 20px 0 0 0 ;line-height: 25px;">Viêm tiền liệt tuyến là bệnh dai dẳng, nguyên nhân bệnh phức tạp, hiện tại có nhiều liệu pháp điều trị nhưng không có tác dụng. Rất nhiều nam giới do thiếu hiểu biết mà áp dụng các liệu pháp bảo thủ, dưới ảnh là 3 liệu pháp điều trị (viêm tiền liệt tuyến do vi khuẩn, viêm tiền liệt tuyến phi vi khuẩn, viêm tiền liệt tuyến dai dẳng), từ đó làm cho bệnh tình tái phát nhiều lần, ngày càng nghiêm trọng, bỏ lỡ thời gian điều trị thích hợp...</p>
    </div>
    <div class="mian">
        <h3>Điều trị bằng kháng sinh</h3>
        <span><img src="images/mian2_pic.jpg" class="af_load_pic" data-original="images/mian2_pic.jpg" height="160" width="316" /></span>
        <p>Chủ yếu điều trị viêm tiền liệt tuyến do vi khuẩn có hiệu quả ban đầu, nhưng lâu dần sẽ nhờn thuốc dẫn đến tổn hại chức năng thận, đường ruột, gan... Tăng nguy cơ mắc các bệnh viêm nhiễm. </p>
        <font>Bạn đã đi kiêm tra chưa?<br>Chưa kiểm tra bạn có dám tùy tiện điều trị không?</font>
        <b><a href="<?= $link_tuvan;?>">Vẫn chưa chắc chắn?<br> Tư vấn trực tuyến là phương án tốt nhất!</a></b>
    </div>
    <div class="mian">
        <h3>Điều trị vật lý trị liệu</h3>
        <span><img src="images/mian2_pic2.jpg" class="af_load_pic" data-original="images/mian2_pic2.jpg" height="160" width="316" /></span>
        <p>Có tác dụng nhất định đối với bệnh nhân bị viêm tiền liệt tuyến, nhưng yêu cầu kỹ thuật cao, thao tác rắc rối, người bệnh cảm thấy đau và liệu trình kéo dài, gây thương tổn cho tiền liệt tuyến. </p>
        <font>Bạn bị viêm tiền liệt tuyến dai dẳng?<br>Không xác định? Bạn có dám thử không? </font>
        <b><a href="<?= $link_tuvan;?>" style="line-height: 40px;">Thế nào là viêm tiền liệt tuyến dai dẳng?</a> </b>
    </div>
    <div class="mian" style="margin:0;">
        <h3>Massage tiền liệt tuyến</h3>
        <span><img src="images/mian2_pic3.jpg" class="af_load_pic" data-original="images/mian2_pic3.jpg" height="160" width="316" /></span>
        <p>Có sự hỗ trợ đối với viêm tiền liệt tuyến do vi khuẩn mãn tính và </p>
        <font>Không chắc chắn?<br>Sao dám tùy tiện thử?</font>
        <b><a href="<?= $link_tuvan;?>">Làm sao để biết được bản thân có bị viêm tiền liệt tuyến do vi khuẩn hay không?</a> </b>
    </div>
</div>
<div id="title3" class="title">
    <div class="tt" style="height: 65px;">
        <div class="tit_stt">03</div> 3 triệu chứng có thể hết, nhờ 1 chiêu duy nhất
    </div>
    <div class="m">
        <div class="mian">
            <h3>Hệ thống điều trị đa chức năng tiền liệt tuyến - MCDR</h3>
            <h2>Làm thế nào để làm được đồng thời hết 3 triệu chứng bệnh? </h2>
            <p>Hệ thống điều trị đa chức năng tiền liệt tuyến - MCDR do viện nghiên cứu bệnh tiền liệt tuyến Anh quốc giám chế, đầu tiên là kết hợp 2 bước phục hồi và điều trị, có thể điều trị phân loại các loại viêm tiền liệt tuyến, mang tính hợp lý, khoa học đối với toàn bộ quá trình điều trị; có tác dụng không đau không xâm lấn, an toàn hiệu quả cao, không tác dụng phụ! </p>
            <span><a href="<?= $link_tuvan;?>">Tìm hiểu chi tiết</a></span> </div>
    </div>
    <div class="m2 m_item">
        <div class="mian">
            <h3>01 Viêm tiền liệt tuyến do vi khuẩn</h3>
            <p><b>Tình trạng bệnh:</b> biểu hiện chủ yếu là đau vùng xương chậu, có thể thấy vùng hạ bộ, dương vật, xung quanh hậu môn, niệu đạo, xương cụt, thắt lưng... Biểu hiện bất thường thường gặp là: tiểu rắt, tiểu nhiều, tiểu buốt...</p>
            <div class="tt" style="background: none"><b style="color: black">MCDR điều trị<br>các chứng bệnh</b>
                <p>điều trị có hiệu quả cao <br />đến các vị trí bệnh</p>
                <span><img src="images/mian3_ico.jpg" class="af_load_pic" data-original="images/mian3_ico.jpg" height="21" width="30" /></span>
                <p>Diệt khuẩn phục hồi<br />tổ chức thương tổn</p>
            </div>
            <div class="tx">
                <span><a href="<?= $link_tuvan;?>">Tôi có bị như vậy?<br>không thể kiểm tra xác minh</a></span>
                <font><a href="<?= $link_tuvan;?>">Còn các vấn đề khác<br>Click tư vấn bác sỹ</a></font>
            </div>
        </div>
    </div>
    <div class="m3 m_item">
        <div class="mian">
            <h3>02 Viêm tiền liệt tuyến phi vi khuẩn</h3>
            <p><b>Tình trạng bệnh:</b> biểu hiện chủ yếu là  đau vùng xương chậu, thường gặp là vùng hạ bộ, dương vật, quanh hậu môn, xương cụt, vùng thắt lưng... Biểu hiện bất thường là tiểu rắt, tiểu buốt, tiểu nhiều...giảm khả năng tình dục... </p>
            <div class="tt" style="background: none">
                <b style="color: black">Đặc trưng<br>dùng thuốc</b>
                <p>Trực tiếp dẫn thuốc<br />phục hồi chức năng</p>
                <span><img src="images/mian3_ico.jpg" class="af_load_pic" data-original="images/mian3_ico.jpg" height="21" width="30" /></span>
                <p>củng cố hiệu quả điều trị<br />tránh tái phát </p>
            </div>
            <div class="tx">
                <span><a href="<?= $link_tuvan;?>">Tôi có triệu chứng tương tự?<br>không thể tự xác minh kiểm tra</a></span>
                <font><a href="<?= $link_tuvan;?>">Còn có vấn đề khác<br>Click tư vấn bác sỹ</a></font>
            </div>
        </div>
    </div>
    <div class="m2 m_item" style="background:url(images/mian3_bg4.jpg);">
        <div class="mian">
            <h3>03 Viêm tiền liệt tuyến mãn tính </h3>
            <p><b>Tình trạng bệnh:</b> nguyên nhân chủ yếu của bệnh là nhân tố nội tiết tố thần kinh, nhân tố tâm lý tinh thần, rối loạn khả năng tiểu tiện, viêm nhiễm, phản ứng miễn dịch bất thường, rối loạn chức năng niệu đạo dưới gây ra...</p>
            <div class="tt" style="background: none"><b>triệu chứng<br>đặc trưng：</b>
                <p style="width: 200px;">Định vị chính xác tránh<br />tổn thương tế bào bình thường</p>
                <span><img src="images/mian3_ico.jpg" class="af_load_pic" data-original="images/mian3_ico.jpg" height="21" width="30" /></span>
                <p style="width: 280px;">Tác động vào sâu bên trong ổ bệnh<br />kích hoạt phục hồi kích thích thần kinh</p>
            </div>
            <div class="tx"> <span><a href="<?= $link_tuvan;?>">Tôi có bị như vậy?<br>không thể kiểm tra xác minh</a></span>
                <font><a href="<?= $link_tuvan;?>">Còn vấn đề gì khác<br>Click tư vấn bác sỹ</a></font>
            </div>
        </div>
    </div>
</div>
<div id="title4" class="title">
    <div class="tt">
        <div class="tit_stt">04</div> Phá vỡ tận gốc bệnh, bệnh không tái phát!
        <p style="color: black;line-height: 25px;margin-top: 30px;">Bác sỹ phòng khám đa khoa Giải Phóng cho biết: ống tuyến nhỏ của tiền liệt tuyến được bao bọc bởi 3 lớp màng ngoài mô mỡ, thông thường các phân tử thuốc và vật lý trị liệu khó mà vào trong được tuyến thể để phát huy tác dụng, do đó phương pháp điều trị thông thường chỉ trì hoãn được triệu chứng. Hệ thống điều trị hiệu ứng đa năng tiền liệt tuyến tấn công màng mỡ, làm mềm hóa các màng bọc, tác động sâu vào bên trong, phát huy tác dụng tối đa, tuyệt đối không tái phát.</p>
    </div>
    <div class="l">
        <div class="t1"> <span><img src="images/mian4_pic.jpg" class="af_load_pic" data-original="images/mian4_pic.jpg" height="121" width="105" /></span>
            <h3>Dây dẫn trực quan, định vị chính xác </h3>
            <p>Hệ thống định vị trực quan có thể định vị chính xác vị trí bệnh của tiền liệt tuyến, dưới trạng thái trực quan làm cho năng lượng đa hiệu ứng tác động chính xác vào vị trí bệnh, đảm bảo điều trị một lần sẽ được tiến hành an toàn chính xác.</p>
        </div>
        <div class="t1"> <span><img src="images/mian4_pic2.jpg" class="af_load_pic" data-original="images/mian4_pic2.jpg" height="121" width="105" /></span>
            <h3>Thông ống tuyến, phục hồi chức năng </h3>
            <p>Tác dụng đối với xung quanh niệu đạo sau, làm cho xung quanh niệu đạo sau tiền liệt tuyến tăng sinh và miệng ống tắc được nhanh chóng tiếp xúc, miệng ống tuyến nhỏ khai thông, bài tiết ra vi khuẩn bệnh, các chất có hại, đồng thời loại bỏ các vấn đề về áp lực tinh thần, phục hồi sinh lý.</p>
        </div>
        <div class="t1" style="height:122px; border:none;"> <span><img src="images/mian4_pic3.jpg" class="af_load_pic" data-original="images/mian4_pic3.jpg" height="121" width="105" /></span>
            <h3>Kết hợp đa năng, điều trị toàn diện </h3>
            <p>Tiêu diệt loại bỏ toàn diện các bệnh trong thể tuyến như tiền liệt tuyến, tinh toàn, niệu đạo... Giải quyết toàn diện các bệnh tiền liệt tuyến và các triệu chứng như tiểu rắt, tiểu buốt,tiểu nhỏ giọt, tiểu khó khăn, giảm sinh lý, không cương cứng, xuất tinh sớm...</p>
        </div>
    </div>
    <div class="r">
        <div class="t1"> <span style="height: 160px;"><img src="images/mian4_pic4.jpg" class="af_load_pic" data-original="images/mian4_pic4.jpg" height="121" width="105" /></span>
            <h3>Xâm nhập sâu, dùng thuốc đúng vị trí</h3>
            <p>Kỹ thuật xúc dẫn thẩm thấm sung mạch tiên tiến, có thể hòa tan màng bọc lipid tiền liệt tuyến, thúc đẩy làm cho tuần hoàn máu cục bộ tăng nhanh, mềm hóa thành tế bào, phân giải liên kết tế bào, làm cho cao phân tử, thuốc nồng độ cao xâm nhập vào ống nhỏ tiền liệt tuyến, thúc đẩy tổ chức tế bào bệnh thay đổi, tiêu viêm diệt khuẩn triệt để.</p>
        </div>
        <div class="t1"> <span><img src="images/mian4_pic5.jpg" class="af_load_pic" data-original="images/mian4_pic5.jpg" height="121" width="105" /></span>
            <h3>An toàn hiệu quả cao, điều trị đồng loạt</h3>
            <p>Hiệu ứng nhiệt năng cao trực tiếp tác dụng vào bên trong tổ chức bệnh, tiêu viêm diệt khuẩn nhanh chóng, giảm sưng đau co thắt... Có ưu điểm là an toàn nhanh chóng, hiệu quả nhanh, không gây đau, toàn diện triệt để...</p>
        </div>
        <div class="t1" style="height:122px; border:none;"> <span><img src="images/mian4_pic6.jpg" class="af_load_pic" data-original="images/mian4_pic6.jpg" height="121" /></span>
            <h3>Phục hồi nhanh chóng, tuyệt đối không tái phát </h3>
            <p>Thúc đẩy tái sinh tế bào và sản sinh mạch máu mới, kích thích tổng hợp protein, kịp thời phục hồi tổ chức thương tổn tiền liệt tuyến, ức chế nhanh chóng hợp thành DNA vi khuẩn gây bệnh, có hiệu quả triệt để kháng lại sự xâm nhập của vi khuẩn gây bệnh, củng cố hiệu quả điều trị và tuyệt đối không tái phát.</p>
        </div>
    </div>
</div>
<div id="title6" class="title">
    <div class="tt" style="height: 65px;margin-bottom: 30px;">
        <div class="tit_stt">05</div> Truyền miệng nhau, mọi người cùng lựa chọn!
    </div>
    <div class="mian"> <span><img src="images/mian6_pic.jpg" class="af_load_pic" data-original="images/mian6_pic.jpg" height="177" width="329" /></span>
        <div class="t">
            <h3>Lý do lựa chọn</h3>
            <p>Truyền miệng tốt, hiệu quả nhanh, chi phí hợp lý không lâu sau đã khỏi rồi</p>
        </div>
        <h2>Anh Minh: làm lái xe  28 tuổi</h2>
        <b>
            Tôi được một người bệnh giới thiệu, phòng khám này rất tốt, môi trường dễ chịu. Giá tiền trong phạm vi chúng tôi chấp nhận được, dịch vụ tốt, hiệu quả điều trị tốt!
        </b>
        <font><a href="<?= $link_tuvan;?>">Kiểm tra chi tiết</a></font></div>
    <div class="mian2"> <span><img src="/public/images/loading.gif" class="af_load_pic" data-original="images/mian6_pic2.jpg" height="177" width="329" /></span>
        <div class="t">
            <h3>Lý do lựa chọn</h3>
            <p>Vợ lên mạng kiểm tra. Nghe nói lượng khám nhiều,chắc là tốt</p>
        </div>
        <h2>Anh Nguyễn Văn Thắng: 36 tuổi</h2>
        <b>Nhân viên kỹ thuật “tiểu rắt, tiểu cấp, tiểu không hết, tiểu chậm, dương vật khó chịu, gần đây tiểu đêm nhiều, tiểu đếm 3-4 lần, có chiều hướng tăng, đi kiểm tra ở bệnh viện thành phố là: viêm tiền liệt tuyến, cần phải massage tiền liệt tuyến...</b>
        <font><a href="<?= $link_tuvan;?>">Kiểm tra chi tiết</a></font>
    </div>
    <div class="mian"> <span><img src="/public/images/loading.gif" class="af_load_pic" data-original="images/mian6_pic3.jpg" height="177" width="329" /></span>
        <div class="t">
            <h3>Lý do lựa chọn</h3>
            <p>Điều trị khá đơn giả và chuyên nghiệp</p>
        </div>
        <h2>Nguyễn Văn Đồng: 26 tuổi</h2>
        <b>Nhân viên văn phòng, hàng ngày đều ở văn phòng, lâu dần cảm thấy đau vùng dương vật, thường xuyên đi vệ sinh, bìu tinh hoàn ẩm ướt. Sau khi kiểm tra ở phòng khám đa khoa Giải Phóng Hà Nội,kết quả là bị viêm tiền liệt tuyến phi vi khuẩn. Bác sỹ cho tôi dùng..... </b>
        <font><a href="<?= $link_tuvan;?>">Kiểm tra chi tiết</a></font></div>
    <div class="mian2"> <span><img src="/public/images/loading.gif" class="af_load_pic" data-original="images/mian6_pic4.jpg" height="177" width="329" /></span>
        <div class="t">
            <h3>Lý do lựa chọn</h3>
            <p>Kỹ thuật tiên tiến, truyền miệng tốt
                Công khai minh bạch, yên tâm điều trị
            </p>
        </div>
        <h2>Phạm Văn Lâm: chủ nhà hàng, năm nay 40 tuổi</h2>
        <b>3 năm trước xuất hiện tiểu rắt, tiểu buốt, đã kiểm tra ở một số phòng khám chẩn đoán là viêm tiền liệt tuyến mãn tính. Đã dùng qua phương pháp điều trị dùng kháng sinh nhưng không cải thiện rõ rệt. Sau khi đến phòng khám đa khoa Giải Phóng Hà Nội phát hiện là do dùng nhờn thuốc trong thời gian dài dẫn đến tổn hại chức năng gan, thận...</b>
        <font><a href="<?= $link_tuvan;?>">Kiểm tra chi tiết</a></font>
    </div>
</div>
<?= menu_footer();?>
<script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="js/ltMove.js"></script>
<script type="text/javascript" src="js/fun.js"></script>
<script type="text/javascript" src="js/jquery.scrollLoading-min.js"></script>
<script type="text/javascript">
    BizQQWPA.addCustom({aty: '0', a: '0', nameAccount: 800037231, selector: 'BizQQWPA11'});
    BizQQWPA.addCustom({aty: '0', a: '0', nameAccount: 800037231, selector: 'BizQQWPA12'});
    BizQQWPA.addCustom({aty: '0', a: '0', nameAccount: 800037231, selector: 'BizQQWPA13'});
</script>
<script type="text/javascript">
    $(function(){
        $("img.af_load_pic").scrollLoading();
        nav1Tab();
        zjTab();
        ltMarquee({"mOutBox":"pl_con0","mInBox1":"pl_con1","mInBox2":"pl_con2","mSpeed":40,"mIrection":"top","mHeight":4400});
    });
    function zjTab(){
        $("#title5 .con .zj .zj_tab li").mouseover(function(){
            var _thisIndex=$(this).index();
            $("#title5 .con .zj .zj_con ul").stop().animate({"margin-left":"-"+615*_thisIndex+"px"});
            $("#title5 .con .zj .zj_tab li").removeClass('hover');
            $("#title5 .con .zj .zj_tab li").eq(_thisIndex).addClass('hover');
        });
    }
</script>
</body>
</html>