<?php include_once('../../define.php');?>
<!DOCTYPE html>
<html>
<head>
    <title>Rò hậu môn</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="bootstrap-3.3.4/css/bootstrap.min.css">
    <script src="<?= link_jquery;?>"></script>
    <script type="text/javascript" src="bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/custom.js"></script>
    <link rel="stylesheet" href="css/style.css">
    <base target="_blank" />
</head>
<body>
<?= Addtop();?>
<?= AddRight();?>
<?= popup();?>
<?php
$domain=domain;
$linktuvan=link_tuvan;
$linkskype=link_skype;
?>
<div class="container-fluid">
    <?= cd_menu_top();?>
    <div class="row">
        <div class="banner">
            <img src="images/banner.jpg">
            <a href="<?php echo $linktuvan;?>" class="banner_tv"><img src="img/banner_tv.png" style="    height: 44px;
    width: 227px;
    position: absolute;
    margin-left: -307px;
    margin-top: 309px;"></a>
        </div>
    </div>
    <div class="row">
        <div class="main">
            <div class="main_item">
                <div class="clear" style="background: #ffffff;"></div>
                <div class="clear" style="background: #ffffff;"></div>
                <div class="title_item">
                    <h3>
                        <label class="title_itemtruoc">Tìm phương pháp hiệu quả</label>
                        <label class="title_itemsau"> hỗ trợ điều trị bệnh rò hậu môn</label>
                    </h3>
                </div>
                <div class="row main_item1">
                    <div class="item1_1">
                        <label>Phòng khám nhỏ ven đường </label>
                        <p>Một phút điều trị bệnh rò hậu môn, chữa không khỏi không lấy tiền</p>
                    </div>
                    <div class="item1_2">
                        <label>Nghe người khác nói</label>
                        <p>Con bé hàng xóm gần nhà tôi uống thuốc xx liền khỏi bệnh!</p>
                    </div>
                    <div class="item1_3">
                        <label>Tờ rơi</label>
                        <p>Bí kíp cổ truyền điều trị bệnh rò hậu môn, đảm bảo điều trị khỏi!</p>
                    </div>
                    <div class="item1_4">
                        <label>Bán thuốc</label>
                        <p>Phương thuốc bí truyền, bôi là khỏi!</p>
                    </div>
                    <a href="<?php echo $linktuvan;?>" class="item1_bstv"><img src="img/btn_bstv.jpg"></a>
                    <div class="item1_5">
                        <div class="item1_5_1">Thao tác thủ thuật quy phạm hơn</div>
                        <div class="item1_5_2">Tiêu chuẩn phục hồi PAC, hồi phục tốt</div>
                        <div class="item1_5_3">Toàn bộ quá trình liệu pháp quốc tế xâm lấn tối thiểu an toàn</div>
                        <div class="item1_5_4">Điều trị thời gian ngắn, dễ hồi phục, tiết kiệm tiền hơn</div>
                    </div>
                    <a href="<?php echo $linktuvan;?>"><img src="img/bnt_hcpt_lagi.png" style="float: left;margin-left: 532px;margin-top: 5px;"></a>
                    <div class="item1_6">
                        <span class="color_do">Kỹ thuật không đau xâm lấn tối thiểu HCPT</span> của Mỹ do ưu thế và hiệu quả đặc thù được người bệnh sử dụng và tin tưởng.
                    </div>
                </div>
            </div>
            <div class="clear2"></div>
            <div class="main_item part2">
                <div class="title_item">
                    <h3>
                        <label class="title_itemtruoc">Kỹ thuật HCPT của Mỹ </label>
                        <label class="title_itemsau">là lựa chọn tin cậy của người bệnh rò hậu môn</label>
                    </h3>
                </div>
                <div class="clear"></div>
                <div class="row main_item2">
                    <div class="item2_row1">
                        <span>Nguyên lý liệu pháp</span>
                        <p>Thủ thuật xâm lấn tối thiểu HCPT của Mỹ áp dụng máy soi trực tràng hậu môn đưa vào bên trong hậu môn, thông qua máy soi, trực tiếp tiến hành đông điện xâm lấn tối thiểu làm miệng trong lỗ rò khô lại, sau đó rửa khô sạch dịch mủ bên trong lỗ rò, ngăn chặn nguồn nhiễm trùng, từ đó chữa khỏi bệnh.</p>
                    </div>
                    <div class="item2_row2">
                        <div class="item2_row2_col1">
                            <span>Ưu thế kỹ thuật</span>
                            <p>An toàn, ít đau, ít chảy máu, tỷ lệ tái phát thấp nhất.</p>
                        </div>
                        <div class="item2_row2_col2">
                            <span>Đối tượng phù hợp</span>
                            <p>Những người điều trị lâu không khỏi, đi làm, nữ giới, người già,trẻ nhỏ...</p>
                        </div>
                    </div>
                    <div class="item2_row3">
                        <div class="item2_row3_col1">
                            <span>An toàn xâm lấn tối thiểu</span>
                            <p>Thủ thuật truyền thống vết thương trên 10cm, kỹ thuật HCPT chỉ 0.5 - 1cm, thủ thuật an toàn cao</p>
                        </div>
                        <div class="item2_row3_col2">
                            <span>Máy kiểm soát kỹ thuật số</span>
                            <p>Kiểm soát chính xác bằng máy tính, cải thiện tốt cảm giác khó chịu do giải phẫu ống hậu môn gây ra, nâng cao khả năng kiểm soát cho người bệnh.</p>
                        </div>
                    </div>
                    <div class="item2_row4">
                        <div class="item2_row4_col1">
                            <span>Độ chính xác cao</span>
                            <p>Kỹ thuật giám sát chính xác, camera kỹ thuật số định vị chính xác vùng bệnh, trong thủ thuật màn hình hiển thị phóng to gấp 10 lần tổ chức bệnh.</p>
                        </div>
                        <div class="item2_row4_col2">
                            <span>Ít biến chứng</span>
                            <p>Không xuất hiện các biến chứng: phù nề, hẹp hậu môn, nhiễm trùng... tỉ lệ gây biến chứng thấp</p>
                        </div>
                    </div>
                    <div class="item2_row5">
                        <div class="item2_row5_col1">
                            <span>Ít đau hơn</span>
                            <p>Gây mê và gây tê, kỹ thuật HCPT tác dụng từ trường điện rung cao tần rung động 480.000 lần/ phút, người bệnh ít gây đâu đơn.</p>
                        </div>
                        <div class="item2_row5_col2">
                            <span style="padding-left: 51px;font-size: 14px;">Thời gian ngắn</span>
                            <p>viết thương hầu như là không có, thời gian thủ thuật ngắn tầm 15 phút.</p>
                        </div>
                    </div>
                </div>
                <div class="row item2_nhacnho">
                    <div class="col-sm-2">
                        <img src="images/bsnhacnho.jpg">
                    </div>
                    <div class="col-sm-7">
                        <span>Bác sỹ nhắc nhở</span>
                        <p>Rò hậu môn không kiểm tra và điều trị kịp thời, bệnh tình nặng hơn dẫn đến các bệnh trực tràng hậu môn khác, thậm chí dẫn tới ung thư!</p>
                    </div>
                    <div class="col-sm-3">
                        <a href="<?php echo $linktuvan;?>" ><img src="img/btn_bsnhacnho.jpg" style="padding-top: 25px;"></a>
                    </div>
                </div>
            </div>
            <div class="clear2"></div>
            <div class="main_item item3">
                <div class="title_item">
                    <h3>
                        <label class="title_itemtruoc">Bệnh nhân hồi phục chứng nhận</label>
                        <label class="title_itemsau">là phương pháp tốt nhất</label>
                    </h3>
                </div>
                <div class="row">
                    <div class="col-sm-6 item3_left">
                        <div class="row">
                            <div class="col-sm-4"><img src="images/item3_1.jpg"></div>
                            <p style="padding: 29px;text-align: justify;">Khỏi bệnh rồi! Không còn phải lo lắng mùi khó chịu của bệnh rò hậu môn làm cho đồng nghiệp xa lánh nữa!</p>
                        </div>
                        <div class="row">
                            <p style="padding: 29px;text-align: justify;">Khỏi bệnh rồi! Nam giới không cần phải lót băng vệ sinh khi đi làm nữa!</p>
                            <div class="col-sm-4"><img src="images/item3_2.jpg"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4"><img src="images/item3_3.jpg"></div>
                            <p style="padding: 29px;text-align: justify;">Khỏi bệnh rồi! Bệnh rò hậu môn khỏi rồi, mông không còn đau nữa, ngồi lâu cũng không sợ!</p>
                        </div>
                        <div class="row">
                            <p style="padding: 29px;text-align: justify;">Khỏi bệnh rồi! Bệnh rò hậu môn khỏi rồi, khi nào đi vệ sinh là do tôi chủ động!</p>
                            <div class="col-sm-4"><img src="images/item3_4.jpg"></div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <img src="images/item3_title_right.jpg" style="width: 461px;margin-left: -1px;">
                        <div class="row item3_right">
                            <div class="clear"></div>
                            <div class="col-sm-2">
                                <img src="images/item3_5.jpg">
                            </div>
                            <div class="col-sm-10">
                                <span>Thủ thuật xâm lấn tối thiểu HCPT thật thần kỳ, bệnh rò hậu môn thực sự khỏi rồi! </span><label> - chị Nga</label>
                            </div>
                            <div class="ngachngang"></div>
                            <div class="col-sm-2">
                                <img src="images/item3_6.jpg">
                            </div>
                            <div class="col-sm-10">
                                <span>Sau khi bệnh rò hậu môn được điều trị bằng kỹ thuật HCPT, không còn đau nữa! </span><label> - Ông Vương</label>
                            </div>
                            <div class="ngachngang"></div>
                            <div class="col-sm-2">
                                <img src="images/item3_7.jpg">
                            </div>
                            <div class="col-sm-10">
                                <span>Sau khi điều trị bằng kỹ thuật xâm lấn tối thiểu HCPT, không còn chảy mủ do rò hậu môn nữa, cảm thấy khô thoáng hơn! </span><label> - Ông Lưu</label>
                            </div>
                            <div class="ngachngang"></div>
                            <div class="col-sm-2">
                                <img src="images/item3_8.jpg">
                            </div>
                            <div class="col-sm-10">
                                <span>Không còn bệnh rò hậu môn, tôi không còn ngại giao tiếp nữa. </span><label> - chị Hằng</label>
                            </div>
                            <div class="ngachngang"></div>
                            <div class="col-sm-2">
                                <img src="images/item3_9.jpg">
                            </div>
                            <div class="col-sm-10">
                                <span>Sau khi điều trị khỏi rò hậu môn, không còn lo lắng sự đau đớn khi đi đại tiện nữa.</span><label> - chị Hà</label>
                            </div>
                            <div class="ngachngang"></div>
                            <div class="col-sm-2">
                                <img src="images/item3_10.jpg">
                            </div>
                            <div class="col-sm-10">
                                <span>phòng khám đa khoa Giải Phóng Hà Nội điều trị khỏi bệnh rò hậu môn, không còn đau đớn nữa, cảm giác nhẹ nhàng hơn!</span><label> - Chị Mai</label>
                            </div>
                        </div>
                        <div class="row item3_cgtv">
                            <a href="<?php echo $linktuvan;?>"><img src="img/btn_cgtv.jpg" class=""></a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <a href="<?php echo $linktuvan;?>"><img src="images/item3_bsnhacnho.jpg" class="img-responsive"></a>
                    </div>
                </div>
            </div>
            <div class="clear2"></div>
            <div class="main_item part4">
                <div class="title_item">
                    <h3>
                        <label class="title_itemtruoc">Dịch vụ y tế</label>
                        <label class="title_itemsau">chuyên nghiệp</label>
                    </h3>
                </div>
                <div class="clear"></div>
                <style>
                    .col-md-4{padding-right: 5px;padding-left: 0;}
                </style>
                <div class="dm_noidung">
                    <div class="row anh-phong-kham-1" style="margin-top:20px;">
                        <div class="col-md-9 anh-phong-kham-2" style="padding-right: 0;">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="img/hinhanhpk/00.jpg" alt="hinhanhphongkham">
                                </div>
                                <div class="col-md-4">
                                    <img src="img/hinhanhpk/11.jpg" alt="le tan">
                                </div>
                                <div class="col-md-4">
                                    <img src="img/hinhanhpk/22.jpg" alt="phong kham 1">
                                </div>
                                <div class="col-md-8" style="  padding-right: 13px;padding-left: 0px;">
                                    <img src="img/hinhanhpk/44.jpg" alt="phong kham 2">
                                </div>
                                <div class="col-md-4">
                                    <img src="img/hinhanhpk/55.jpg" alt="phong kham 3">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3" style="padding-left: 0px;">
                            <img src="img/hinhanhpk/33.jpg" alt="thu ngan" style="width: 230px; height: 324px;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--<div id="footer">
        <div class="footer">
            <div class="footer_left">
                <div class="f_left">
                    <img src="img/footer/logo_footer.png" alt="do hau mon" style="width: 384px;">
                </div>
            </div>
            <div style="float: left;margin-top: 40px;"><img src="img/footer/chia_footer.jpg" alt="do hau mon"></div>
            <div class="footer_right">
                <div class="f_right">
                    <div class="ico_f">
                        <a href="<?php /*echo $linktuvan;*/?>" target="_blank"><img src="img/footer/tv-1.png"></a>
                        <a href="<?php /*echo $linktuvan;*/?>" target="_blank"><img src="img/footer/tv-2.png"></a>
                        <a href="<?php /*echo $linkskype;*/?>" target="_blank"><img src="img/footer/tv-3.png"></a>
                        <a href="/"><img src="img/footer/tv-4.png"></a>
                    </div>
                </div>
                <div class="clr"></div>
                <img src="img/footer/footer_right.png" alt="ro hau mon" style="float: left;  margin-top: 10px;">
            </div>
        </div>
    </div>-->
    <?= cd_footer();?>
</div>
<?= line_chat();?>
</body>
</html>