<?php 
$link_trangchu = "http://phongkhamgiaiphong.com/";
$link_tv = "http://swt.pk709.com/LR/Chatpre.aspx?id=KTF27288478&lng=en";
$link_gioithieu = "http://phongkhamgiaiphong.com/cd6/gioi-thieu/";
$link_tuyenduong = "http://phongkhamgiaiphong.com/cd6/lo-trinh-kham/";
$link_kythuat = "http://khamnamkhoahanoi.vn/ky-thuat";
$link_thietbi = "http://khamnamkhoahanoi.vn/thiet-bi";
?>
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <title> Đón chào năm mới, trao gửi niềm tin </title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.3.1/css/hover-min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" />

  </head>
  <script>
      new WOW().init();
</script>

  <body>
  <div class="header m-4">
  	 <div class="container">
  	 	 <div class="row">
  	 	 	 <div class="col-md-5">
  	 	 	 	 <img src="images/logo.png" alt="">
  	 	 	 </div>
  	 	 	 <div class="col-md-2">
  	 	 	 	 <img class="pt-2" src="images/ic_p.png" alt="">
  	 	 	 </div>
  	 	 	 <div class="col-md-2">
  	 	 	 	<a href="<?= $link_tv;?>"><img class="pt-2" src="images/ic_h.png" alt=""></a>
  	 	 	 </div>
  	 	 	 <div class="col-md-3">
  	 	 	 	 <a href="<?= $link_tv;?>"><img class="pt-2" src="images/ic_m.png" alt=""></a>
  	 	 	 </div>
  	 	 </div>
  	 </div>
  </div>
 <!--------- menu -------->
 <div class="menu">
 	 <div class="container">
 	 	 <div class="row">
 	 	 	<div class="col-md-12">
	 	 	 	<div class="db_menu">
		 	 	 	 <ul>
		 	 	 	 	 <li>
		 	 	 	 	 	 <a href="<?= $link_trangchu;?>"> Trang chủ </a>
		 	 	 	 	 </li>
		 	 	 	 	 <li>
		 	 	 	 	 	 <a href="<?= $link_gioithieu;?>"> Giới thiệu  </a>
		 	 	 	 	 </li>
		 	 	 	 	 <li>
		 	 	 	 	 	 <a href="<?= $link_thietbi?>"> Thiết bị  </a>
		 	 	 	 	 </li>
		 	 	 	 	 <li>
		 	 	 	 	 	 <a href="<?= $link_tv;?>"> Bác sĩ  </a>
		 	 	 	 	 </li>
		 	 	 	 	 <li>
		 	 	 	 	 	 <a href="<?=$link_tuyenduong;?>"> Tuyến xe </a>
		 	 	 	 	 </li>
		 	 	 	 	 <li>
		 	 	 	 	 	 <a href="<?=$link_tv;?>"> Đăng ký trực tuyến  </a>
		 	 	 	 	 </li>
		 	 	 	 </ul>
	 	 	 	</div>
 	 	 		
 	 	 	</div>
 	 	 </div>
 	 </div>
 </div>
<!---------- slider ------------>
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			
			<div class="carousel-inner" role="listbox">
				<div class="carousel-item active" style="background: #7d0417;">
					<img style="display: block;margin: auto" src="http://khamnamkhoahanoi.vn/cdsuckhoe/chuyen-muc-suc-khoe/images/banner.jpg" alt="First slide">
				</div>
			</div>
			<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
				<i class="fa fa-chevron-right fa-2x" aria-hidden="true"></i>
			</a>
			<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
				<i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i>
			</a>
		</div>
		<!------ home 1 ---------->
		<div class="home1 wow zoomIn">
			<div class="container">
				 <div class="row mb-4 pt-3">
				 	 <div class="col-md-3 text-center">
				 	 	<img src="images/top_cg1.png" alt="">
				 	 </div>
				 	 <div class="col-md-3 text-center">
				 	 	<img src="images/xn.png" alt="">
				 	 </div>
				 	 <div class="col-md-3 text-center">
				 	 	<img src="images/tt.png" alt="">
				 	 </div>
				 	 <div class="col-md-3 text-center">
				 	 	<img src="images/dau.png" alt="">
				 	 </div>
				 </div>
				 <div class="row text-center mx-auto mb-4">
				 	 <div class="tt_home1 text-center"> hãy đến với phòng khám Đa khoa Giải Phóng <b> Thiết bị đầy đủ - Điều trị hiệu quả - Chi phí thấp </b></div>
				 </div>
				 <div class="row">
				 	 <p class="text-justify px-5 py-3">
				 	 	Để chào mừng năm mới 2019, phòng khám đa khoa Giải Phóng Hà Nội tổ chức triển khai chương trình ưu đãi giảm giá khám chữa bệnh cực sốc. Theo đó người bệnh sẽ được các chuyên gia tư vấn hoàn toàn miễn phí, được giảm 50% chi phí xét nghiệm, giảm 50% chi phí thủ thuật và giảm 50% chi phí điều trị. Thông qua hoạt động thiết thực này, phòng khám Giải Phóng mong muốn mang tới cho người dân ở địa bàn thủ đô Hà Nội và các tỉnh thành lân cận một dịch vụ y tế chất lượng cùng mức giá tốt nhất. 
				 	 </p>
				 </div>
			</div>
		</div>
		<div class="home2 mb-5 wow zoomIn">
			 <div class="container">
			 	 <div class="row text-center mx-auto my-5">
			 	 	<div class="col-md-12">
				 	 	 <div class="tt_home2">
				 	 	 	  <div class="red"> 3 hạng mục miễn phí  <span class="yellow"> bạn nhận được </span> </div>
				 	 	 </div>
			 	 	</div>
			 	 </div>
			 	 <div class="row">
			 	 	 <div class="col-md-4 text-center">
			 	 	 	  <div class="red_bg">
			 	 	 	  		 <div class="tt_red"> Đặt hẹn bác sĩ </div>
			 	 	 	  		 <div class="des_red"> Bạn có thể đặt hẹn miễn phí để nhận được sự tư vấn và khám bệnh bởi đội ngũ bác sĩ chuyên môn cao </div>
			 	 	 	  </div>
			 	 	 </div>
			 	 	 <div class="col-md-4 text-center">
			 	 	 	   <div class="reder_bg">
				 	 	 	   	 <div class="tt_red"> Tư vấn  </div>
				 	 	 	  	 <div class="des_red"> Tư vấn miễn phí dành cho người bệnh khi đến khám và chữa bệnh cùng các bác sĩ chuyên khoa  </div>
			 	 	 	   </div>
			 	 	 </div>
			 	 	 <div class="col-md-4 text-center">
			 	 	 	  <div class="red_n_bg">
			 	 	 	  	     <div class="tt_red"> tái khám </div>
			 	 	 	  		 <div class="des_red"> Phòng khám miễn phí tái khám với mong muốn dành cho bạn những trải nghiệm dịch vụ chuyên nghiệp. </div>
			 	 	 	  </div>
			 	 	 </div>
			 	 </div>
			 </div>
		</div>
		<div class="home3 wow zoomIn">
			 <div class="container">
			 	 <div class="row mx-auto justify-content-center">
			 	 	 <div class="col-md-8 col-md-push-2">
			 	 	 	  <div class="row">
			 	 	 	  	  <div class="col-md-2 text-center">
			 	 	 	  	  	 <img src="images/icon_st.png" alt="">
			 	 	 	  	  </div>
			 	 	 	  	  <div class="col-md-8 text-center pt-5">
			 	 	 	  	  	 <img src="images/_50_pt.png" alt="">
			 	 	 	  	  </div>
			 	 	 	  	  <div class="col-md-2 text-center">
			 	 	 	  	  	 <img src="images/icon_st_2.png" alt="">
			 	 	 	  	  </div>
			 	 	 	  </div>
			 	 	 </div>
			 	 </div>
			 	 <div class="row text-center mx-auto justify-content-center">
			 	 	<div class="col-md-8 col-md-push-4">
				 	 	 <div class="tt_home3">
				 	 	 	 Chúng tôi có thiết bị và môi trường mà những nơi khác không thể so sánh 
				 	 	 </div>
			 	 	</div>
			 	 </div>
			 	 <div class="row mt-5">
			 	 	 <div class="col-md-7">
			 	 	 	 <div class="cover_yello">
			 	 	 	 	 <div class="p_text_cv">
			 	 	 	 	 	 Khâu kiểm tra bệnh tại phòng khám được thực hiện theo đúng trình tự, gồm khâu kiểm tra lâm sàng đến làm xét nghiệm, điển hình như xét nghiệm máu, xét nghiệm nước tiểu, xét nghiệm mẫu vật...cùng nhiều xét nghiệm chuyên môn khác. Qúa trình kiểm tra được thực hiện trực tiếp bởi các bác sỹ đầu ngành, áp dụng máy móc kỹ thuật tân tiến, cho phép chẩn đoán bệnh chính xác trong thời gian ngắn nhất <br> <br>
			 	 	 	 	 	 Vì sự an toàn của bạn, hi vọng mọi người nâng cao cảnh giác, lựa chọn cẩn thận! Không nên tin tưởng các phòng khám tư nhân nhỏ lẻ và không chính quy, khi làm thủ thuật nhất định phải lựa chọn phòng khám chính quy, có chất lượng, quy mô lớn...
			 	 	 	 	 </div>
			 	 	 	 	 <div class="p_anh">
			 	 	 	 	 	 <img src="images/bs_tv.png" alt="" class="img_r h-100">
			 	 	 	 	 </div>
			 	 	 	 </div>
			 	 	 </div>
			 	 	 <div class="col-md-5">
			 	 	 	 <img src="images/gr_img_50.png" alt="">
			 	 	 </div>
			 	 </div>
			 	 <div class="row mt-4">
			 	 	  <div class="col-md-7">
			 	 	  	  <img src="images/dk_dt.png" alt="" class="text-center mx-auto" style="display: block;">
			 	 	  </div>
			 	 	  <div class="col-md-5">
			 	 	  	 <a href="<?= $link_tv;?>"><img src="images/btn_tv.png" alt="" class="text-center mx-auto " style="display: block;"></a>
			 	 	  </div>
			 	 </div>
			 </div>
		</div>
		<div class="home4 wow zoomIn">
			<div class="cover_khoi1">
			 	 	  <div class="tit_h4 mt-3">
			 	 	  	 <img src="images/tit_home4.png" alt="">
			 	 	  </div>
			 	 	  <div class="tit_yel mb-5"> (Không phát sinh thêm bất cứ chi phí nào cho người bệnh) </div>
			 	 	  <div class="so1_text mt-2">
			 	 	  	 <div class="so1"> <img src="images/so_1.png" alt=""> </div>
			 	 	  	 <div class="text_so1">
			 	 	  	 	Thu phí một lần, hợp lý minh bạch, không phát sinh thêm bất kỳ chi phí nào khác, giúp bệnh nhân an tâm chữa trị
			 	 	  	 </div>
			 	 	  </div>
			 	 	  <div class="so1_text">
			 	 	  	 <div class="so1"> <img src="images/so_2.png" alt=""> </div>
			 	 	  	 <div class="text_so1">
			 	 	  	 	Quá trình kiểm tra an toàn không gây đau đớn, chỉ mất 3-5 phút, kết quả chính xác, hình ảnh rõ nét.
			 	 	  	 </div>
			 	 	  </div>
			 	 	  <div class="so1_text">
			 	 	  	 <div class="so1"> <img src="images/so_3.png" alt=""> </div>
			 	 	  	 <div class="text_so1">
			 	 	  	 	 Đội ngũ y bác sĩ trên 20 năm kinh nghiệm lâm sàng, đảm bảo thủ  <br> thuật an toàn hiệu quả.
			 	 	  	 </div>
			 	 	  </div>
			 	 	  <div class="so1_text">
			 	 	  	 <div class="so1"> <img src="images/so_4.png" alt=""> </div>
			 	 	  	 <div class="text_so1">
			 	 	  	 	Thủ thuật có độ chính xác cao, kỹ thuật gây mê công nghệ mới <br> không gây đau đớn trong suốt quá trình, hồi phục nhanh.
			 	 	  	 </div>
			 	 	  </div>
			 	 	  <div class="so1_text" style="margin-bottom: 12%;">
			 	 	  	 <div class="so1"></div>
			 	 	  	 <div class="text_so1 float-right">
			 	 	  	 	 <img src="images/doble_ha.png" alt="">
			 	 	  	 </div>
			 	 	  </div>
			 	 </div>
			 	 <div class="khoi2_h4 pl-5">
			 	 <div class="khoi1_tieude">
				 	 	 <img src="images/td_15.png" alt="">
			 	 	<div class="khoi_nd_td">
				 	 	 <div class="so1_text">
			 	 	  	 <div class="so1"> <img src="images/1.png" alt=""> </div>
			 	 	  	 <div class="text_so1">
			 	 	  	 	Kiểm tra kỹ lưỡng trước khi làm thủ thuật, hạn chế rủi ro xuống mức thấp nhất, phòng thủ thuật vô trùng. 
			 	 	  	 </div>
			 	 	  </div>
			 	 	  <div class="so1_text">
			 	 	  	 <div class="so1"> <img src="images/2.png" alt=""> </div>
			 	 	  	 <div class="text_so1">
			 	 	  	 	Áp dụng “kỹ thuật cắt bao quy đầu công nghệ Châu Âu”, ít chảy máu, hồi phục nhanh, không ảnh hưởng tới công tác và học tập.
			 	 	  	 </div>
			 	 	  </div>
			 	 	  <div class="so1_text">
			 	 	  	 <div class="so1"> <img src="images/3.png" alt=""> </div>
			 	 	  	 <div class="text_so1">
			 	 	  	 	Thủ thuật được thực hiện bởi các bác sĩ có hơn 20 năm kinh nghiệm, đảm bảo an toàn không có sai sót.
			 	 	  	 </div>
			 	 	  </div>
			 	 	  <div class="so1_text">
			 	 	  	 <div class="so1"> <img src="images/4.png" alt=""> </div>
			 	 	  	 <div class="text_so1">
			 	 	  	 	Thủ thuật an toàn không đau, đảm bảo tính thẩm mỹ cao, không để lại sẹo, nâng cao rõ rệt đời sống vợ chồng.
			 	 	  	 </div>
			 	 	  </div>
				 	 	 <div class="bqd" style="padding-left: 15%;">
				 	 	 	 <img src="images/bqd.png" alt="">
				 	 	 </div>
			 	 	</div>
			 	 </div>
			 </div>
			 
		</div>
		<div class="home3 wow zoomIn">
			 <div class="container">
			 	 <div class="row mx-auto justify-content-center">
			 	 	 <div class="col-md-8 col-md-push-2">
			 	 	 	  <div class="row">
			 	 	 	  	  <div class="col-md-2 text-center">
			 	 	 	  	  	 <img src="images/icon_st.png" alt="">
			 	 	 	  	  </div>
			 	 	 	  	  <div class="col-md-8 text-center pt-5">
			 	 	 	  	  	 <img src="images/tit_h5.png" alt="">
			 	 	 	  	  </div>
			 	 	 	  	  <div class="col-md-2 text-center">
			 	 	 	  	  	 <img src="images/icon_st_2.png" alt="">
			 	 	 	  	  </div>
			 	 	 	  </div>
			 	 	 </div>
			 	 </div>
			 	 <div class="row text-center mx-auto justify-content-center">
			 	 	<div class="col-md-8 col-md-push-4">
				 	 	 <div class="tt_home3 custom_t_h3">
				 	 	 	 Thông cảm và sẻ chia, mang tới không gian ấm cúng như gia đình
				 	 	 </div>
			 	 	</div>
			 	 </div>
			 	 <div class="row mt-4">
			 	 	 <div class="col-md-7">
			 	 	 	 <div class="cover_white">
			 	 	 	 	 <div class="p_text_cv">
			 	 	 	 	 <div class="tt_tip">
			 	 	 	 	 	PHÒNG KHÁM ĐA KHOA GIẢI PHÓNG ƯU ĐÃI GIẢM TỚI 50%
			 	 	 	 	 </div>
			 	 	 	 	 <div class="des_tip">
			 	 	 	 	 	Phòng khám đa khoa Giải Phóng ưu đãi giảm 50% chi phí điều trị đối với tất cả bệnh nhân khi tới khám và điều trị tại địa chỉ số 709 đường Giải Phóng – Hoàng Mai – Hà Nội. Các phương pháp điều trị đều được nhập khẩu từ các nước có nền y học hiện đại nhất trên thế giới như Mỹ, Đức, Nhật Bản, Hàn Quốc…giúp giải quyết dứt điểm tận gốc căn nguyên bệnh, ngăn ngừa tái phát, không gây đau đớn và đảm bảo an toàn. Qua ưu đãi này, phòng khám mong muốn tất cả những bệnh nhân ở vùng sâu vùng xa, người bệnh có điều kiện kinh tế khó khăn có cơ hội được tiếp cận với dịch vụ y tế chất lượng nhất. 
			 	 	 	 	 </div>
			 	 	 	 	 </div>
			 	 	 	 	 <div class="p_anh">
			 	 	 	 	 	 <img src="images/3benhnhan.png" alt="" class="img_r h-100">
			 	 	 	 	 </div>
			 	 	 	 </div>
			 	 	 </div>
			 	 	 <div class="col-md-5">
			 	 	 	 <img src="images/dt_50.png" alt="">
			 	 	 </div>
			 	 </div>
			 	 <div class="row mt-2">
			 	 	  <div class="col-md-7">
			 	 	  	  <img src="images/dk_dt.png" alt="" style="display: block;" class="mx-auto">
			 	 	  </div>
			 	 	  <div class="col-md-5">
			 	 	  	 <a href="<?= $link_tv;?>"><img src="images/btn_tv.png" alt="" style="display: block;" class="mx-auto"></a>
			 	 	  </div>
			 	 </div>
			 </div>
		</div>
		<div class="home5 wow zoomIn">
			 <div class="container">
			 	 <div class="row mx-auto justify-content-center">
			 	 	 <div class="col-md-8 col-md-push-2">
			 	 	 	 <div class="tt_home5">
			 	 	 	 	 <img src="images/thuthuat_5.png" alt="">
			 	 	 	 </div>
			 	 	 </div>
			 	 </div>
			 	 <div class="row">
			 	 	 <div class="col-md-6">
			 	 	 	  <img src="images/thong.png" alt="">
			 	 	 </div>
			 	 	 <div class="col-md-6">
			 	 	 	 <div class="cv_white mt-4">
			 	 	 	 	 <div class="tt_white_cv">
			 	 	 	 	 	 NHẰM ĐÁP ỨNG NHU CẦU CHĂM SÓC VÀ BẢO VỆ SỨC KHỎE CỦA QUÝ KHÁCH
			 	 	 	 	 </div>
			 	 	 	 	 <div class="content_white mb-4">
			 	 	 	 	 	 Nhằm đáp ứng nhu cầu chăm sóc và bảo vệ sức khỏe của quý khách hàng, Phòng khám đa khoa Giải Phóng luôn trong tâm thế sẵn sàng phục vụ và thực hiện công tác thăm khám bệnh nhanh chóng. Đặc biệt, chúng tôi tổ chức chương trình khuyến mại tháng 12 với những chính sách ưu đãi hấp dẫn giảm 50% chi phí thủ thuật, cam kết nếu tái phát sẽ miễn phí hoàn toàn thủ thuật tạo điều kiện thuận lợi nhất cho quý khách hàng dễ dàng tiếp cận dịch vụ và thỏa mãn những mong muốn.
			 	 	 	 	 </div>
			 	 	 	 	 <img src="images/bs_hai.png" alt="">
			 	 	 	 </div>
			 	 	 </div>
			 	 </div>
			 	 <div class="row mt-5 text-center">
			 	 	 <div class="col-md-6">
			 	 	 	<img src="images/dt_do.png" alt="">
			 	 	 </div>
			 	 	 <div class="col-md-6">
			 	 	 	 <a href="<?= $link_tv;?>"><img src="images/btn_tv.png" alt=""></a>
			 	 	 </div>
			 	 </div>
			 </div>
		</div>
		<div class="home3 wow zoomIn">
			 <div class="container">
			 	 <div class="row">
			 	 	  <div class="col-md-8 col-md-push-2 mx-auto justify-content-center mt-4 text-center">
			 	 	  	  <div class="tt_home6">
			 	 	  	  	 <img src="images/pk_cn.png" alt="">
			 	 	  	  	 <div class="des_home6 text-center mt-3">
			 	 	  	  	 	 Phòng khám là nơi hội tụ đội ngũ y bác sỹ có trình độ chuyên môn cao, hệ thống trang thiết bị hiện đại, dịch vụ chăm sóc tận tình, chu đáo luôn làm hài lòng mọi bệnh nhân. Phòng khám đa khoa 709 Giải Phóng Hà Nội đã và đang cố gắng phấn đấu trở thành một đơn vị chăm sóc sức khỏe có quy mô lớn, khẳng định vị thế và thương hiệu của mình trong lĩnh vực khám, hỗ trợ chữa bệnh.
			 	 	  	  	 </div>
			 	 	  	  </div>
			 	 	  </div>
			 	 </div>
			 	 <div class="row mt-5">
			 	 	<div class="col-md-3">
			 	 		 <div class="baoquanh">
			 	 		 	 <img class="img-fluid" src="images/4_khoi_img1.png" alt="">
			 	 		 </div>
			 	 		 <div class="baoquah2">
			 	 		 	 <div class="tt_baoquanh2">
			 	 		 	 	PHÒNG KHÁM UY TÍN
			 	 		 	 </div>
			 	 		 	 <div class="des_bq">
			 	 		 	 	Đây là phòng khám đa khoa chuyên nghiệp được Sở y tế Hà Nội chứng nhận và cấp phép hoạt động, là cơ sở khám chữa bệnh uy tín và hợp pháp của mọi gia đình.
			 	 		 	 </div>
			 	 		 </div>
			 	 	</div>
			 	 	<div class="col-md-3">
			 	 		 <div class="baoquanh">
			 	 		 	 <img class="img-fluid" src="images/4_khoi_img2.png" alt="">
			 	 		 </div>
			 	 		 <div class="baoquah3">
			 	 		 	 <div class="tt_baoquanh2">
			 	 		 	 	Trang thiết bị hiện đại
			 	 		 	 </div>
			 	 		 	 <div class="des_bq">
			 	 		 	 	Luôn tiên phong trong việc điều trị cho bệnh nhân bằng các trang thiết bị và công nghệ hiện đại đã và đang được ứng dụng trên thế giới.
			 	 		 	 </div>
			 	 		 </div>
			 	 	</div>
			 	 	<div class="col-md-3">
			 	 		 <div class="baoquanh">
			 	 		 	 <img class="img-fluid" src="images/4_khoi_img3.png" alt="">
			 	 		 </div>
			 	 		 <div class="baoquah2">
			 	 		 	 <div class="tt_baoquanh2">
			 	 		 	 	 Y bác sĩ chuyên nghiệp
			 	 		 	 </div>
			 	 		 	 <div class="des_bq">
			 	 		 	 	Với đội ngũ bác sĩ có trình độ chuyên môn cao 20 năm kinh nghiệm trong ngành. Cùng lương tâm Y Đức, trách nhiệm cao, chắc chắn sẽ làm hài lòng khách hàng khi tới khám bệnh.
			 	 		 	 </div>
			 	 		 </div>
			 	 	</div>
			 	 	<div class="col-md-3">
			 	 		 <div class="baoquanh">
			 	 		 	 <img class="img-fluid" src="images/4_khoi_img4.png" alt="">
			 	 		 </div>
			 	 		 <div class="baoquah3">
			 	 		 	 <div class="tt_baoquanh2">
			 	 		 	 	hiệu quả an toàn 
			 	 		 	 </div>
			 	 		 	 <div class="des_bq">
			 	 		 	 	Người bệnh được điều trị trong môi trường khám chữa đảm bảo vô trùng, đúng tiêu chuẩn, chuyên nghiệp và đầy đủ tiện nghi.
			 	 		 	 </div>
			 	 		 </div>
			 	 	</div>
			 	 </div>
			 </div>
		</div>
		<div class="home7 p-5 wow zoomIn">
			 <div class="container">
			 	<div class="row justify-content-center wow bounceInDown">
			 		   <div class="tt_thamkham">
			 		   	 Phòng khám đa khoa 
			 		   </div>
			 	</div>
			 	<div class="row justify-content-center wow bounceInDown">
			 		 <div class="des_tk">
			 		 	Chuyên nghiệp uy tín 
			 		 </div>
			 	</div>
			 	<div class="row">
			 		 <div class="col-md-10 offset-md-1 pb-5">
			 		 	 <div class="des_hai_thamk text-center mt-2 wow zoomIn">
			 		 	 	 Phòng khám đa khoa Giải Phóng với trang thiết bị hiện đại, kỹ thuật tiên tiến, điều trị hiệu quả cao, chi phí thấp.
Không phải phòng khám nào cũng có thể áp dụng kỹ thuật xâm lấn tối thiểu Chỉ có những phòng khám chuyên nghiệp, toàn diện, cơ cấu trang thiết bị và năng lực về y tế chính quy toàn diện mới có đủ tư cách áp dụng
			 		 	 </div>
			 		 </div>
			 	</div>
			 	<div class="row">
			 		 <div class="col-md-4 pr-5 pl-3">
			 		 	   <div class="khoind_1 text-right pb-5">
			 		 	   	  <div class="tt_nd1"> Năng lực được công nhận </div>
			 		 	   	  <div class="des_nd1">
			 		 	   	  	 Phòng khám đa khoa Giải Phóng với trang thiết bị hiện đại, kỹ thuật tiên tiến, điều trị hiệu quả cao, chi phí thấp
			 		 	   	  </div>
			 		 	   </div>
			 		 	   <div class="khoind_2 text-right">
			 		 	   	    <div class="tt_nd2"> Yêu cầu về trình độ </div>
			 		 	   	    <div class="des_nd1 des_nd_custom2">
			 		 	   	    	 Nhằm đảm bảo thực hiện thủ thuật an toàn và hiệu quả cao, thực hiện thủ thuật cần có: 
									1. Bác sỹ có Trình độ thủ thuật cao <br>
									2. Bác sỹ thực hiện hàng ngàn ca thủ thuật không để 
									xuất hiện sự cố <br>
									3. Làm trong ngành 20 năm trở lên 
			 		 	   	    </div>
			 		 	   </div>
			 		 </div>
			 		 <div class="col-md-4 wow zoomIn">
			 		 	 <img class="img-fluid" src="images/img_giua.png" alt="">
			 		 </div>
			 		 <div class="col-md-4 pr-5 pl-3">
			 		 	   <div class="khoind_1 text-left pb-5">
			 		 	   	  <div class="tt_nd1"> Trang thiết bị hiện đại  </div>
			 		 	   	  <div class="des_nd2 des_nd_custom">
			 		 	   	  	Phòng khám đa khoa Giải Phóng, nhập khẩu trang thiết bị hiện đại, đảm bảo tính an toàn và hiệu quả điều trị
			 		 	   	  </div>
			 		 	   </div>
			 		 	   <div class="khoind_2 text-left">
			 		 	   	    <div class="tt_nd2"> Bảo đảm an toàn  </div>
			 		 	   	    <div class="des_nd2 des_nd_custom">
			 		 	   	    	- Môi trường được đảm bảo - phòng thủ thuật sạch sẽ vô khuẩn <br>
									- Bác sỹ được đảm bảo - với đội ngũ y bác sỹ có trên 20 năm 
									kinh nghiệm lâm sàng <br>
									- Kinh nghiệm được đảm bảo - với hàng ngàn ca thủ thuật 
									không sự cố 
			 		 	   	    </div>
			 		 	   </div>
			 		 </div>
			 	</div>
			 	<div class="row justify-content-center">
			 		  <a href="<?= $link_tv;?>"><input type="submit" class=" btn btn-warning clickme" value="Click tư vấn đặt hẹn"></a>
			 	</div>
			 </div>
		</div>
		<footer class="pt-5 pb-5 wow zoomIn">
			 <div class="container">
			 	 <div class="row">
			 	 	 <div class="col-md-3">
			 	 	 	 <img class="img-fluid" src="images/f_logo.png" alt="" style="margin-top: 30px;">
			 	 	 </div>
			 	 	 <div class="col-md-3 justify-content-center text-center" style="border-right: 1px solid #6e0606;border-left: 1px solid #6e0606;">
			 	 	 	 <div class="tt_f"> Trung tâm có uy tín </div>
			 	 	 	 <div class="list_dm_f">
			 	 	 	 	 <ul>
			 	 	 	 	 	 <li>
			 	 	 	 	 	 	 <a href="<?=$link_gioithieu;?>"> Giới thiệu phòng khám </a>
			 	 	 	 	 	 </li>
			 	 	 	 	 	 <li>
			 	 	 	 	 	 	 <a href="<?=$link_thietbi;?>"> Thiết bị hiện đại </a>
			 	 	 	 	 	 </li>
			 	 	 	 	 	 <li>
			 	 	 	 	 	 	 <a href="<?= $link_kythuat;?>"> Kỹ thuật hiện đại   </a>
			 	 	 	 	 	 </li>
			 	 	 	 	 	 <li>
			 	 	 	 	 	 	 <a href="<?= $link_tv;?>"> Tư vấn chi phí </a>
			 	 	 	 	 	 </li>
			 	 	 	 	 	 <li>
			 	 	 	 	 	 	 <a href="<?= $link_tv;?>"> Liên hệ với chúng tôi </a>
			 	 	 	 	 	 </li>
			 	 	 	 	 	 <li>
			 	 	 	 	 	 	 <a href="<?= $link_tv;?>"> Đăng ký trực tuyến </a>
			 	 	 	 	 	 </li>
			 	 	 	 	 </ul>
			 	 	 	 </div>
			 	 	 </div>
			 	 	 <div class="col-md-6"> 
                          <div class="tt_f_cuoi text-center pb-3">
                          	  Liên hệ chúng tôi
                          </div>
                          <div class="dong_col2 pb-3">
                          	 <img src="images/sdt_f_cuoi.png" alt="">
                          	 <a href="https://www.facebook.com/khamnamkhoa709giaiphong/"><img class="text-right pl-5" src="images/fa_bok.png" alt=""></a>
                          </div>
                          <div class="dong_col3 pb-3">
                          	 <a href="<?= $link_tv;?>"><img src="images/f_benhtinh.png" alt=""></a>
                          	 <a href="<?=$link_tv;?>"><img src="images/f_dieutri.png" alt=""></a>
                          	 <a href="<?=$link_tv;?>"><img src="images/f_chiphi.png" alt=""></a>
                          </div>
                          <div class="p_f_text">
                          	 <p>Copyright @ 2009-2018. Phong Kham Da Khoa Giai Phong. All rights reserved</p>
                          	 <p>ĐỊA CHỈ: 709 Giải Phóng - Hoàng Mai - HÀ NỘI</p>
                          	 <p>Sở hữu bản quyền phòng khám Đa Khoa Giải Phóng, nội dung website này chỉ để tham khảo không làm căn cứ chẩn đoán y tế.Tôn trọng ý kiến bác sĩ</p>
                          </div>
			 	 	 </div>
			 	 </div>
			 </div>
		</footer>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
		<script language="javascript" src="http://swt.pk709.com/JS/LsJS.aspx?siteid=KTF27288478&#038;lng=en"></script>
  </body>
</html>