<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"/>
	<link href="style.css" rel="stylesheet"/>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<base target="_blank" />
</head>
<?php require_once('../../define.php');?>
<?= Addtop();?>
<body>

	<div style="background:#0a5f82">
		<div class="container menu-kaka" style="">
			<ul class="nav navbar-nav" style="width:100%">
				<li class="active"><a href="<?= domain;?>">Trang chủ</a></li>
				<li class=""><a href="<?= link_gioithieu;?>">Giới thiệu</a></li>
				<li class=""><a href="<?= link_thietbi;?>">Thiết Bị</a></li>
				<li class=""><a href="<?= link_kythuat;?>">Kỹ thuật</a></li>
				<li class=""><a href="<?= link_tuvan;?>">Hẹn lịch khám</a></li>
				<li class=""><a href="<?= link_lienhe;?>">Liên hệ</a></li>
			</ul>
		</div>
	</div>
    <div class="banner-top">
        <img src="images/banner-top.png"  />
        <div class="container loi-dan">
            <p>Những năm gần đây, áp lực cuộc sống và công việc tăng lên, cộng thêm ăn uống và nghỉ ngơi không điều độ làm mất cân bằng nội tiết tố, không rụng trứng, rối loạn rụng trứng, tinh trùng ít, tinh trùng yếu, không có tinh trùng... Tỷ lệ này có xu hướng tăng lên. Nhưng vì bệnh phức tạp, liên quan đến mất cân bằng hormone cơ thể, do đó việc kiểm tra cơ bản về sinh sản là --- kiểm tra Hormone nội tiết tố 6 hạng mục, là phương pháp kiểm tra để loại bỏ những triệu chứng vô sinh trên. phòng khám đa khoa Giải Phóng Hà Nội triển khai phòng thực nghiệm, kiểm tra chính xác; chi phí mỗi mục kiểm tra đều được các cơ quan liên ngành phê duyệt, để người bệnh được kiểm tra với chi phí hợp lý. </p>
        </div>
    </div>
	<div class="container" style="padding-left:18px;padding-right:28px;padding-top:10px;position: relative; ">
		<div class="row hang-muc-la-gi">
			<p style="color:#09678e;    font-weight: 600;font-size:17px">Hormone nội tiết tố 6 hạng mục là gì? Kiểm tra cần bao nhiêu tiền?</p>
			<p style="color:#8e8e8e;">WHAT ARE SIX HORMONES? CHECK HOW MANY NORMAL?</p>
			<a href="<?= link_tuvan;?>"><img  src="images/click-tu-van-1.png" height="49" width="113"></a>
			
		</div>

	</div>
	<div class="container" style="padding-top:10px;">
			<div class="row noi-dung-hang-muc">
							<p>Kiểm tra Hormone nội tiết tố 6 hạng mục là phương pháp kiểm tra chủ yếu nhất trong việc kiểm tra chức năng sinh lý, mất cân bằng nội tiết tố. </p>
				<p>Thúc đẩy hormone nang trứng phát triển (FSH), thúc đẩy hormone hoàng thể phát triển (LH), Progesterone (F), Testosterone (T), Prolactin (PKL). </p>
			<div class="col-md-8">

				<div class="biaoge">
						<table align="left" border="0" cellspacing="0" width="700">
							<tbody>
								<tr class="kaka">
									<td bgcolor="#fff" rowspan="2" width="31"></td>
									<td align="middle" bgcolor="#006699" rowspan="2" valign="center" width="81">
										<span class="bai">Hạng mục</span></td>
									<td align="middle" bgcolor="#006699" colspan="2" valign="center">
										<span class="bai">Giá trị bình thường</span></td>
									<td align="middle" bgcolor="#006699" rowspan="2" valign="center" width="52">
										<span class="bai">Đơn vị</span></td>
									<td align="middle" bgcolor="#006699" rowspan="2" valign="center" style="    width: 152px;">
										<span class="bai">Ý nghĩa kiểm tra</span></td>
								</tr>
								<tr>
									<td align="middle" bgcolor="#a6004e" valign="center" >
										<span class="bai1">Nữ giới</span></td>
									<td align="middle" bgcolor="#007470" valign="center" style="     width: 108px;">
										<span class="bai1">Nam giới</span></td>
								</tr>
								<tr>
									<td align="middle" class="lv" height="64" valign="center" width="31">
										1</td>
									<td align="middle" class="hun" height="64" valign="center" width="81">
										Thúc đẩy hormone nang trứng (FSH)
										</td>
									<td align="left" class="hong" height="64" valign="center" width="176">
										Giai đoạn thể nang: 2.8-10.1
Đỉnh rụng trứng: 3.7-18.2
Giai đoạn hoàng thể: 1.2-9.7
Giai đoạn mãn kinh: 14.6-96.6
Giai đoạn mãn kinh (ERT): 7.1-70.4
</td>
									<td align="middle" class="lan" height="64" valign="center" width="57">
										1.5-12.0</td>
									<td align="middle" class="hun" height="64" valign="center" width="52">
										lU/l</td>
									<td align="left" class="last" height="64" valign="center" width="239">
										FSH và LH liên quan mật thiết đến sự kiểm soát hoạt tính sinh sản và sinh trưởng của tổ chức tuyến sinh sản</td>
								</tr>
								<tr>
									<td align="middle" class="lv" valign="center">
										2</td>
									<td align="middle" class="hun" valign="center" width="81">
										Thúc đẩy hormone Luteinizing(LH)
										</td>
									<td align="left" class="hong" valign="center">
										Giai đoạn thể nang: 1.0-10
Đỉnh rụng trứng: 15-70
Giai đoạn hoàng thể: 0.1-13.2
Thời kỳ kinh nguyệt: 0.1-11
Giai đoạn mãn kinh: 12.8-47
</td>
									<td align="middle" class="lan" valign="center">
										0.7-7.0</td>
									<td align="middle" class="hun" valign="center">
										mlU/ml</td>
									<td align="left" class="last" valign="center">
										LH dùng để quyết định thời gian mãn kinh, thời gian rụng trứng và giám sát quá trình điều trị nội tiết tố.</td>
								</tr>
								<tr>
									<td align="middle" class="lv" valign="center">
										3</td>
									<td align="middle" class="hun" valign="center" width="81">
										Progesterone (P)</td>
									<td align="left" class="hong" valign="center">
										Giai đoạn thể nang: 0.1-1.8
Giai đoạn hoàng thể: 1.7-31
Giai đoạn mãn kinh: 0.1-0.8
Đỉnh rụng trứng: 1.7-31
</td>
									<td align="middle" class="lan" valign="center">
										0.1-2.0</td>
									<td align="middle" class="hun" valign="center">
										ng/ml</td>
									<td align="left" class="last" valign="center">
										P do dịch hoàng thể buồng trứng, chẩn đoán chức năng hoàng thể không đầy đủ, xuất huyết tử cung do chức năng rụng trứng mất cân bằng, mang thai ngoài tử cung... </td>
								</tr>
								<tr>
									<td align="middle" class="lv" valign="center">
										4</td>
									<td align="middle" class="hun" valign="center" width="81">

										Estradiol (E2)</td>
									<td align="left" class="hong" valign="center">
										Giai đoạn thể nang: 0-88
Đỉnh rụng trứng: 18-500
Giai đoạn hoàng thể: 15-135
Giai đoạn mãn kinh: 0-55
</td>
									<td align="middle" class="lan" valign="center">
										0-60.3</td>
									<td align="middle" class="hun" valign="center">
										pg/ml</td>
									<td align="left" class="last" valign="center">
										Kiểm tra E2 trong máu ,trong nước tiểu nhằm chẩn đoán dậy thì sớm, chậm phát triển, đóng vai trò quan trọng trong việc chẩn đoán và phát hiện những bệnh lý về phụ khoa. </td>
								</tr>
								<tr>
									<td align="middle" class="lv" valign="center">
										5</td>
									<td align="middle" class="hun" valign="center" width="81">
										Thúc đẩy Hormone Prolactin (PRL)</td>
									<td align="left" class="hong" valign="center" style="    text-align: -webkit-center;">
										41-600</td>
									<td align="middle" class="lan" valign="center">
										29-580</td>
									<td align="middle" class="hun" valign="center">
										mIU/L</td>
									<td align="left" class="last" valign="center">
										Kiểm tra PRL hỗ trợ chẩn đoán hypothalamus - rối loạn chức năng tuyến yên. </td>
								</tr>
								<tr>
									<td align="middle" class="lv" valign="center">
										6</td>
									<td align="middle" valign="center" width="81">
										<span class="hun">Testosterone (T)</span></td>
									<td align="left" class="hong" valign="center">
										Giai đoạn vị thành niên: 0.01-0.43
Giai đoạn thành niên: 0.1-1.9
</td>
									<td align="middle" class="lan" valign="center">
										Giai đoạn vị thành niên: 0.01-0.43 
Giai đoạn thành niên: 2.0-8.5
</td>
									<td align="middle" class="hun" valign="center">
										ng/ml</td>
									<td align="left" class="last" valign="center">
										T tiết ra từ tinh hoàn nam hay buồng trứng nữ, chẩn đoán không có tinh hoàn, liệt dương, mãn kinh, rậm lông, rụng tóc...</td>
								</tr>

							</tbody>

						</table>
						<div style="clear: both"></div>
							<div style="width:700px;border: solid 2px #cecece; border-top:0">
								<a href="<?= link_tuvan;?>" rel="nofollow" target="_blank">
								<img height="45" src="images/tu-van-ngay.png" width="696"></a>
							</div>
						</div>

			</div>
			<div class="col-md-4">
			<a href="<?= link_tuvan;?>">
				<img src="images/kiem-tra-toan-dien.png" height="699" width="283"> </a>
			</div>

			</div>
	</div>
	<div class="hang-muc-bat-thuong" style="background:#d4e8f8;    padding-bottom: 15px;padding-top:12px;margin-top:15px;">
		<div class="container" style="padding-left:18px;">
			<div class="row hang-muc-la-gi" style="margin-right:26px;    margin-bottom: 20px;    position: relative;">
				<p style="color:#09678e;    font-weight: 600;font-size:17px">HORMONE NỘI TIẾT TỐ 6 HẠNG MỤC HORMONE BẤT THƯỜNG PHẢI LÀM THẾ NÀO?</p>
				<p style="color:#8e8e8e;">SIX HORMONES ABNORMALITIES HOW TO DO?</p>
				<a  href="<?= link_tuvan;?>"><img style="    right: 0px;
    margin-top: -10px;" src="images/click-tu-van-1.png" height="49" width="113"></a>
				
			</div>
			<div class="row">
				<div class="col-md-6" style="    padding-right: 81px;">
					<p class="xanh-t">Lựa chọn phòng khám “chuyên nghiệp chính quy” </p>
					<p style="    line-height: 29px;    padding-bottom: 2px;">Trên phương diện lâm sàng ,những người kiểm tra Hormone nội tiết tố 6 hạng mục về cơ bản để xác định rõ các bệnh như: mất cân bằng nội tiết tố, không rụng trứng, rụng trứng không tốt, mất cân bằng hormone, tinh trùng ít, tinh trùng yếu... Đối với những bệnh nhân vô sinh mà nói, khi kết quả kiểm tra bất thường cần lựa chọn phòng khám tốt để được tiến hành điều trị đúng. </p>
					<img src="images/1.png" height="187" width="403">
				</div>
				<div class="col-md-6">
					<p class="xanh-t">Tìm nguyên nhân bệnh, điều trị đúng bệnh </p>
					<p>Kiểm tra Hormone nội tiết tố 6 hạng mục tìm 3 bệnh bất thường, kiểm tra rõ nguyên nhân bệnh, điều trị đúng. </p>
					<div class="row benh-123">
						<div class="col-md-7 benh-t">
							<p class="xanh">Bệnh 1</p>
							<p>Vô sinh, rối loạn nội tiết tố </p>
						</div>
						<div class="col-md-7 benh-t">
							<p class="xanh">Bệnh 2</p>
							<p>Hội chứng đa nang buồng trứng, rụng trứng bất thường, không rụng trứng </p>
						</div>
						<div class="col-md-7 benh-t">
							<p class="xanh">Bệnh 3</p>
							<p>Không tinh trùng, tinh dịch bất thường, tinh trùng yếu, tinh trùng ít </p>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

	<div class="tinh-trang" style="padding-top:12px;    padding-bottom: 20px;">
		<div class="container">
			<div class="row hang-muc-la-gi" style="margin-right:26px;    margin-bottom: 20px;    position: relative;">
				<p style="color:#09678e;    font-weight: 600;font-size:17px">Tình trạng của bạn có cần phải kiểm tra Hormone nội tiết tố 6 hạng mục không? </p>
				<p style="color:#8e8e8e;">IN YOUR CASE DO HORMONES SIX TESTS?</p>
				<a  href="<?= link_tuvan;?>"><img style="    right: 0px;    margin-top: -10px;" src="images/click-tu-van-1.png" height="49" width="113"></a>
				
			</div>
			<div class="row tinh-trang-noi-dung">
				<div class="col-md-8" style="float:right;    width: 708px;">
					<p>Bác sỹ nhắc nhở: nam nữ muốn sinh đẻ, cần coi trọng việc kiểm tra Hormone nội tiết tố 6 hạng mục. Đặc biệt là nữ giới kinh nguyệt không đều và nam giới liệt dương xuất tinh sớm. Nên đến các phòng khám chuyên khoa chính quy để được kiểm tra và điều trị hiệu quả</p>
					<div class="row">
						<div class="col-md-3 t1">
							<p>Những trường hợp như kinh nguyệt thưa, tắc<br> kinh, kinh nguyệt <br>không đều, kết hôn <br>sau 1 năm chưa<br> có thai...</p>
						</div>
						<div class="col-md-3 t2">
							<p>Những trường hợp có <br>nhiều bệnh nặng hoặc<br> bị các bệnh như: béo<br> phì, rậm lông, mụn<br> trứng cá...</p>
						</div>
						<div class="col-md-3 t3">
							<p>Những người có cuộc <br>sống quan hệ vợ <br>chồng không hòa <br>hợp, bị lãnh cảm...</p>
						</div>
						<div class="col-md-3 t4">
							<p>Nam giới bị các bệnh<br> như yếu sinh lý, liệt<br> dương, xuất tinh<br> sớm, rối loạn<br> cương dương....</p>
						</div>																		
					</div>	
				</div>

			</div>
		</div>
	</div>

	<div class="kiem-tra-benh" style="min-height:300px;background:#d4e8f8;padding-top:15px;">
		<div class="container">
						<div class="row hang-muc-la-gi" style="margin-right:26px;    margin-bottom: 20px;    position: relative;">
				<p style="color:#09678e;    font-weight: 600;font-size:17px">Kiểm tra Hormone nội tiết tố 6 hạng mục cần chú ý những gì? </p>
				<p style="color:#8e8e8e;">SIX HORMONES CHECK WHAT PRECAUTIONS?</p>
				<a  href="<?= link_tuvan;?>"><img style="    right: 0px;    margin-top: -10px;" src="images/click-tu-van-1.png" height="49" width="113"></a>
				
			</div>
			<div class="row ">
				<div class="col-md-6" style="    width: 55%;  text-align: justify;">
					<div class="row tt-1">
						<div class="col-md-4">
							<p class="phuong-phap-1">1.Phương pháp kiểm tra <b class="hai-cham">:</b></p>
						</div>
						<div class="col-md-8">
						<p>lấy máu xét nghiệm, kiểm tra huyết thanh; </p>
						</div>
					</div>
					<div class="row tt-1">
						<div class="col-md-4">
							<p class="phuong-phap-1">2.Thời gian kiểm tra <b class="hai-cham">:</b></p>
						</div>
						<div class="col-md-8">
						<p>thời gian kiểm tra tốt là ngày thứ 3-5 sau khi sạch kinh. Khi kiểm tra cần chú ý 4 giai đoạn: giai đoạn nang trứng, giai đoạn rụng trứng, giai đoạn hoàng thể, giai đoạn tắc kinh. Do giai đoạn khác nhau, giá trị bình thường không giống với các chị em tắc kinh, bất kỳ thời gian nào đều có thể. Các bạn nam giới, bất cứ lúc nào đều có thể. </p>
						</div>
					</div>
					<div class="row tt-1">
						<div class="col-md-4">
							<p class="phuong-phap-1">3.Kiểm tra khoang bụng <b class="hai-cham">:</b> </p>
						</div>
						<div class="col-md-8">
						<p>kết quả kiểm tra chính xác. </p>
						</div>
					</div>
					<div class="row tt-1">
						<div class="col-md-4">
							<p class="phuong-phap-1">4.Thận trọng dùng thuốc <b class="hai-cham">:</b></p>
						</div>
						<div class="col-md-8">
						<p>trước khi kiểm tra cần tránh dùng các loại thuốc có ảnh hưởng đến hormone, tránh cho kết quả sai. </p>
						</div>
					</div>					
				</div>
				<div class="col-md-6" style="    text-align: right; width: 42%; float: right;">
				<a href="<?= link_tuvan;?>">
					<img src="images/click-tu-van-3.png" height="289" width="403"></a>
				</div>
			</div>
			<div class="row">
				<p class="t-kaka">Những điều cần biết về kiểm tra Hormone nội tiết tố 6 hạng mục của phòng khám đa khoa Giải Phóng Hà Nội</p>
			</div>
		</div>
		<a class="click-t" href="<?= link_tuvan;?>">
		<div class="container dang-ky-kham" style="text-align:center">
		<a class="click-t" href="<?= link_tuvan;?>">
			<img src="images/9.png" height="60" width="879">
			<div class="row t-tete">
				<p>
					Đăng ký tại phòng khám
				</p>
				<p>Đăng ký qua mạng</p>
				<p>Chi phí</p>
				<p style="    padding-left: 30px;">Chuyên nghiệp</p>
				<p style="    padding-left: 30px;">Miễn phí</p>

			</div>
			<div class="row t-tete-1">
				<p>
					Thuận tiện<br> tiết kiệm thời gian
				</p>
				<p>Khám ưu tiên <br>hưởng ưu đãi</p>
				<p>Đều thông qua các ban ngành<br> liên quan giám sát, phê duyệt</p>
				<p style="    padding-left: 30px;">Miễn phí đăng ký<br> tiết kiệm chi phí </p>
				<p style="    padding-left: 22px;">Phân tích kết quả và hướng<br> dẫn chuẩn bị mang thai </p>

			</div>		</a>	
		</div>
		
		
	</div>
	<div class="container" style="padding-left:18px;padding-right:28px;padding-top:10px;position: relative; ">
		<div class="row hang-muc-la-gi">
			<p style="color:#09678e;    font-weight: 600;font-size:17px">Kiểm tra Hormone nội tiết tố 6 hạng mục cần chú ý những gì? </p>
			<p style="color:#8e8e8e;">SIX HORMONES CHECK WHAT PRECAUTIONS?</p>
			<a href="<?= link_tuvan;?>"><img  src="images/click-tu-van-1.png" height="49" width="113"></a>
			
		</div>
	</div>	
	<div class="container">	
<div class="row content-bong">
        <div class="main_item main_item2" style="padding-top:16px;		padding-bottom:9px;">
            <div class="row">
                <div class="col-sm-4">
                    <div class="img">
                        <img src="images/tn1.jpg">
                        <p>Chỉ kiểm tra những hạng mục phù hợp với bệnh tình của bạn, bác sỹ chuyên khoa phụ khoa sẽ đưa ra những hạng mục kiểm tra, tính toán chi tiết giúp bạn tiết kiệm chi phí có thể.</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="img">
                        <img src="images/tn2.jpg">
                        <p>      Tất cả các mục kiểm tra đều áp dụng thiết bị kỹ thuật khoa học, độ chính xác cao, trong thời gian gần đây nếu đã đi kiểm tra và có kết quả thì phòng khám sẽ không cần kiểm tra lại lần 2, không để cho người bệnh mất đi mất lại nhiều loại chi phí.</p>
                    </div>
                </div>
                <div class="col-sm-4"  style="margin:0">
                    <div class="img">
                        <img src="images/tn3.jpg">
                        <p>
                            phòng khám đa khoa Giải Phóng Hà Nội sử dụng thiết bị y tế tiên tiến, kỹ thuật hiện đại giúp người bệnh yên tâm, kiểm tra chính xác không sai sót.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
	</div>	
	<div class="container" style="padding-left:18px;padding-right:28px;padding-bottom: 6px;position: relative;">
		<div class="row hang-muc-la-gi" style="    background: none;">
		
		</div>
	</div>
	<div class="container">
		<div class="row content-bong">
        <div class="main_item main_item3">
            <div class="row">
                <div class="col-sm-4">
                    <div class="item3_1">
                        <p>Kỹ thuật chuẩn trị hiện đại<br>
                        đạt tiêu chuẩn cao</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="item3_2">
                        <p>Đảm bảo hơn về độ an toàn<br>
                            và hiệu quả điều trị</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="item3_3">
                        <a href="<?= link_tuvan;?>"> <p style="text-transform: uppercase">click<br>
                            xem chi tiết</p></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
	</div>	
	<div class="footer" style="">
		<div class="container">
		<div class="row" style="background:none">
		 
			<div class="col-md-6" style="padding-top:50px">
			 <img style="margin:0 auto;" alt="" src="http://khamnamkhoahanoi.vn/cd6/chinh-hinh/cat-bao-quy-dau/images/logo-1.png">
			</div>
			<div class="col-md-6 row-son-tuvan" style="padding-left:65px;">
			<p><a href="<?= link_tuvan;?>" target="_blank">
				<img style="margin:0 auto;" alt="" src="images/tv-1.png">  </a>
			</p>
						<p> <a href="<?= link_tuvan;?>" target="_blank">
				<img style="margin:0 auto;" alt="" src="images/tv-2.png">  </a>
			</p>

						<p><a href="<?= link_skype;?>" target="_blank">
				<img style="margin:0 auto;" alt="" src="images/tv-3.png">  </a>
			</p>
			<p><a href="<?= domain;?>" target="_blank">
				<img style="margin:0 auto ;" alt="" src="images/tv-4.png"> </a>
			</p>
			<div class="row" style="clear:both;background:none">
				<h3 style="    font-style: italic;font-weight:600"> <?= phone1;?> - <?= phone2;?></h3>
				<p>Địa chỉ: SỐ 709 - GIẢI PHÓNG - HOÀNG MAI - HÀ NỘI</p>
				<p>Ðiện thoại: <?= phone1;?> - <?= phone2;?></p>
			</div>
			</div>
		</div>
		</div>
</div>
</body>
</html>
<?= popup();?>
<?= Addleft();?>
<?= line_chat();?>
<script type="text/javascript" language="JavaScript">
    $(document).ready(function () {
        $("#banner-close").click(function () {
            $(".banner-son").hide();
        });
    });
	</script>

