<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Thủ thuật trĩ</title>
    <meta content="" name="Keywords" />
    <meta content="" name="Description"/>
    <script type='text/javascript' src="js/jquery-1.4.4.min.js"></script>
    <script src="js/gg.js" type="text/javascript"></script>
    <script src="js/MSClass.js" type="text/javascript"></script>
    <base target="_blank">
</head>
<!--[if IE 6]>
<script>
    DD_belatedPNG.fix('.buttom_2,.buttom_zixun,.jaja_2,.rak_1,.z_1,a.rna1,a:hover.rna1,a.ran2,a:hover.rna2,a.rna3,a:hover.rna3,.ra1_1,.ra1_2,.rapng,.ra3_1,.ra3_dd ul li,.ra3_dd ul li.active,.ra5_2,.ra6_1,.ra7_1,.ra8_1,.ra2_1');
</script>
<![endif]-->
<body>
<?php
require_once('../../define.php');
$domain=domain;
$link_tuvan=link_tuvan;
$line_chat=line_chat();
$Addtop=Addtop();
?>
<?= $Addtop;?>
<?= cd_menu_top();?>
<link href="css/main.css" type="text/css" rel="stylesheet" />
<div class="right_box" id="mdtop">
    <div class="ra1">
        <div class="ra1_1"></div>
        <div class="ra1_2"></div>
    </div>
    <div class="ra2 rapng" id="mda1">
        <div class="ra2_1">
            <ul>
                <li class="ra2_1_text">Bạn bị  những khó chịu này ? 10 người có đến 9 người bị trĩ!</li>
                <li class="z_1">
                    <p>Rặn mạnh nhưng không thể đại tiện được; khi đi vệ sinh là cả bồn cầu có máu; đau đớn khó chịu, không thể ngồi lâu, không thể đi nhiều; khi sờ vào có cục mềm mềm, có dịch mùi hôi, thậm chí khi đại tiện, xì hơi, hắt hơi...đều trở thành “hoạt động mạnh”. Không sai, bạn đã bị bệnh trĩ.</p>
                </li>
            </ul>
        </div>
    </div>
    <div class="ra3 rapng">
        <div class="rak_1"></div>
        <div class="ra3_line1"></div>
        <div class="ra3_1"></div>
        <div class="ra3_dd">
            <ul id="a3hk_bot">
                <li>TRĨ NỘI</li>
                <li>TRĨ NGOẠI</li>
                <li>TRĨ HỖN HỢP</li>
            </ul>
        </div>
        <div class="ra3_2" id="a3_hk">
            <ul id="a3_hk_ul">
                <li> <span><img src="images/jaja_pic11.jpg"/></span>
                    <h3>Triệu chứng trĩ nội như sau：</h3>
                    <div>
                        <p>Độ 1: búi trĩ nhỏ mềm, thường khi đại tiện cọ sát búi trĩ mà chảy máu, không sa ra ngoài, không đau, sau đại tiện ngừng chảy máu.<br/>
                            Độ 2: búi trĩ dần to, mềm, búi trĩ có màu đỏ tươi hoặc tím nhạt.<br/>
                            Độ 3: đại tiện ra máu giảm, kèm theo cảm giác trướng tức hậu môn. Búi trĩ to hơn, khi mệt mỏi hoặc áp lực ở bụng tăng thì trĩ nội sa ra ngoài, phải dùng tay mới co lại được.<br/>
                            Độ 4: sa ra không thể tự co lại được. Khi đi lại, hắt hơi hoặc đứng búi trĩ sẽ sa ra ngoài. Sau khi nằm ngửa, chườm nóng mới có thể co lại được.
                        </p>
                        <p class="img_b"></p>
                    </div>
                </li>
                <li> <span><img src="images/jaja_pic12.jpg"/></span>
                    <h3>Triệu chứng trĩ ngoại như sau: </h3>
                    <div>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Trĩ ngoại tổ chức mô liên hết - nếp gấp da viền hậu môn to lên, lỗ hậu môn xuất hiện đám thịt hình cầu có thể sờ thấy được.</p>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Trĩ ngoại huyết khối, đau dữ dội, cảm giác trướng tức rõ rệt, cạnh hậu môn có cục thịt trơn cứng, chạm vào rất đau.</p>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Trĩ ngoại viêm nhiễm, viêm nhiễm làm cho nếp gấp viêm nhiễm phù nề, khi đại tiện hậu môn rất đau, chảy máu, có kèm theo ít dịch. </p>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Trĩ ngoại giãn tĩnh mạch, viền hậu môn hình thành vòng tròn, rặn mạnh khi đại tiện có thể nhìn thấy búi trĩ màu tím, sau khi đại tiện nghỉ ngơi mới có thể co nhỏ lại.</p>
                        <p style="text-indent:0;">
                            <a href="<?= $link_tuvan;?>" target="_blank" class="zx1">TƯ VẤN TRỰC TUYẾN</a>
                            <a href="<?= $link_tuvan;?>" target="_blank" class="zx1">ĐĂNG KÝ TRỰC TUYẾN</a>
                        </p>
                    </div>
                </li>
                <li> <span><img src="images/jaja_pic13.jpg"/></span>
                    <h3>Triệu chứng trĩ hỗn hợp như sau: </h3>
                    <div>
                        <p style="text-indent:2em; line-height:16px;">Trĩ ngoại + trĩ nội = trĩ hỗn hợp phải không? Cách hiểu này hoàn toàn sai lầm, trĩ hỗn hợp còn được gọi là trĩ ngoại bên trong, ở cùng vị trí trên dưới mép hậu môn, giãn tĩnh mạch hình thành khối vòng, bên trong ngoài liên tiếp, không rõ danh giới chinhslaf biểu hiện chính của bệnh này. Trĩ hỗn hợp thuộc một dạng nghiêm trọng trong bệnh trĩ. Triệu chứng của cả trĩ nội và trĩ ngoại, triệu chứng điển hình là ngứa, đau, đại tiện ra máu, búi trĩ sa ra ngoài...</p>
                        <p style="padding-top:9px;"><strong>1. Đại tiện ra máu:</strong> đa phần là do phân chà sát vào niêm mạc hoặc rặn mạnh khi đi ngoài gây ra giãn tĩnh mạch, rách tĩnh mạch.</p>
                        <p><strong>2. Búi trĩ sa ra:</strong> giai đoạn về sau búi trĩ to lên, dần dần tách khỏi cơ, khi đại tiện sa ra ngoài hậu môn. Người bị nặng cần phải dùng tay để đẩy vào.</p>
                        <p><strong>3. Ngứa:</strong> giai đoạn sau trĩ hỗn hợp sa ra và cơ hậu môn giãn lỏng, thường có dịch chảy ra, xung quanh hậu môn ngứa ẩm ướt</p>
                        <p><strong>4. Tràn dịch nhầy:</strong> niêm mạc trực tràng thời gian dài chịu kích thích của búi trĩ, gây ra viêm nhiễm, làm cho dịch tăng nhiều, xuất hiện tràn dịch nhầy. Sau khi nghỉ ngơi mới co lại.</p>
                        <p style="text-indent:0;">
                            <a href="<?= $link_tuvan;?>" target="_blank" class="zx1">TƯ VẤN TRỰC TUYẾN</a>
                            <a href="<?= $link_tuvan;?>" target="_blank" class="zx1">ĐĂNG KÝ TRỰC TUYẾN</a>
                        </p>
                    </div>
                </li>
            </ul>
        </div>
        <script type="text/javascript">
            new Marquee(
                    {
                        MSClassID : "a3_hk",
                        ContentID : "a3_hk_ul",
                        TabID	  : "a3hk_bot",
                        Direction : 2,
                        Step	  : 0.3,
                        Width	  : 915,
                        Height	  : 296,
                        Timer	  : 20,
                        DelayTime : 3000,
                        WaitTime  : 0,
                        ScrollStep: 915,
                        SwitchType: 0,
                        AutoStart : 1
                    })
        </script>
    </div>
    <div class="ra6 rapng" id="mda3">
        <div class="ra6_1">
            Phương pháp tốt cho bệnh trĩ, loại bỏ tận gốc chỉ cần 20 phút
        </div>
        <div class="ra6_2"></div>
        <div class="ra6_3" id="a6_hk">
            <ul id="a6_hk_ul">
                <li> <span><a href="<?= $link_tuvan;?>" target="_blank"><img src="images/cook.jpg"/></a></span>
                    <h3>Kỹ thuật thắt siêu xâm lấn tối thiểu COOK</h3>
                    <p>20 phút giải quyết bệnh trĩ “sát thủ” không để lại sẹo<br>
                        <font>Dụng cụ an toàn&nbsp;&nbsp;&nbsp;thủ thuật tiên tiến&nbsp;&nbsp;&nbsp;quá trình dễ chịu&nbsp;&nbsp;&nbsp;phục hồi nhanh</font><br>
                        <br>
                        Phạm vi điều trị: các giai đoạn trĩ nội (độ I đến độ III hiệu quả khá tốt), trĩ nội trĩ hỗn hợp, polyp trực tràng, u mạch máu hoặc dị dạng mạch máu...
                    </p>
                    <div class="aa1">ĐIỆN THOẠI TƯ VẤN：<b><?= phone1;?></b></div>
                    <a href="<?= $link_tuvan;?>" class="zx1" target="_blank">TƯ VẤN TRỰC TUYẾN</a>
                </li>
                <li> <span><a href="<?= $link_tuvan;?>" target="_blank"><img src="images/pph.jpg"/></a></span>
                    <h3>Kỹ thuật xâm lấn tối thiểu</h3>
                    <p>Điều trị cơ bản và chuyên sâu, loại bỏ tận gốc bệnh trĩ<br>
                        <font>An toàn ít đau&nbsp;&nbsp;&nbsp;Biến chứng thấp&nbsp;&nbsp;&nbsp;Thương tổn bề mặt nhỏ   &nbsp;&nbsp;&nbsp;Phạm vi chẩn trị rộng </font><br>
                        <br>
                        Phạm vi điều trị: trĩ nội, sa trực tràng, trĩ hỗn hợp, trĩ vòng, sa trĩ nghiêm trọng, sa hậu môn...
                    </p>
                    <div class="aa1">ĐIỆN THOẠI TƯ VẤN：<b><?= phone1;?></b></div>
                    <a href="<?= $link_tuvan;?>" class="zx1" target="_blank">TƯ VẤN TRỰC TUYẾN</a>
                </li>
                <li> <span><a href="<?= $link_tuvan;?>" target="_blank"><img src="images/hcpt.jpg"/></a></span>
                    <h3>Kỹ thuật xâm lấn tối thiểu thông minh HCPT</h3>
                    <p>Các loại máy trị bệnh trực tràng hậu môn, chuyên nghiệp đi đầu trong ngành <br>
                        <font>Xâm lấn tối thiểu an toàn &nbsp;&nbsp;&nbsp;Điều trị xong có thể ra về ngay &nbsp;&nbsp;&nbsp;Độ chính xác cao&nbsp;&nbsp;&nbsp;Biến chứng thấp</font><br>
                        <br>
                        Phạm vi điều trị: trĩ nội, trĩ ngoại, trĩ hỗn hợp, nứt kẽ hậu môn, rò hậu môn, sa hậu môn, áp xe hậu môn...
                    </p>
                    <div class="aa1">ĐIỆN THOẠI TƯ VẤN：<b><?= phone1;?></b></div>
                    <a href="<?= $link_tuvan;?>" class="zx1" target="_blank">TƯ VẤN TRỰC TUYẾN</a>
                </li>
            </ul>
        </div>
        <div class="ra6_4">
            <ul id="a6hk_bot">
                <li>COOK</li>
                <li style="margin:0 4px;">PPH</li>
                <li>HCPT</li>
            </ul>
        </div>
        <script type="text/javascript">
            new Marquee(
                    {
                        MSClassID : "a6_hk",
                        ContentID : "a6_hk_ul",
                        TabID	  : "a6hk_bot",
                        Direction : 1,
                        Step	  : 0.3,
                        Width	  : 913,
                        Height	  : 332,
                        Timer	  : 20,
                        DelayTime : 3000,
                        WaitTime  : 0,
                        ScrollStep: 332,
                        SwitchType: 0,
                        AutoStart : 1
                    })
        </script>
    </div>
    <div class="ra7 rapng">
        <div class="ra7_1">
        tại sao mắc bệnh trĩ? tại sao càng ngày càng nghiêm trọng?
        </div>
        <div class="jaja_2">
            <div style=" width:410px; height:443px; float:left;">
                <p style="text-indent:2em; line-height:18px; padding-top:320px; color:#bfcaca;">
                    Có rất nhiều bệnh nhân khi đối mặt với bệnh trực tràng hậu môn như bệnh trĩ, không lựa chọn điều trị tích cực mà lựa chọn “chịu đựng” . Chỉ cần tạm thời khống chế được triệu chứng, thì có thể kéo dài qua được. Bệnh nhỏ biến thành bệnh lớn, không cần thủ thuật biến thành cần làm thủ thuật, không chỉ tăng độ khó cho việc điều trị mà còn tăng sự đau đớn và chi phí trong việc điều trị. Bác sỹ trực tràng hậu môn cho biết: người bệnh sợ phiền, sợ đau, là những điều thường gặp; do chịu đựng dẫn đến thắt nút cần phải làm thủ thuật. (trĩ kéo dài không điều trị, có hậu quả nghiêm trọng không? )
                </p>
            </div>
            <div style=" width:505px; height:443px; float:left; line-height:18px;">
                <p style=" padding-left:30px; color:#bfcaca; padding-top:125px; text-indent:2em;">Theo sự giới thiệu của bác sỹ, thời gian đại tiện càng lâu có thể khiến cho áp lực vùng bụng tăng cao, hậu môn trực tràng sung huyết, thậm chí có thể dẫn đến niêm mạc trực tràng và vùng cơ tách ra sa ra ngoài, ống hậu môn di chuyển theo phân, lâu dần dễ dẫn đến bệnh trĩ.</p>
                <p style=" padding-left:30px; color:#bfcaca; padding-top:45px;  text-indent:2em;">Theo lời của bác sỹ, trĩ và thực ẩm có liên quan mật thiết, thực phẩm mặc dù chưa chắc là nguyên nhân trực tiếp dẫn đến bệnh trĩ, nhưng đối với bệnh trĩ có vai trò nhất định.</p>
                <p style=" padding-left:30px; color:#bfcaca; padding-top:45px;  text-indent:2em;">Công việc xã hội hiện đại đa phần là đứng hoặc ngồi, đặc biệt là dân văn phòng và giáo viên... Thường ngồi hoặc đứng cả ngày, thiếu vận động là sẽ mắc bệnh. Đây là sự báo trước của các bệnh về trực tràng hậu môn như bệnh trĩ. Theo bác sỹ giải thích: ngồi nhiều làm cho huyết mạch không thông, huyết mạch không thông gây ra ức huyết, chảy về hậu môn mà sinh ra bệnh trĩ; đứng lâu cũng có thể dẫn tới bệnh trĩ, đây là nhóm người có khả năng mắc bệnh trĩ cao.</p>
            </div>
        </div>
    </div>
    <style>
        .buttom_zixun a{
            color: #ffffff;
            padding-top: 15px;
            text-indent: 50px;
            text-decoration: none;
        }
    </style>
    <div class="ra8 rapng" id="mdbottom">
        <div class="buttom_zixun">
            <a href="<?= $link_tuvan;?>" class="j_1"><b>Tư vấn trực tiếp bác sỹ</b><p>hỏi ngay, trả lời luôn</p></a>
            <a href="<?= $link_tuvan;?>" class="j_2"><b>Đăng ký trực tuyến</b><p>Miễn phí đăng ký</p><p>Nhanh chóng khám bệnh</p></a>
           <a href="<?= $link_tuvan;?>" class="j_3"><b>Miễn phí tư vấn điện thoại</b><p><?= phone1;?></p></a>
            <a href="<?= $link_tuvan;?>" class="j_4"><b>Tư vấn trực tiếp skype</b><p>nhanh chóng thuận tiện</p><p>bảo mật riêng tư</p></a>
        </div>
        <div class="buttom_2">
            <div style="float: left;padding-top: 30px;padding-right: 20px;">
                <img src="images/logo_f.png" alt="">
            </div>
            <div style="float: left;border-left: 1px solid #ffffff;color: #ffffff">
                <p style="padding-left:25px; padding-top:6px; line-height:24px; color:#fff;">SỐ 709 - GIẢI PHÓNG - HOÀNG MAI - HÀ NỘI<br/>
                    Điện thoại tư vấn: <b><?= phone1;?> - <?= phone2;?></b> (phòng khám không ngày nghỉ)<br/>
                    Sở hữu bản quyền: Copyright 2010 - 2016 Phong Kham Da Khoa Giai Phong Ha Noi.<br>
                    All rights reverved.
                </p>
            </div>
        </div>
    </div>
</div>
</body>
<?= $line_chat;?>
</html>