<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title> Mobie giải phóng </title>
	<link rel="stylesheet" href="css/style.css">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="pages">
		 <header class="header">
		 	  <div class="container">
		 	  	 <div class="row row1">
		 	  	 	 <div class="col-xs-9">
		 	  	 	 	 <div class="m_logo">
		 	  	 	 	 	 <img class="img-responsive" src="images/m_logo.png" alt="">
		 	  	 	 	 </div>
		 	  	 	 </div>
		 	  	 	 <div class="col-xs-3">
		 	  	 	 	 <div class="m_logo_2">
		 	  	 	 	 	  <img src="images/m_logo_2.png" alt="">
		 	  	 	 	 </div>
		 	  	 	 </div>
		 	  	 </div>
		 	  </div>
		 </header> <!-- end header -->
		 <div class="menu">
		 	<div class="container">
		 		 <div class="row">
		 		 	 <div class="sub_menu_con">
		 		 	 	 <ul>
		 		 	 	 	 <li>
		 		 	 	 	 	<a href="">  Trang chủ </a>
		 		 	 	 	 </li>
		 		 	 	 	 <li>
		 		 	 	 	 	<a href=""> Giới thiệu </a>
		 		 	 	 	 </li>
		 		 	 	 	 <li>
		 		 	 	 	 	<a href=""> Kỹ thuật </a>
		 		 	 	 	 </li>
		 		 	 	 	 <li>
		 		 	 	 	 	<a href=""> Bác sỹ  </a>
		 		 	 	 	 </li>
		 		 	 	 	 <li>
		 		 	 	 	 	<a href=""> Liên hệ </a>
		 		 	 	 	 </li>
		 		 	 	 </ul>
		 		 	 </div>
		 		 </div>
		 	</div>
		 </div> <!-- end menu  -->
		 <div class="baner">
		 	 <div class="container">
		 	 	 <div class="row">
		 	 	 	 <img class="img-responsive" src="images/banner_mobile.png" alt="">
		 	 	 </div>
		 	 </div>
		 </div>
		 <div class="home1_m">
		 	 <div class="container">
		 	 	 <div class="row">
		 	 	 	 <div class="bg_loidan">
		 	 	 	 	 <div class="col-xs-4">
		 	 	 	 	 	  
		 	 	 	 	 </div>
		 	 	 	 	 <div class="col-xs-8" style="padding-right: 0px;">
		 	 	 	 	 	<div class="loidan">
		 	 	 	 	 		 Với phương châm đặt sức khỏe của bệnh nhân lên hàng đầu và nhằm giảm bớt gánh nặng cho người bệnh, phòng khám đa khoa Giải Phóng  triển khai chương trình ưu đãi mừng xuân mới. Dành riêng cho những bệnh nhân có đặt hẹn trước với nhiều hạng mục hấp dẫn.
		 	 	 	 	 	</div>
		 	 	 	 	 </div>
		 	 	 	 </div>
		 	 	 </div>
		 	 	 <div class="row text-center rowcol2">
		 	 	 	<div class="tt_m_hom1"> Những hạng mục ưu tiên miễn phí </div>
		 	 	 	<img style="margin-top: 20px;" class="img-responsive" src="images/img_home2.png" alt="">
		 	 	 </div>
		 	 </div>
		 </div> <!-- end home1-->
		 <div class="home2_m">
		 	 <div class="container">
		 	 	 <div class="row text-center">
		 	 	 	 <img class="img-responsive" src="http://phongkhamgiaiphong.com/bxh/cdsuckhoe/chuyen-de-suc-khoe/images/30_kt.png" alt="">
		 	 	 	 <div class="text_home2_m">
		 	 	 	 	Chúng tôi có thiết bị và môi trường thủ thuật <br> mà những nơi khác không thể so sánh 
		 	 	 	 </div>
		 	 	 </div>
		 	 	 <div class="row">
		 	 	 	 <div class="khoitrang">
		 	 	 	 	  <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/anh1_home2.jpg" alt="">
		 	 	 	 	  <div class="text-khoitrang">
		 	 	 	 	  	 Khâu kiểm tra bệnh tại phòng khám được thực hiện theo đúng trình tự, gồm khâu kiểm tra lâm sàng đến làm xét nghiệm, điển hình như xét nghiệm máu, xét nghiệm nước tiểu, xét nghiệm mẫu vật...cùng nhiều xét nghiệm chuyên môn khác. Qúa trình kiểm tra được thực hiện trực tiếp bởi các bác sỹ đầu ngành, áp dụng máy móc kỹ thuật tân tiến, cho phép chẩn đoán bệnh chính xác trong thời gian ngắn nhất
		 	 	 	 	  </div>
		 	 	 	 </div>
		 	 	 </div>
		 	 	 <div class="row text-center">
		 	 	 	<button class="btn btn-danger nuttv"> Tư vấn trực tuyến </button>
		 	 	 </div>
		 	 	  <div class="row" style="margin-top: 20px;">
		 	 	 	 <div class="khoitrang">
		 	 	 	 	  <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/anh2_home2.jpg" alt="">
		 	 	 	 	  <div class="text-khoitrang">
		 	 	 	 	  	Vì sự an toàn của bạn, hi vọng mọi người nâng cao cảnh giác, lựa chọn cẩn thận! Không nên tin tưởng các phòng khám tư nhân nhỏ lẻ và không chính quy, khi làm thủ thuật nhất định phải lựa chọn phòng khám chính quy, có chất lượng, quy mô lớn...
		 	 	 	 	  </div>
		 	 	 	 </div>
		 	 	 </div>
		 	 	 <div class="row text-center">
		 	 	 	<button class="btn btn-danger nuttv"> Tư vấn trực tuyến </button>
		 	 	 </div>
		 	 </div>
		 </div> <!-- end home 2 mobie -->
		 <div class="home3_mobie">
		 	<div class="container">
		 		 <div class="row text-center">
		 		 	   <img class="img-responsive" src="http://phongkhamgiaiphong.com/tmh/cdsuckhoe/chuyen-de-suc-khoe/images/30_tt.png" alt="">
		 		 </div>
		 		 <div class="row">
		 		 	 <div class="khoitrang">
		 	 	 	 	  <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/bs_home4.jpg" alt="">
		 	 	 	 	  <div class="text-khoitrang">
		 	 	 	 	  	Sau chặng đường nhiều năm phát triển,phòng khám đa khoa Giải Phóng đã khẳng định được vị thế trong lĩnh vực chăm sóc sức khỏe, với phương châm đặt sức khỏe của bệnh nhân lên hàng đầu và nhằm giảm bớt gánh nặng cho người bệnh, phòng khám triển khai chương trình ưu đãi mừng xuân mới. Dành riêng cho những bệnh nhân có đặt hẹn trước với nhiều hạng mục hấp dẫn.
		 	 	 	 	  </div>
		 	 	 	 </div>
		 		 </div>
		 		  <div class="row text-center">
		 	 	 	<button class="btn btn-danger nuttv tv_hai"> 
                         <span class="img_tab3">
                    <img class="img_tab3" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/phonetv.png" alt="">
                  </span>
                  <span class="tv_mienphi">
                      Tư vấn miễn phí trực tuyến 
                  </span>
		 	 	 	</button>
		 	 	 </div>
		 	</div>
		 </div>
		 <div class="home3_mobie h3hai">
		 	<div class="container">
		 		 <div class="row text-center">
		 		 	   <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/dt.png" alt="">
		 		 </div>
		 		 <div class="row">
		 		 	 <div class="khoitrang">
		 	 	 	 	  <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/bs_hom4.png" alt="">
		 	 	 	 	  <div class="text-khoitrang">
		 	 	 	 	  	Sau chặng đường nhiều năm phát triển,phòng khám đa khoa Giải Phóng đã khẳng định được vị thế trong lĩnh vực chăm sóc sức khỏe, với phương châm đặt sức khỏe của bệnh nhân lên hàng đầu và nhằm giảm bớt gánh nặng cho người bệnh, phòng khám triển khai chương trình ưu đãi mừng xuân mới. Dành riêng cho những bệnh nhân có đặt hẹn trước với nhiều hạng mục hấp dẫn.
		 	 	 	 	  </div>
		 	 	 	 </div>
		 		 </div>
		 		  <div class="row text-center">
		 	 	 	<button class="btn btn-danger nuttv tv_hai"> 
                         <span class="img_tab3">
                    <img class="img_tab3" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/phonetv.png" alt="">
                  </span>
                  <span class="tv_mienphi">
                      Tư vấn miễn phí trực tuyến 
                  </span>
		 	 	 	</button>
		 	 	 </div>
		 	</div>
		 </div>
		 <div class="home4_mobie">
		 	<div class="container">
		 		<div class="row text-center">
		 			 <div class="tt_home4"> Phòng khám chuyên nghiệp </div>
		 			 <div class="des_home4">Chúng tôi luôn cố gắng nỗ lực để có thể phục vụ bệnh nhân tốt nhất</div>
		 		</div>
		 		<div class="row text-center" style="margin-top: 30px;">
		 			 <div class="col-xs-6">
		 			 	 <div class="baonentrang">
		 			 	 	 <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/cn1_home5.png" alt="">
		 			 	 	 <div class="tt_nentrang"> 	Phòng khám đa khoa  <br> chuyên nghiệp </div>
		 			 	 	 <div class="des_nentang">Chuyên điều trị các bệnh, bảo vệ sức khỏe bản thân</div>
		 			 	 </div>
		 			 </div>
		 			 <div class="col-xs-6">
		 			 	 <div class="baonentrang">
		 			 	 	 <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/cn2_home5.png" alt="">
		 			 	 	 <div class="tt_nentrang"> 	Đội ngũ y tế  <br> lớn mạnh </div>
		 			 	 	 <div class="des_nentang">Tập hợp các bác sỹ nổi tiếng trong và ngoài nước, đội ngũ y bác sỹ hùng hậu</div>
		 			 	 </div>
		 			 </div>
		 		</div>
		 		<div class="row text-center" style="margin-top: 30px;">
		 			 <div class="col-xs-6">
		 			 	 <div class="baonentrang">
		 			 	 	 <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/cn3_home5.png" alt="">
		 			 	 	 <div class="tt_nentrang"> 	Kỹ thuật chẩn trị  <br> tiên tiến toàn diện </div>
		 			 	 	 <div class="des_nentang">Nhập khẩu các loại kỹ thuật chẩn trị, nâng cao hiệu quả điều trị bệnh</div>
		 			 	 </div>
		 			 </div>
		 			 <div class="col-xs-6">
		 			 	 <div class="baonentrang">
		 			 	 	 <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/cn4_home5.png" alt="">
		 			 	 	 <div class="tt_nentrang"> 	Đến thăm khám  <br> là được hưởng ưu đãi </div>
		 			 	 	 <div class="des_nentang">Người bệnh đến khám sẽ được hưởng ưu đãi, tiết kiệm chi phí </div>
		 			 	 </div>
		 			 </div>
		 		</div>
		 	</div>
		 </div> <!-- end home 4 -->
		 <div class="home5_mobie">
		 	<div class="container">
		 		<div class="row text-center">
		 			<div class="tt_home5"> Thăm khám bệnh lưu ý lựa chọn <br> phòng khám chuyên nghiệp</div>
		 			<div class="des_home5">
		 			Phòng khám đa khoa Giải Phóng với trang thiết bị hiện đại, kỹ thuật tiên tiến, điều trị hiệu quả cao, chi phí thấp</div>
		 			<div class="des_home5_hai"> 
		 			Không phải phòng khám nào cũng có thể áp dụng kỹ thuật xâm lấn tối thiểu Chỉ có những phòng khám chuyên nghiệp, toàn diện, cơ cấu trang thiết bị và năng lực về y tế chính quy toàn diện mới có đủ tư cách áp dụng.
		 		   </div>
		 		   <img style="width: 100%;margin-top: 20px;" class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/img_home6.jpg" alt="">
		 		</div>
		 		<div class="row" style="margin-top: 30px;">
		 			<div class="col-xs-2" style="padding-left: 0px;">
		 				 <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/so1.png" alt="">
		 			</div>
		 			<div class="col-xs-10">
		 				<div class="baoquanhhet">
		 					<div class="tt_baoquanhhet"> Năng lực được công nhận </div>
		 					<div class="des_baoquanhhet"> Phòng khám đa khoa Giải Phóng với trang thiết bị hiện đại, kỹ thuật tiên tiến, điều trị hiệu quả cao, chi phí thấp</div>
		 				</div>
		 			</div>
		 		</div>
		 		<div class="row" style="margin-top: 30px;">
		 			<div class="col-xs-2" style="padding-left: 0px;">
		 				 <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/so2.png" alt="">
		 			</div>
		 			<div class="col-xs-10">
		 				<div class="baoquanhhet">
		 					<div class="tt_baoquanhhet"> Bảo đảm an toàn  </div>
		 					<div class="des_baoquanhhet"> - Môi trường được đảm bảo - phòng thủ thuật sạch sẽ vô khuẩn <br> - Bác sỹ được đảm bảo - với đội ngũ y bác sỹ có trên 20 năm <br> kinh nghiệm lâm sàng <br>- Kinh nghiệm được đảm bảo - với hàng ngàn ca thủ thuật không sự cố</div>
		 				</div>
		 			</div>
		 		</div>
		 		<div class="row" style="margin-top: 30px;">
		 			<div class="col-xs-2" style="padding-left: 0px;">
		 				 <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/so3.png" alt="">
		 			</div>
		 			<div class="col-xs-10">
		 				<div class="baoquanhhet">
		 					<div class="tt_baoquanhhet"> Năng lực được công nhận </div>
		 					<div class="des_baoquanhhet"> Nhằm đảm bảo thực hiện thủ thuật an toàn và hiệu quả cao, bác <br> sỹ thực hiện thủ thuật cần có: <br>
                              <div class="text_col10">
                              	 1. Bác sỹ có Trình độ thực hiện thủ thuật <br>
                              	 2. Bác sỹ thực hiện hàng ngàn ca thủ thuật không để <br>
                              	 xuất hiện sự cố <br>
                              	 3. Làm việc trong ngành y từ 20 năm trở lên <br>
                              </div>
		 					</div>
		 				</div>
		 			</div>
		 		</div>
		 		<div class="row" style="margin-top: 30px;">
		 			<div class="col-xs-2" style="padding-left: 0px;">
		 				 <img class="img-responsive" src="http://phongkhamgiaiphong.com/cdsuckhoe/chuyen-muc-suc-khoe/images/so4.png" alt="">
		 			</div>
		 			<div class="col-xs-10">
		 				<div class="baoquanhhet">
		 					<div class="tt_baoquanhhet"> Trang thiết bị hiện đại  </div>
		 					<div class="des_baoquanhhet"> Phòng khám đa khoa Giải Phóng, nhập khẩu trang thiết bị hiện đại, đảm bảo tính an toàn và hiệu quả điều trị</div>
		 				</div>
		 			</div>
		 		</div>
		 		<div class="row text-center">
		 	 	 	<button class="btn btn-danger nuttv"> Tư vấn trực tuyến </button>
		 	 	 </div>
		 	</div>
		 </div>
		 <div class="home6">
		 	<div class="container">
		 		<div class="row">
		 			 <img style="margin-top: 20px;" class="img-responsive" src="images/lienhe.png" alt="">
		 		</div>
		 		<div class="row">
		 			<img class="img-responsive" src="images/footer.png" alt="">
		 		</div>
		 	</div>
		 </div>
		 ,
	</div>
</body>
</html>