<!DOCTYPE html>
<html>
<head>
    <title>Lộ trình khám</title>
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <base target="_blank"/>
</head>
<?php
require_once('../../define.php');
$domain=domain;
$link_tuvan=link_tuvan;
$link_gioithieu=link_gioithieu;
$link_thietbi=link_thietbi;
$link_skype=link_skype;
?>
<body>
<?= Addtop();?>
<?= Addleft();?>
<?= popup();?>
<div class="body-1">
    <div class="container">
        <div class="row" style="margin: auto;text-align: center;">
            <!--<div class="col-md-6" style="margin-top:10px;margin-bottom: 6px;">
                <img src="images/logo.png" height="69" width="395">
            </div>
            <div class="col-md-6" style="margin-top:30px;">
                <a style="float:right" href="<?/*= $link_tuvan;*/?>">
                    <img src="images/chuyen-gia-tu-van-1.png" height="27" width="101">
                </a>
                <a style="float:right;padding-right: 20px;" href="<?/*= $domain;*/?>">
                    <img src="images/trang-chu.png" height="27" width="101">
                </a>
            </div>-->
            <img src="http://chuabenhxahoi.net/images/banner_top.gif" alt="banner top">
        </div>
    </div>
</div>
<div class="body-1" style="background: #177fc8">
    <div class="container menu-top">
        <div class="row">
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="<?= $domain;?>">Trang chủ</a></li>
                    <li><a href="<?= $link_gioithieu;?>">Giới thiệu</a></li>
                    <li><a target="_blank" style="" href="<?= $link_thietbi;?>">Thiết bị</a></li>
                    <li><a target="_blank" style="" href="<?= $link_tuvan;?>">Tư vấn</a></li>
                    <li><a target="_blank" style="" href="<?= $link_tuvan;?>">Hẹn khám</a></li>
                    <li><a target="_blank" style="" href="<?= $link_tuvan;?>">Địa chỉ</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="http://namkhoa168.com/public/frontend/css/quy-trinh-kham_demo.css">
<style>
</style>
<div class="row quytrinhkham" style="font-size: 14px;width: 1000px;margin: auto">
    <div class="main_item">
        <div class="lylx_ts box_bodder">
            <div class="txt">
                <p>Nếu bạn không có nhiều thời gian, không tiện tư vấn trên mạng, bạn vui lòng Click vào phần điền thông tin đăng ký đặt hẹn, hoặc cũng có thể gọi trực tiếp đến số điện thoại <?= phone1;?>, <?= phone2;?> để đặt hẹn, sẽ có bác sỹ chuyên khoa tư vấn cho bạn.</p>
                <div class="btn"><a href="<?= $link_tuvan;?>">đăng ký mã số khám</a></div>
            </div>
        </div>
        <div class="con">
            <div class="tit"><span>CÁCH THỨC ĐẾN PHÒNG KHÁM</span></div>
            <div class="content_main">
                <div class="lx1">
                    <div style="width: 275px;float: left;">
                        <div class="p1">Tự lái xe</div>
                        <h2 style="color: #177fc8;font-size: 12px;font-weight: bold">lộ trình đến phòng khám</h2>
                        <div class="p2">km12 -  ngọc hồi - thanh trì - hn</div>
                    </div>
                    <div style="float: left;background: url('http://namkhoa168.com/public/frontend/images/quy-trinh-kham/txt1.png') no-repeat left 8px;padding-left: 25px;width: 400px;">
                        <p style="margin-bottom: 0">
                            <b class="color_xanh">Từ Thường Tín</b> lên thì qua <b class="color_xanh">Bệnh Viện Nông Nghiệp</b> khoảng 2Km cơ sở 5 tầng nằm ngay mặt đường bên tay phải <b>(Phòng Khám Đa Khoa 168 Hà Nội)</b>
                        </p>
                        <p style="margin-bottom: 0">
                            <b class="color_xanh">Hướng Từ Hà Đông</b> đi qua <b class="color_xanh">đài hóa thân Hoàn Vũ</b> đi tới ngã ba đường tàu (Ngã ba Văn Điển) rẽ tay phải đi khoảng 500m nhìn sang tay trái thấy cơ sở 5 tầng <b>(Phòng Khám Đa Khoa 168 Hà Nội)</b>
                        </p>
                        <p>
                            <b CLASS="color_xanh">Từ hướng bến xe Giáp Bát </b>, đi xuống thẳng theo trục đường <b class="color_xanh">Giải Phóng - Ngọc Hồi qua bên xe Nước Ngầm</b> tới <b>(Phòng Khám Đa Khoa 168 Hà Nội)</b> là khoảng 3Km
                        </p>
                    </div>
                </div>
                <div class="lx2">
                    <div style="width: 275px;float: left">
                        <div class="p1"><span>điểm xe bus</span></div>
                        <h2>Các tuyến buýt phòng khám</h2>
                        <div style="text-transform: uppercase"><span>1.</span> điểm dừng là cách công ty z179</div>
                        <div style="text-transform: uppercase"><span>2.</span> điểm đứng là kho bãi đá văn điển</div>
                        <div class="p2">km12 -  ngọc hồi - thanh trì - hà nội</div>
                    </div>
                    <style>
                        .lx2_2 ul{
                            width: 420px;
                            float: left;
                            margin-top: 13px;
                            margin-left: 40px;
                            list-style: none;
                        }
                        .lx2_2 ul li{
                            float: left;
                            padding-top: 3px;
                        }
                        .lx2_2 ul li div{
                            float: left;
                        }
                        .lx2_2_left{
                            width: 115px;;
                        }
                    </style>
                    <div class="lx2_2">
                        <ul>
                            <li><div class="lx2_2_left">+)Tuyến <b>Xe 04 </b></div><div><span class="color_xanh">: Long Biên - BX nước ngầm</span></div></li>
                            <li><div class="lx2_2_left">+)Tuyến <b>Xe 06A </b></div><div><span class="color_xanh">: BX Giáp Bát - Cầu Giẽ</span></div></li>
                            <li><div class="lx2_2_left">+)Tuyến <b>Xe 06B </b></div><div><span class="color_xanh">: BX Giáp Bát - Thường Tín</span></div></li>
                            <li><div class="lx2_2_left">+)Tuyến <b>Xe 08 </b></div><div><span class="color_xanh">: Long Biên - Đông Mỹ</span></div></li>
                            <li><div class="lx2_2_left">+)Tuyến <b>Xe 12 </b></div><div><span class="color_xanh">: CV Nghĩa Đô - Đại Áng</span></div></li>
                            <li><div class="lx2_2_left">+)Tuyến <b>Xe 16B </b></div><div><span class="color_xanh">: BX Nước Ngầm - BX Mỹ Đình</span></div></li>
                            <li><div class="lx2_2_left">+)Tuyến <b>Xe 39 </b></div><div><span class="color_xanh">: CV Nghĩa Đô - Văn Điển</span></div></li>
                            <li><div class="lx2_2_left">+)Tuyến <b>Xe 60 </b></div><div><span class="color_xanh">: BX Nam Thăng Long - BX Nước Ngầm</span></div></li>
                            <li><div class="lx2_2_left">+)Tuyến <b>Xe 206 </b></div><div><span class="color_xanh">: BX Giáp Bát - Phủ Lý</span></div></li>
                            <li><div class="lx2_2_left">+)Tuyến <b>Xe 209 </b></div><div><span class="color_xanh">: BX Giáp Bát - Hưng Yên</span></div></li>
                        </ul>
                    </div>
                </div>
                <div class="lx3">
                    <div class="p1">tàu hỏa</div>
                    <h2>Lộ trình đến phòng khám</h2>
                    <img src="http://namkhoa168.com/public/frontend/images/quy-trinh-kham/td_tauhoa.png">
                    <div class="p2">km12 -  ngọc hồi - thanh trì - hà nội</div>
                </div>
                <div class="lx4">
                    <div style="width: 275px;float: left">
                        <div class="p1"><span>Máy bay</span></div>
                        <h2>Lộ trình đến phòng khám</h2>
                        <div style="margin: 30px 0;"><img src="http://namkhoa168.com/public/frontend/images/quy-trinh-kham/td_maybay.png"></div>
                        <div class="p2">km12 -  ngọc hồi - thanh trì - hà nội</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="con2">
            <div class="tit"><span>vị trí phòng khám</span></div>
            <div class="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3726.3747631548154!2d105.84303331535367!3d20.937459996263854!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ad96163b2d43%3A0xf38bf1e69bcc4a2c!2zUGjDsm5nIEtow6FtIMSQYSBLaG9hIDE2OCBIw6AgTuG7mWk!5e0!3m2!1svi!2s!4v1445054160245" height="300" width="100%" frameborder="0" scrolling="no"></iframe>
            </div>
        </div>
    </div>
</div>
<div class="body-1" style="background:url('images/bg-footer.png');">
    <div class="container" style="width:1085px; background: url('images/bong.png') 0 -32px no-repeat;padding-top:60px;">
        <div class="row" style="background:none">

            <div class="col-md-6" style="    width: 475px;">
                <img style="margin:0 auto;" alt="" src="images/logo-1.png">
            </div>
            <div class="col-md-6 row-son-tuvan" style="    padding-left: 26px;    width: 602px;">
                <p><a href="<?= $link_tuvan;?>" target="_blank">
                        <img style="margin:0 auto;" alt="" src="images/tv-1.png"> </a>
                </p>

                <p><a href="<?= $link_tuvan;?>" target="_blank">
                        <img style="margin:0 auto;" alt="" src="images/tv-2.png"> </a>
                </p>

                <p><a href="<?= $link_skype;?>" target="_blank">
                        <img style="margin:0 auto;" alt="" src="images/tv-3.png"> </a>
                </p>

                <p><a href="<?= $domain;?>" target="_blank">
                        <img style="margin:0 auto;" alt="" src="images/tv-4.png"> </a>
                </p>

                <div class="row sonkaka" style="clear:both;background:none">
                    <div class="boy-boy" style="width:446px;    padding-top: 5px;">
                        <p>Km12 Ngọc Hồi, Thanh Trì, Hà Nội</p>
                        <p>Ðiện thoại: <?= phone1;?> - <?= phone2;?></p>
                        <p>Email: phongkhamdakhoa168@gmail.com</p>
                    </div>
                    <p style="     margin-left: -20px;   font-size: 13px;
    text-align: left;font-weight:600">Thông tin trên website mang tính chất tham khảo không là căn cứ y tế và chẩn
                        đoán </p>
                </div>
            </div>
        </div>
    </div>
</div>
<?= line_chat();?>
</body>
</html>