<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
    <title>Khuyến mại</title>
    <link type="text/css" href="css/style.css" rel="stylesheet" />
    <script type="text/javascript" src="/skin/zzxsj/js/include.js"></script>
    <base target="_blank">
</head>
<?php
$link_tuvan='http://chat.phongkham168.com/LR/Chatpre.aspx?id=KRX41100266&lng=en';
$domain='http://khamnamkhoa168.com/';
$link_gioithieu='http://khamnamkhoa168.com/2015/chuyen-de-nam-khoa-thang-7/';
$link_kythuat='http://khamnamkhoa168.com/ky-thuat';
$link_thietbi='http://khamnamkhoa168.com/thiet-bi';
$linh_diachi='http://khamnamkhoa168.com/lien-he';
$link_tuvan2='<script language="javascript" src="http://chat.phongkham168.com/JS/LsJS.aspx?siteid=KRX41100266&float=1&lng=en"></script>';
?>
<body>
<div class="zt_tbox">
    <div class="zt_top">
        <div class="zt_top1 fl"><a href="<?= $domain;?>"></a></div>
        <div class="zt_top2 fr"><a href="<?= $domain;?>"></a></div>
    </div>
    <div class="clear"></div>
    <div class="zt_nav">
        <ul>
            <li><a href="<?= $domain;?>">TRANG CHỦ</a></li>
            <li><a href="<?= $link_gioithieu;?>" >GIỚI THIỆU</a></li>
            <li><a href="<?= $link_kythuat;?>" >KỸ THUẬT</a></li>
            <li><a href="<?= $link_thietbi;?>" >THIẾT BỊ</a></li>
            <li><a href="<?= $link_tuvan;?>" >BÁC SỸ</a></li>
            <li><a href="<?= $linh_diachi;?>" >TUYẾN XE</a></li>
            <li><a href="<?= $link_tuvan;?>" >ĐĂNG KÝ TRỰC TUYẾN</a></li>
        </ul>
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>
<div class="zt_ban">
    <div class="zt_ban1"></div>
    <div class="zt_ban2"></div>
    <div class="zt_ban3">
        <div class="zt_ban3c">
            <ul style="background: url('imgs/ico_banner.png') no-repeat center;">
                <li class="zt_ban32"><a href="<?= $link_tuvan;?>"></a></li>
                <li class="zt_ban33"><a href="<?= $link_tuvan;?>"></a></li>
                <li class="zt_ban34"><a href="<?= $link_tuvan;?>"></a></li>
            </ul>
        </div>
    </div>
    <div class="zt_ban4" style="text-align: center;color: #ffea00;font-weight: bold;font-size: 20px;margin-top: 22px;">
        <div style="margin:auto;width: 570px;border-bottom: 2px solid #ffea00;">Thời gian diễn ra hoạt động : <b style="font-size: 25px;">20.04.2016 - 20.05.2016</b></div>
    </div>
</div>
<div class="clear"></div>
<div class="zt_con">
    <div class="zt1">
        <div class="zt_tit1" style="overflow: hidden">
            <div class="loidan">
                <div class="left">
                    <img src="imgs/loidani.png" alt="">
                </div>
                <div class="right">
                    Chào mừng ngày Giải phóng miền nam thống nhất đất nước 30/04 và Quốc tế lao động 1/5, phòng khám đa khoa 168 Hà Nội đặc biệt triển khai hoạt động ưu đãi chăm sóc sức khỏe, để quan tâm sức khỏe người dân và giảm gánh nặng cho họ, tặng sức khỏe cho người bệnh, phát huy ưu thế thiết bị hiện đại, dịch vụ chất lượng, kỹ thuật chuyên nghiệp, điều trị xâm lấn tối thiểu và không đau đớn. Thông qua việc giảm phí, miễn phí phòng khám bảo vệ sức khỏe cho bạn.
                </div>
            </div>
        </div>
        <div class="zt1c">
            <div class="khainv_clear"></div>
            <div class="tit_part1 tit_part">
                <div class="ico_part">những hạng mục ưu tiên nam khoa</div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <div class="zt2" id="con2">
        <div class="zt21">
            <div class="zt21c fl" style="margin-right:15px;">
                <ul>
                    <li class="w1 h3">
                        <p>phí tư vấn bác sỹ</p>
                    </li>
                    <li class="w1 h3">
                        <p>phí bác sỹ khám bệnh</p>
                    </li>
                    <li class="w3 h2"><a href="<?= $link_tuvan;?>"><img src="imgs/mp_p1.jpg" width="457" height="78" /></a></li>
                </ul>
            </div>
            <div class="zt21c fl">
                <ul>
                    <li class="w1 h1" style="width: 457px;">
                        <p>các hạng mục kiểm tra nam khoa</p>
                    </li>
                    <li class="w3 h2"><a href="<?= $link_tuvan;?>"><img src="imgs/ud_p1.jpg" width="457" height="78" /></a></li>
                </ul>
            </div>
        </div>
        <div class="clear"></div>
        <div class="khainv_clear"></div>
    </div>
    <div class="clear"></div>
    <div class="zt4" id="con4">
            <div class="tit_part2 tit_part">
                <div class="ico_part">Giảm 50% phí thủ thuật xâm lấn tối thiểu</div>
            </div>
        <div class="zt4c">
            <div class="khainv_clear"></div>
            <img src="images/img_p2_1.jpg" alt="">
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <div class="zt5" id="con5">
        <div class="tit_part3 tit_part">
            <div class="ico_part">Giảm <b>30%</b> phí thủ thuật chỉnh hình phụ khoa</div>
        </div>
        <div class="khainv_clear"></div>
        <div class="zt5c">
            <img src="images/img_p3_1.jpg" alt="">
            <!--<div class="p3_1">
                <div class="p3_1_c">
                    <div class="p3_w235">
                        <div class="p3_1_c_i">
                            Kỹ thuật vá màng trinh xâm lấn tối thiểu công nghệ Hàn Quốc EVE : ít xâm lấn, không đau đớn, an toàn, hiệu quả cao, không để lại sẹo, chính xác, phục hồi như ban đầu, kín đáo và không cần nằm viện.
                        </div>
                    </div>
                    <div class="p3_w235">
                        <div class="p3_1_c_i">
                            Kỹ thuật xâm lấn tối thiểu công nghệ Hàn Quốc EVE: ít xâm lấn, không đau đớn, an toàn, hiệu quả cao, không để lại sẹo, chính xác, không cần nằm viện, khôi phục sự đàn hồi như trước khi sinh.
                        </div>
                    </div>
                    <div class="p3_w235">
                        <div class="p3_1_c_i">
                            Phòng khám đa khoa 168 luôn đi đầu tại địa bàn Hà Nội về việc áp dụng các kỹ thuật chỉnh hình công nghệ Hàn quốc, không cần qua nước ngoài nhưng vẫn có thể được hưởng các công nghệ Quốc tế.
                        </div>
                    </div>
                    <div class="p3_w235">
                        <div class="p3_1_c_i">
                            <p style="text-align: center">
                                Được hưởng ưu đãi<br>
                                Phí tư vấn bác sĩ<br>
                                Phí bác sĩ khám bệnh<br>
                                Miễn phí đặt hẹn<br>
                                Được ưu tiên khám chữa bệnh<br>
                                <a href="<?= $link_tuvan;?>" style="border: 1px solid #8b6500;padding: 3px 5px;color:#8b6500;margin: auto;margin-top: 10px;display: block;width: 130px;text-indent: 0px; ">Click đặt hẹn khám</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>-->
            <div class="khainv_clear"></div>
            <div class="khainv_clear"></div>
            <!--<div class="p3_2">
                <div class="p3_2_des">
                    <div class="khainv_clear"></div>
                    Trong thời gian ưu đãi những bệnh nhân đến thăm khám sẽ căn cứ vào từng loại kỹ thuật khác nhau, tình trạng sức khỏe khác nhau, sẽ được hưởng tương đương các hạng mục chăm sóc sức khỏe dưới đây, chúc bạn sớm khôi phục.
                </div>
                <div class="khainv_clear"></div>
                <div class="p3_2_img">
                    <div class="p3_2_img_i">
                        <img src="images/img_p3_1.jpg" alt="">
                        <p>Tham khám phụ khoa</p>
                    </div>
                    <div class="p3_2_img_i">
                        <img src="images/img_p3_2.jpg" alt="">
                        <p>Bữa cơm dinh dương</p>
                    </div>
                    <div class="p3_2_img_i">
                        <img src="images/img_p3_3.jpg" alt="">
                        <p>Kiểm tra siêu âm</p>
                    </div>
                    <div class="p3_2_img_i">
                        <img src="images/img_p3_4.jpg" alt="">
                        <p>Soi cổ tử cung</p>
                    </div>
                    <div class="p3_2_img_i">
                        <img src="images/img_p3_5.jpg" alt="">
                        <p>Chăm sóc cổ tử cung</p>
                    </div>
                    <div class="p3_2_img_i">
                        <img src="images/img_p3_6.jpg" alt="">
                        <p>Xét nghiệm khí hư</p>
                    </div>
                </div>
            </div>-->
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <div class="zt4" id="con6">
        <div class="tit_part4 tit_part">
            <div class="ico_part">Thăm khám bệnh lưu ý lựa chọn phòng khám chuyên nghiệp</div>
        </div>
        <div class="khainv_clear"></div>
        <div class="p4_c">
            <div class="p4_c_left">
                <div class="" style="padding-left: 100px;">
                    <b style="font-size: 16px;">Phòng khám đa khoa 168 Hà Nội với trang thiết bị hiện đại, kỹ thuật tiên tiến, điều trị hiệu quả cao, chi phí thấp</b>
                    <p>Không phải phòng khám nào cũng có thể áp dụng kỹ thuật xâm lấn tối thiểu</p>
                    <p>Chỉ có những phòng khám chuyên nghiệp, toàn diện, cơ cấu trang thiết bị và năng lực về y tế chính quy toàn diện mới có đủ tư cách áp dụng.</p>
                    <div class="khainv_clear"></div>
                    <div class="khainv_clear"></div>
                    <img src="images/img_pk.jpg" alt="">
                    <div class="khainv_clear"></div>
                    <div class="khainv_clear"></div>
                    <a href="<?= $link_tuvan;?>" class="tvdt">click tư vấn đặt hẹn</a>
                </div>
            </div>
            <div class="p4_c_right">
                <div class="p4_c_right_1">
                    <div class="ico"></div>
                    <div class="des">
                        <b>Năng lực được công nhận</b>
                        <p>
                            Chúng tôi có thiết bị và môi trường thủ thuật mà những nơi khác không thể so sánh
                        </p>
                    </div>
                </div>
                <div class="khainv_clear"></div>
                <div class="p4_c_right_2">
                    <div class="ico"></div>
                    <div class="des">
                        <b>Bảo đảm an toàn</b>
                        <p>Phòng thủ thuật của phòng khám đa khoa 168 Hà Nội vô khuẩn tuyệt đối, các y bác sỹ chấp hành nghiêm khắc quy trình thao tác kỹ thuật vô khuẩn và chế độ vô khuẩn, hàng tuần đều tiến hành kiểm tra hiệu quả vô khuẩn của phòng thủ thuật, có hiệu quả trong việc phòng tránh nhiễm trùng trong thủ thuật, nâng cao độ an toàn của thủ thuật.</p>
                    </div>
                </div>
                <div class="khainv_clear"></div>
                <div class="p4_c_right_3">
                    <div class="ico"></div>
                    <div class="des">
                        <b>Yêu cầu về trình độ</b>
                        <p>Vì sự an toàn của bạn, hi vọng mọi người nâng cao cảnh giác, lựa chọn cẩn thận! Không nên tin tưởng các phòng khám tư nhân nhỏ lẻ và không chính quy, khi làm thủ thuật nhất định phải lựa chọn phòng khám chính quy, có chất lượng, quy mô lớn...</p>
                    </div>
                </div>
                <div class="khainv_clear"></div>
                <div class="p4_c_right_4">
                    <div class="ico"></div>
                    <div class="des">
                        <b>Trang thiết bị hiện đại</b>
                        <p>Tạo dựng thương hiệu phòng khám đa khoa hàng đầu trong khu vực Hà Nội, phòng khám đa khoa 168 Hà Nội nhập khẩu các thiết bị tiên tiến nhất như: máy hiển vi phóng đại đa chức năng, máy trị liệu hồng ngoại, máy trị liệu (CRS) sóng ngắn, máy trị liệu vi ba, máy chẩn đoán siêu âm màu, hệ thống trị liệu đẳng li tử nhiệt độ thấp của Mỹ, máy phân tích chất lượng tinh trùng, máy soi trực tràng hậu môn của Đức... Đưa ra các dữ liệu khoa học có lợi nhất, có lợi trong việc điều trị sức khỏe cho người bệnh. </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="part5" id="con7">
        <div class="tit_part5 tit_part">
            <div class="ico_part">phòng khám chuyên nghiệp tại hà nội</div>
        </div>
        <div class="khainv_clear"></div>
        <div class="part5_1">
            <ul>
                <li>
                    <span>Phòng khám đa khoa<br>chuyên nghiệp</span>
                    <p>Chuyên điều trị các bệnh, bảo vệ sức khỏe bản thân</p>
                </li>
                <li>
                    <span>Đội ngũ y tế<br>lớn mạnh</span>
                    <p>Tập hợp các bác sỹ nổi tiếng trong và ngoài nước, đội ngũ y bác sỹ hùng hậu </p>
                </li>
                <li>
                    <span>Kỹ thuật chẩn trị tiên tiến<br>toàn diện</span>
                    <p>Nhập khẩu các loại kỹ thuật chẩn trị, nâng cao hiệu quả điều trị bệnh</p>
                </li>
                <li>
                    <span>Đến Thăm khám<br>là được hưởng ưu đãi</span>
                    <p>Người bệnh đến khám sẽ được hưởng ưu đãi, tiết kiệm chi phí</p>
                </li>
            </ul>
        </div>
        <div class="khainv_clear"></div>
        <div class="part5_2">
            <ul>
                <li style="padding-top: 20px;padding-bottom: 20px;">
                    <img src="imgs/p5_2_1.png" alt="">
                </li>
                <li>
                    <a href="<?= $link_tuvan;?>">
                        <img src="imgs/p5_2_2.png" alt="">
                        <br><b>tư vấn trực tuyến</b>
                    </a>
                </li>
                <li>
                    <a href="<?= $link_tuvan;?>">
                        <img src="imgs/p5_2_3.png" alt="">
                        <br><b>đặt khám online</b>
                    </a>
                </li>
                <li>
                    <a href="<?= $link_tuvan;?>">
                        <img src="imgs/p5_2_4.png" alt="">
                        <br><b>tư vấn điện thoại</b>
                    </a>
                </li>
                <li>
                    <a href="<?= $link_tuvan;?>">
                        <img src="imgs/p5_2_5.png" alt="">
                        <br><b>đặt lịch khám</b>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="clear"></div>
<div class="foot">
    <div class="clear"></div>
    <div class="foot_con">
        <div class="foot_l fl">
            <div class="foot_ll fl"><img src="imgs/logo_f.png" /></div>
        </div>
        <div class="foot_r fl">
            <ul>
                <li>KM 12 - Ngọc Hồi - Thanh Trì - Hà Nội</li>
                <li>Điện Thoại : 043 6866 888 - 043 6866 686</li>
                <li>Email : phongkhamdakhoa168@gmail.com</li>
                <li><i>Thông tin trên website mang tính chất tham khảo không là căn cứ y tế và chẩn đoán</i></li>
            </ul>
        </div>
    </div>
</div>
<?= $link_tuvan2;?>
</body>
</html>