<?php
require_once("../../../define.php");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Hẹp bao quy đầu</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <link href="css/main.css" rel="stylesheet" type="text/css" />
    <link href="css/zt/main.css" rel="stylesheet" type="text/css" />
    <base target="_blank">
    <?= ico_shortcut;?>
</head>
<body style="font-family: arial,times new roman">
<div id="top_ts">
</div>
<div id="nav">
    <div class="nav_in">
        <div class="logo"><a href=""><img src="http://namkhoa168.com/public/frontend/img/home/logo.png"/></a></div>
        <div class="nav_list fwryh">
            <div class="nav_list_bg"><span></span></div>
            <ul class="bg">
                <li class="f"></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
            <ul class="txt">
                <li class="f">
                    <a href="<?= domain;?>"><div class="box"><p>TRANG CHỦ<br>PHÒNG KHÁM</p></div></a>
                </li>
                <li>
                    <a href="<?= link_gioithieu;?>"><div class="box"><p>GIỚI THIỆU<br>PHÒNG KHÁM</p></div></a>
                </li>
                <li>
                    <a href="<?= link_tuvan;?>"><div class="box"><p>BÁC SỸ<br>CHÍNH QUY</p></div></a>
                </li>
                <li>
                    <a href="<?= link_kythuat;?>"><div class="box"><p>KỸ THUẬT<br>HIỆN ĐẠI</p></div></a>
                </li>
                <li>
                    <a href="<?= link_thietbi;?>"><div class="box"><p>THIẾT BỊ<br>TIÊN TIẾN</p></div></a>
                </li>
                <li class="last">
                    <a href="<?= link_diachi;?>"><div class="box"><p>ĐỊA CHỈ<br>PHÒNG KHÁM</p></div></a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div id="banner" style="margin: auto;background: #fcfcfd;">
    <div class="banner_item">
        <img src="image/banner.jpg" alt="">
    </div>
    <div class="banner5">
        <!--<div class="mian"><span><a href="<?/*= link_tuvan;*/?>">TƯ VẤN TRỰC TUYẾN</a></span> </div>-->
    </div>
</div>
<div id="title">
    <div class="tt"> <span><img src="image/title1.png" /> </span>
        <p>NGUY HẠI RẤT LỚN CỦA HẸP BAO QUY ĐẦU</p>
        </div>
        <div class="clear"></div>
    <div class="mian">
        <div class="left">
            <p style="padding-right: 15px;">DẪN ĐẾN NAM GIỚI VÔ SINH</p>
            <p style="padding-right: 90px;letter-spacing: -1px;">GÂY RA UNG THƯ DƯƠNG VẬT</p>
            <p style="padding-right: 105px;line-height: 25px;">THƯƠNG TỔN<br>CHỨC NĂNG THẬN</p>
        </div>
        <div class="right">
            <p style="padding-left: 20px;">DẪN ĐẾN XUẤT TINH SỚM,LIỆT DƯƠNG</p>
            <p style="padding-left: 90px">DẪN TỚI VIÊM NHIỄM PHỤ KHOA</p>
            <p style="padding-left: 100px;line-height: 25px;">GÂY TRỞ NGẠI SỰ PHÁT<br>TRIỂN CỦA DƯƠNG VẬT</p>
        </div>
    </div>
    <div class="clear"></div>
</div>
<div style="width: 100%;background: #f8f8f8">
    <div id="title2">
        <div class="mian">
            <div class="left"><span><img src="image/mian_pic.jpg" width="419" height="210" /></span>
                <h3><img src="image/mian_pic2.jpg" height="54" width="348" /></h3>
                <span style="margin-right:10px;"><img src="image/mian_pic3.jpg" /></span>
                <div style="float: right;width: 285px;">
                    <p>39.5% nữ giới cho rằng dễ mắc các bệnh viêm nhiễm phụ khoa</p>
                    <p>12% nữ giới cho rằng quá bẩn</p>
                    <p>48.5% nữ giới cho rằng bao quy đầu dài ảnh hưởng đến chất lượng quan hệ tình dục</p>
                </div>
            </div>
            <div class="right">
                <div class="box"> <span><img src="image/mian_pic4.jpg" /></span>
                    <h3>Chị Phạm Thị Thu ở Cầu Giấy cho biết: tôi có độc thân cũng không chấp nhận nam giới bị dài bao quy đầu </h3>
                    <font>Chưa kết hôn<br>25 tuổi</font>
                    <p>Mặc dù tôi độc thân nhưng tôi học y vì vậy mà có yêu cầu nghiêm khắc đối với người bạn đời, dài bao quy đầu trong mắt tôi không chỉ là một loại bệnh, mà tôi còn...</p>
                </div>
                <div class="box"> <span><img src="image/mian_pic5.jpg" /></span>
                    <h3>Cách nhìn của dân công sở đối với người chồng bị dài bao quy đầu</h3>
                    <font>27 tuổi<br>kết hôn 1 năm</font>
                    <p style="line-height: 18px;">Kết hôn chưa được 1 năm tôi đã bị viêm phụ khoa nặng, đến phòng khám điều trị nhưng vẫn tái phát nhiều lần, sau đó bác sỹ hỏi chồng tôi có phải bị dài bao quy đầu hay không, bác sỹ cho biết bệnh này dễ dẫn đến vợ bị viêm nhiễm phụ khoa, về nhà bắt chồng phải....</p>
                </div>
                <div class="box"> <span><img src="image/mian_pic6.jpg" /></span>
                    <h3>Chị Nguyễn Thị Hải cho biết: bao quy đầu dài ảnh hưởng đến tình cảm vợ chồng</h3>
                    <font>Đã kết hôn<br>32 tuổi</font>
                    <p>Chồng bị dài bao quy đầu, dẫn đến tôi thường xuyên bị viêm nhiễm phụ khoa như viêm lộ tuyến cổ tử cung, viêm cổ tử cung... Những bệnh này thường tái phát nhiều lần, điều khiến tôi không thể chấp nhận được là...</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="title3">
    <div class="tt"> <span><img src="image/title2.jpg" /> </span>
        <p>Dài bao quy đầu là gì? Dài bao quy đầu là chỉ nam giới trưởng thành bao quy đầu bị bao phủ bởi lớp da dương vật, khiến cho quy đầu không thể hoàn toàn lộ ra ngoài được.</p>
        <font><a href="<?= link_tuvan;?>" class="btn_tvtt">TƯ VẤN TRỰC TIẾP</a></font> </div>
    <div class="left">
        <h3><img src="image/mian2_pic.jpg" /></h3>
        <p><a href="<?= link_tuvan;?>">QUY ĐẦU<br>CÓ MÙI HÔI</a></p>
        <p><a href="<?= link_tuvan;?>">QUY ĐẦU<br>PHÙ NỀ</a></p>
        <p><a href="<?= link_tuvan;?>">VIÊM<br>BAO QUY ĐẦU</a></p>
        <p><a href="<?= link_tuvan;?>">VIÊM NHIỄM<br>VI KHUẨN NIỆU ĐẠO</a></p>
        <p><a href="<?= link_tuvan;?>">VIÊN NHIỄM<br>NHIỀU LẦN</a></p>
        <p><a href="<?= link_tuvan;?>">DỊCH <br>TĂNG NHIỀU</a></p>
        <p><a href="<?= link_tuvan;?>">TIỂU TIỆN<br>KHÔNG CÓ LỰC</a></p>
        <p><a href="<?= link_tuvan;?>">BAO QUY ĐẦU<br>BỊ BAO PHỦ</a></p>
        <font ><a href="<?= link_tuvan;?>">Tự kiểm tra thông tin chính xác,tư vấn trực tiếp bác sỹ >> </a></font> </div>
    <div class="right">
        <h3><img src="image/mian2_pic2.jpg" /></h3>
        <div class="box"><span><img src="image/mian2_pic3.jpg" style="max-width: 100%" /></span> <font><a href="<?= link_tuvan;?>">của bạn<br>có bình thường không？</a> </font> </div>
    </div>
</div>
<div id="title4">
    <div class="mian">
        <div class="tt"> <span><img src="image/title3.jpg" style="max-width: 100%" /> </span>
            <font><a href="<?= link_tuvan;?>">TƯ VẤN TRỰC TUYẾN>></a></font> </div>
        <span><img src="image/mian3_pic5.jpg" style="max-width: 100%;margin-left: 4px;" /></span>
        <font><a href="<?= link_tuvan;?>">Lựa chọn 1 lần, hạnh phúc 1 đời</a></font>
    </div>
</div>
<div id="title5">
    <div class="tt"> <span><img src="image/title4.jpg" /> </span>
        <p>
            Dài bao quy đầu là gì? Dài bao quy đầu là chỉ nam giới trưởng thành<br>bao quy đầu bị bao phủ bởi lớp da dương vật, khiến cho quy đầu không thể<br>hoàn toàn lộ ra ngoài được<br />
        </p>
        <div style="width: 100%;float: left;"><a href="<?= link_tuvan;?>" class="btn_tvtt" style="margin: auto">TƯ VẤN TRỰC TUYẾN >></a></div>
        <div class="clear"></div>
        </div>
    <div class="box">
        <div class="left"><img src="image/mian4_pic.jpg" /></div>
        <div class="right"> <span><img src="image/mian4_line.jpg" /></span>
            <h3>Kính hiển vi thủ thuật của đức</h3>
            <strong>tránh gây tổn thương mạch máu, thần kinh, an toàn, nhanh chóng</strong>
            <font><a href="<?= link_tuvan;?>">TƯ VẤN TRỰC TUYẾN>></a></font> </div>
    </div>
    <div class="box2">
        <div class="left"><span><img src="image/mian4_line.jpg" /></span>
            <h3>Kính hiển vi thủ thuật của đức</h3>
            <strong>tránh gây tổn thương mạch máu, thần kinh, an toàn, nhanh chóng</strong>
            <font><a href="<?= link_tuvan;?>">TƯ VẤN TRỰC TUYẾN>></a></font></div>
        <div class="right"> <img src="image/mian4_pic2.jpg" width="456" height="260" /> </div>
    </div>
</div>
<div id="title6">
    <div class="mian">
        <div class="tt"> <span style="display: block"><img src="image/title5.jpg" /> </span>
            <p style="display: block">Phòng thủ thuật vô khuẩn là tiêu chuẩn đảm bảo an toàn thủ thuật, một ca thủ thuật thành công không chỉ cần một bác sỹ ngoại khoa tay nghề cao, một bác sỹ gây mê nhiều kinh nghiệm, còn cần môi trường thủ thuật vô khuẩn tốt nhất, an toàn, sạch sẽ... Một môi trường thủ thuật vô khuẩn ngoài việc đảm bảo bệnh nhân thoải mái, quan trọng hơn là thời gian hồi phục và thời gian thủ thuật để tránh viêm nhiễm, biến chứng do thủ thuật gây ra, đảm bảo thủ thuật an toàn cho người bệnh.</p>
            <div class="clear"></div>
            <div style="width: 100%;text-align: center;display: block"><a href="<?= link_tuvan;?>" class="btn_tvtt" style="margin: auto">TƯ VẤN TRỰC TUYẾN>></a></div>
            <div class="clear"></div>
        </div>
        <div class="box"> <span><img src="image/mian5_pic.jpg" /></span>
            <h3>ĐỘ AN TOÀN</h3>
            <p>Diệt khuẩn khoa học sạch sẽ, độ sạch không khí đạt 99.98%</p>
        </div>
        <div class="box"> <span><img src="image/mian5_pic2.jpg" /></span>
            <h3>KHÔNG VIÊM NHIỄM</h3>
            <p>Tỷ lệ viêm nhiễm gần như không có</p>
        </div>
        <div class="box"> <span><img src="image/mian5_pic3.jpg" /></span>
            <h3 style="line-height: 22px;">CÂN BẰNG NHIỆT ĐỘ,<br>ĐỘ ẨM VÀ ÁP SUẤT</h3>
            <p>Tấm cách âm và giữ nhiệt, 6 lần phun ion chân không</p>
        </div>
        <div class="box"> <span><img src="image/mian5_pic4.jpg" /></span>
            <h3 style="line-height: 22px;">VÔ KHUẨN,<br>NGHIÊM NGẶT</h3>
            <p>Mỗi tiếng thay không khí 600 lần, làm cho vi khuẩn không có chất truyền dẫn</p>
        </div>
        <div class="box"> <span><img src="image/mian5_pic5.jpg" /></span>
            <h3>KHÔNG KHÍ SẠCH</h3>
            <p>Không khí sạch, đảm bảo vô khuẩn</p>
        </div>
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>
<div class="clear"></div>
<div id="title7">
    <h3 style="color:#177fc8;">MỘT PHÒNG THỦ THUẬT TỐT<BR>KHÔNG PHẢI PHÒNG KHÁM THÔNG THƯỜNG NÀO CŨNG CÓ THỂ DÙNG ĐƯỢC</h3>
</div>
<div class="clear"></div>
<table class="tab">
    <tr>
        <td class="t1"><img src="image/mian5_pic6.jpg" /></td>
        <td class="t2">
            <b>PHÒNG THỦ THUẬT PHỔ THÔNG</b>
            <p>Phòng thủ thuật sạch thông thường hoặc phòng thủ thuật sạch phổ thông</p>
        </td>
        <td class="t3" style="color: #177fc8;">
            <b>PHÒNG THỦ THUẬT VÔ KHUẨN 168</b>
            <p>Phòng thủ thuật sạch tiêu chuẩn</p>
        </td>
    </tr>
    <tr>
        <td class="t1">CÁCH ÂM</td>
        <td class="t2"><span><img src="image/mian5_pic7.jpg" /> </span>
            <p>Tường mỏng hoặc lớp hợp kim phổ thông</p></td>
        <td class="t3"><span><img src="image/mian5_pic8.jpg" /> </span>
            <p>Lớp cách âm giữ nhiệt 12mm, cách âm đạt tiêu chuẩn quốc tế</p></td>
    </tr>
    <tr>
        <td class="t1">PHUN KHÁNG KHUẨN</td>
        <td class="t2">
            <span class="dong2"><img src="image/mian5_pic7.jpg" /> </span>
            <p>Rất ít hoặc không có điều kiện tiến hành phun kháng khuẩn</p>
        </td>
        <td class="t3"><span><img src="image/mian5_pic8.jpg" /> </span>
            <p>Phun ion chống khuẩn 6 lần chân không</p></td>
    </tr>
    <tr>
        <td class="t1">VẬT LIỆU SÀN</td>
        <td class="t2">
            <span class="dong2"><img src="image/mian5_pic7.jpg" /> </span>
            <p>Sàn tương đối tốt so với phòng thủ thuật thông thường, nhưng không chống được bụi và vi khuẩn </p>
        </td>
        <td class="t3">
            <span class="dong2"><img src="image/mian5_pic8.jpg" /> </span>
            <p>Phòng thủ thuật vô khuẩn, duy trì phòng thủ thuật không vi khuẩn không bụi bẩn</p>
        </td>
    </tr>
    <tr>
        <td class="t1">CÂN BẰNG NHIỆT</td>
        <td class="t2"><span><img src="image/mian5_pic7.jpg" /> </span>
            <p>Cân bằng nhiệt và áp suất là vấn đề lớn</p>
        </td>
        <td class="t3"><span><img src="image/mian5_pic8.jpg" /> </span>
            <p>Trong phòng thủ thuật cân bằng nhiệt, độ ẩm và áp suất</p>
        </td>
    </tr>
    <tr>
        <td class="t1">KHÔNG KHÍ SẠCH</td>
        <td class="t2">
            <span><img src="image/mian5_pic7.jpg" /> </span>
            <p>Độ sạch không khí khó đạt được 85%</p>
        </td>
        <td class="t3"><span><img src="image/mian5_pic8.jpg" /> </span>
            <p>Mỗi tiếng thay 600 lần không khí, độ sạch không khí đạt 99.98%</p></td>
    </tr>
    <tr>
        <td class="t1">LƯỢNG VI KHUẨN</td>
        <td class="t2">
            <span class="dong2"><img src="image/mian5_pic7.jpg" /> </span>
            <p>Nồng độ bình quân lớn nhất của vi khuẩn là 5con/30min.φ90máu (175 con/m3)</p></td>
        <td class="t3">
            <span class="dong2"><img src="image/mian5_pic8.jpg" /> </span>
            <p>Nồng độ bình quân lớn nhất của vi khuẩn là 1.5 con/30min.φ90máu （50con/m3）</p></td>
    </tr>
</table>
<div id="title8">
    <div class="tt"> <span><img src="image/title6.jpg" /> </span>
        <p>Để thực sự đạt được hiệu quả như mong muốn, một sợi chỉ khâu cũng phải chọn kĩ lưỡng</p>
        <font><a href="<?= link_tuvan;?>" class="btn_tvtt">TƯ VẤN TRỰC TUYẾN>></a></font>
    </div>
    <div class="clear"></div>
    <div class="left"><img src="image/mian6_pic.jpg"/></div>
    <div class="right">
        <h3>ĐẶC ĐIỂM CHỈ COLLAGENE NHẬP KHẨU</h3>
        <span><img src="image/mian6_pic7.jpg" /></span>
        <p style="margin-top: 5px;line-height:22px;">Hoàn toàn tự tiêu, không tác dụng phụ, không để lại chất hóa học, không có phản ứng xấu với cơ thể</p>
        <p>Chỉ khâu collagene có lợi với việc phục hồi vết thương</p>
        <p>Dịch thể mềm, không gây thương tổn tổ chức cơ thể</p>
        <p>Độ căng vừa phải, không dẫn đến nứt chỉ vết khâu</p>
        <font><a href="<?= link_tuvan;?>">TÌM HIỂU CHỈ KHÂU COLLAGENE NHẬP KHẨU</a></font>
        <strong><a href="<?= link_tuvan;?>">TÌM HIỂU<br>QUÁ TRÌNH THỦ THUẬT</a></strong>
    </div>
</div>
<table class="tab2">
    <tr class="t1">
        <td width="100"></td>
        <td width="192">CHỈ TƠ</td>
        <td width="282">CHỈ RUỘT CỪU</td>
        <td width="222">CHỈ TỔNG HỢP NHÂN TẠO</td>
        <td style="font-weight:bold;">CHỈ COLLAGENE CAO SU</td>
    </tr>
    <tr class="t2">
        <td style="font-weight:bold;">VẬT TƯ</td>
        <td>Nilon</td>
        <td>Áo ruột bông cừu</td>
        <td>các chất hóa học hợp thành</td>
        <td>Collagene cao su thuần tự nhiên</td>
    </tr>
    <tr class="t2">
        <td style="font-weight:bold;">THỜI GIAN<br> TỰ TIÊU</td>
        <td>Không tự tiêu</td>
        <td>10-20 Ngày</td>
        <td>Không tiêu hoàn toàn, có để lại chất hóa học</td>
        <td>5-7 Ngày</td>
    </tr>
    <tr class="t2">
        <td style="font-weight:bold;">ĐẶC TÍNH<br>KHÔNG<br>GIỐNG NHAU</td>
        <td>Lực căng mạnh nhất nhưng cần chỉ co lại</td>
        <td style="line-height:22px;">Lực căng mạnh nhất nhưng cần chỉ co lại</td>
        <td  style="line-height:22px;">không thích hợp khâu da người (thủ thuật cắt bao quy đầu không thích hợp)</td>
        <td style="line-height:22px;">Chỉ collagene cao su toàn hoàn loại bỏ tạp chất, thời gian tự tiêu ngắn, an toàn cao.</td>
    </tr>
</table>
<div id="title9">
    <div class="tt"> <span><img src="image/title7.jpg" /> </span>
        <p>Điều trị thời gian ngắn, giúp bạn không còn lo lắng cả một đời </p>
        <font><a href="<?= link_tuvan;?>" class="btn_tvtt">TƯ VẤN TRỰC TUYẾN</a></font>
    </div>
    <div class="clear"></div>
    <div class="box"> <span><img src="image/mian7_pic.jpg" width="125" height="144" /></span>
        <h3>thủ thuật hiệu quả,<br>rút ngắn thời gian</h3>
        <p>Thủ thuật sử dụng thiết kế mỹ học động thái, căn cứ vào tình trạng dương vật để đưa ra tuyến cắt phù hợp nhất, thời gian thủ thuật được rút ngắn so với phương pháp truyền thống.</p>
    </div>
    <div class="box"> <span><img src="image/mian7_pic2.jpg" width="125" height="144" /></span>
        <h3>Máy móc thủ thuật đặc thù,<br>nâng cao hiệu quả thủ thuật </h3>
        <p>Thủ thuật áp dụng dao thủ thuật Swann-Morton của Anh Quốc, công hiệu tốt, sử dụng thích hợp, nâng cao hiệu quả thủ thuật.</p>
    </div>
    <div class="box"> <span><img src="image/mian7_pic3.jpg" width="125" height="144" /></span>
        <h3>Chuyên gia thủ thuật đầu ngành, thủ pháp thành thục nhanh gọn</h3>
        <p>Bác sỹ chỉnh hình cơ quan sinh sản, đã làm thủ thuật bao quy đầu thành công cho hàng vạn người, không xảy ra sơ xuất.</p>
    </div>
</div>
<div id="title10">
    <div class="mian">
        <div class="tt"> <span><img src="image/title8.jpg" /> </span>
            <p>Nam giới nỗ lực để mua nhà, mua xe, xây dựng sự nghiệp,... Muốn làm những việc đó thì phải có sức khỏe; đối tốt với bản thân, lựa chọn tốt cho chính mình, lựa chọn phòng khám tốt, thay đổi bản thân, hưởng thụ cuộc sống tốt đẹp!</p>
            <font><a href="<?= link_tuvan;?>" class="btn_tvtt">TƯ VẤN TRỰC TIẾP</a></font>
        </div>
        <div class="clear"></div>
        <div class="box"> <span><img src="image/mian8_pic.jpg" /></span> <strong>Công nhân viên / Trịnh Văn Mạnh</strong>
            <p>Sau khi thủ thuật cuộc sống vợ chồng thực sự tốt hơn rất nhiều, chị anh không biết đã bị viêm nhiễm phụ khoa</p>
            <font><a href="<?= link_tuvan;?>" class="btn_tvtt">TƯ VẤN TRỰC TUYẾN</a></font> </div>
        <div class="box2"> <span><img src="image/mian8_pic2.jpg" /></span> <strong>Giám đốc công ty / Lê Văn Minh</strong>
            <p>Phục hồi nhanh sau thủ thuật, quan hệ với vợ xong cảm thấy thỏa mãn</p>
            <font><a href="<?= link_tuvan;?>" class="btn_tvtt">TƯ VẤN TRỰC TUYẾN</a></font> </div>
        <div class="box"> <span><img src="image/mian8_pic3.jpg" /></span> <strong>Sinh viên / Phạm Văn Nam </strong>
            <p>Từ sau khi cắt bao quy đầu, mỗi lần hẹ bạn gái, cô ấy đều nhanh chóng nhận lời...</p>
            <font><a href="<?= link_tuvan;?>" class="btn_tvtt">TƯ VẤN TRỰC TUYẾN</a></font> </div>
        <div class="box2"> <span><img src="image/mian8_pic4.jpg" /></span> <strong>Nhân viên IT/Nguyễn Thu Hà</strong>
            <p>Sau thủ thuật không cần cắt chỉ, cậu nhỏ rất phong độ, chất lượng quan hệ được nâng lên nhiều.</p>
            <font><a href="<?= link_tuvan;?>" class="btn_tvtt">TƯ VẤN TRỰC TUYẾN</a></font> </div>
    </div>
</div>
<script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
<?= menu_footer();?>
<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="js/ltMove.js"></script>
<script type="text/javascript" src="js/fun.js"></script>
<script type="text/javascript">
    $(function(){
        nav1Tab();
    });
</script>
</body>
</html>
