<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>đại tiện khi ra máu</title>
    <link href="css/style.css" type="text/css" rel="stylesheet"/>
    <link href="css/custorm.css" type="text/css" rel="stylesheet"/>
    <script type="text/javascript"  src="js/bigpicroll.js"></script>
    <script type='text/javascript' src="js/jquery-1.4.4.min.js"></script>
    <script type="text/javascript"  src="js/js.js"></script>
    <script src="js/simplefoucs.js" type="text/javascript"></script>
	<base target="_blank" />
</head>
<?php require_once('../../define.php'); ?>
<?php
$domain=domain;
$link_gioithieu=link_gioithieu;
$link_kythuat=link_kythuat;
$link_thietbi=link_thietbi;
$link_diachi=link_diachi;
$link_tuvan=link_tuvan;
$line_chat=line_chat();
?>
<body>
<div class="fram">
<div class="head">
    <div class="nav">
        <div class="nav_bg">
            <div class="logo">
                <a href="http://trihanoi.com/">
                <img src="images/logo.png"/>
                </a>
            </div>
            <div class="nav_1">
                <ul>
                    <li><a href="<?= $domain;?>" >trang chủ</a></li>
                    <li><a href="<?= $link_gioithieu;?>" >giới thiệu</a></li>
                    <li><a href="<?= $link_kythuat;?>" >kỹ thuật</a></li>
                    <li><a href="<?= $link_thietbi;?>" >thiết bị</a></li>
                    <li><a href="<?= $link_diachi;?>" >địa chỉ</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="banner">
        <div style="background:url(images/banner.jpg) no-repeat top center; overflow:hidden;width: 100%;height: 530px;">
            <div  style="width:1000px; margin:auto; height:100px;margin-top: 330px;">
                <a href="<?= $link_tuvan;?>" ><div style="width:240px; margin-left:40px; height:100px;"></div></a>
            </div>
        </div>
    </div>
</div>
<div class="main1">
    <div class="comm">
        <a href="<?= $link_tuvan;?>" style="color: #000000;text-transform: uppercase;font-weight: bold;font-size: 20px;">
            <span class="color_red">Đi vệ sinh ra máu,</span> bạn có những triệu chứng đó không
        </a>
    </div>
    <div class="m1s">
        <ul>
            <li class="li_bta" id="bxjs1" onmousemove="Tab(1,8,'bxjs','li_bta','li_btb')"><a href="<?= $link_tuvan;?>" ><p><img src="images/tub_1.png"/></p><h3>Đại tiện xong máu phun theo tia</h3></a></li>
            <li class="li_btb" id="bxjs2" onmousemove="Tab(2,8,'bxjs','li_bta','li_btb')"><a href="<?= $link_tuvan;?>" ><p><img src="images/tub_2.png"/></p><h3>Đại tiện xong máu chảy thành giọt</h3></a></li>
            <li class="li_btb" id="bxjs3" onmousemove="Tab(3,8,'bxjs','li_bta','li_btb')"><a href="<?= $link_tuvan;?>" ><p><img src="images/tub_3.png"/></p><h3>Lau xong chảy máu</h3></a></li>
            <li class="li_btb" id="bxjs4" onmousemove="Tab(4,8,'bxjs','li_bta','li_btb')"><a href="<?= $link_tuvan;?>" ><p><img src="images/tub_4.png"/></p><h3>Màu máu đỏ tươi</h3></a></li>
            <li class="li_btb" id="bxjs5" onmousemove="Tab(5,8,'bxjs','li_bta','li_btb')"><a href="<?= $link_tuvan;?>" ><p><img src="images/tub_5.png"/></p><h3>Đại tiện có màu đỏ thẫm</h3></a></li>
            <li class="li_btb" id="bxjs6" onmousemove="Tab(6,8,'bxjs','li_bta','li_btb')"><a href="<?= $link_tuvan;?>" ><p><img src="images/tub_6.png"/></p><h3>Máu mủ lẫn phân</h3></a></li>
            <li class="li_btb" id="bxjs7" onmousemove="Tab(7,8,'bxjs','li_bta','li_btb')"><a href="<?= $link_tuvan;?>" ><p><img src="images/tub_7.png"/></p><h3>Phân màu đen</h3></a></li>
            <li class="li_btb" id="bxjs8" onmousemove="Tab(8,8,'bxjs','li_bta','li_btb')"><a href="<?= $link_tuvan;?>" ><p><img src="images/tub_8.png"/></p><h3>Đại tiện ra máu không đau</h3></a></li>
        </ul>
    </div>
    <div class="comm2">
        <a href="<?= $link_tuvan;?>">
        Rốt cuộc là có chuyện gì, click tư vấn
        </a>
    </div>
</div>
<div class="main2">
    <div class="comm">
        <a href="<?= $link_tuvan;?>" class="item_tit" >
            <span>Đại tiện ra máu</span> gây ra những bất tiện nào cho người bệnh
        </a>
    </div>
    <div class="m2sa">
        <ul>
            <li>
                <p>Chảy máu sau khi đại tiện, dính ra quần áo làm tôi bối rối</p>
                <div class="tv">
                    <a href="<?= $link_tuvan;?>" >Tư vấn</a>
                </div>
            </li>
            <li>
                <p>Chảy nhiều máu, nam giới dùng băng vệ sinh</p>
                <div class="tv">
                    <a href="<?= $link_tuvan;?>" >Tư vấn</a>
                </div>
            </li>
            <li>
                <p>Ăn đồ cay, tụ tập, uống rượu không thể vui hết mình</p>
                <div class="tv">
                    <a href="<?= $link_tuvan;?>" >Tư vấn</a>
                </div>
            </li>
            <li>
                <p>Đi vệ sinh nhìn thấy màu đỏ, bị ám ảnh về tâm lý</p>
                <div class="tv">
                    <a href="<?= $link_tuvan;?>" >Tư vấn</a>
                </div>
            </li>
            <li>
                <p>Gây ra thiếu máu, sắc mặt tái nhợt</p>
                <div class="tv">
                    <a href="<?= $link_tuvan;?>" >Tư vấn</a>
                </div>
            </li>
        </ul>
    </div>
</div>
<div class="main3">
    <div class="m3sa">
        <div style="overflow:hidden;" >
            <div class="comm"><a href="<?= $link_tuvan;?>" class="item_tit" style="color: white">
                <span>Đại tiện ra máu và không có quy luật,</span> điều trị hay không điều trị
            </a>
            </div>
        </div>
        <div class="m3sa1">
            <img src="images/bx_56.jpg" width="462" height="216"/>
            <div class="m3sa_r">
                <h3>nơi tự kiểm tra triệu chứng</h3>
                <dl style="width: 290px;">
                    <dt style=" width:100%">
                        <span style="float:left;padding-top: 8px;">đại tiện ra máu không đau</span>
                        <a href="<?= $link_tuvan;?>"  style="float:left;"><img src="images/bx_60.gif"/></a><br/></dt>
                    <dd>Đại tiện ra máu không đau</dd>
                    <dd>Đại tiện ra máu đau</dd>
                    <dd>Đại tiện ra máu kèm sa trĩ</dd>
                    <dd>Máu màu đỏ thẫm, kèm dịch nhầy</dd>
                    <dd>Mắt thường không nhìn thấy đại tiện ra máu: phân màu đen</dd>
                </dl>
                <dl style="width: 195px;margin-left: 0px;">
                    <dt style="padding-top: 8px;">giới thiệu bác sỹ</dt>
                    <dd>Trị nội, polyp trực tràng</dd>
                    <dd>Nứt kẽ hậu môn</dd>
                    <dd>Trĩ, polyp trực tràng</dd>
                    <dd>Ưng thư trực tràng</dd>
                    <dd>Xuất huyết đường tiêu hóa trên</dd>
                </dl>
            </div>
        </div>
        <div class="djzx"><a href="<?= $link_tuvan;?>" ><img src="images/bstv.png" width="146" height="116"/></a></div>
    </div>
</div>
<div class="main4">
    <div style="background:url(images/bg_item4.jpg)  top no-repeat; overflow:hidden;padding-top: 90px;padding-bottom: 30px;">
        <div class="m4sa">
            <div class="f_out" id="jbqhjs1c" style=" display:none;">
                <img src="images/jbtp1.jpg" style="float:left;"/>
                <div class="nrxq f_out">
                    <dl>
                        <dt>Đại tiện ra máu</dt>
                        <dd><b>Biểu hiện triệu chứng:</b> đại tiện lẫn máu thường sảy ra sau khi đi đại tiện hoặc trong quá trình đi đại tiện, triệu chứng chảy máu nhỏ giọt hoặc phun thành tia, máu màu đỏ tươi, máu và phân không lẫn vào nhau.</dd>
                        <dd><b>Phân tích bản chất:</b> tĩnh mạch dưới da ống hậu môn tích tụ máu, giãn mạch và hình thành vòm tĩnh mạch, hình trạng ban đầu.</dd>
                        <dd><b>Giới thiệu điều trị:</b> điều trị bằng thuốc xâm lấn tối thiểu trị độ 1,2; điều trị thủ thuật xâm lấn tối thiểu trĩ độ 3,4 </dd>
                    </dl>
                    <a href="<?= $link_tuvan;?>" class="btn_vt" >Rốt cuộc là có chuyện gì, click tư vấn</a>
                </div>

            </div>
            <div class="f_out" id="jbqhjs2c" style="display:block;">
                <img src="images/jbtp2.jpg" style="float:left;"/>
                <div class="nrxq">
                    <dl>
                        <dt>Đại tiện ra máu đường tiêu hóa trên</dt>
                        <dd><b>Biểu hiện triệu chứng:</b> phân đen là biểu hiện chính, do thời gian dài tích tụ lại trong đường tiêu hóa, máu màu đỏ thẫm lẫn trong phân.</dd>
                        <dd><b>Phân tích bản chất:</b> giãn tĩnh mạch ống tiêu hóa, loét dạ dày và u nang dẫn tới đại tiện ra máu, cần tìm ra vị trí chảy máu để điều trị.</dd>
                        <dd><b>Giới thiệu điều trị:</b> trực tiếp đưa thuốc vào vị trí vùng bệnh (chuyên khoa pha thuốc); cầm máu trực quan bằng nội soi, người bị chảy nhiều máu nên xem xét làm thủ thuật.</dd>
                    </dl>
                    <a href="<?= $link_tuvan;?>" class="btn_vt">Rốt cuộc là có chuyện gì, click tư vấn</a>
                </div>
            </div>
            <div class="f_out" id="jbqhjs3c" style="display:none;">
                <img src="images/jbtp3.jpg" style="float:left;"/>
                <div class="nrxq">
                    <dl>
                        <dt>Nứt kẽ hậu môn đại tiện ra máu</dt>
                        <dd><b>Triệu chứng biểu hiện:</b> màu máu đỏ tươi, chảy thành giọt hoặc dính vào giấy khi lau, sau đại tiện hậu môn sẽ đau dữ dội.</dd>
                        <dd><b>Phân tích bản chất:</b> ảnh hướng giữa táo bón và nứt kẽ hậu môn, đại tiện khô rát khi lau chùi sẽ gây ra chảy máu, điều trị xem cụ thể bệnh tình.</dd>
                        <dd><b>Giới thiệu điều trị:</b> nứt kẽ hậu môn cấp tính có thể ngồi bồn tắm để dễ đi đại tiện; nứt kẽ hậu môn mãn tính có thể dùng bồn tắm, bôi trơn để dễ đi đại tiện; nếu lâu không khỏi, điều trị không có hiệu quả cần phải tiến hành thủ thuật.</dd>
                    </dl>
                    <a href="<?= $link_tuvan;?>" class="btn_vt">Rốt cuộc là có chuyện gì, click tư vấn</a>
                </div>
            </div>
            <div class="f_out" id="jbqhjs4c" style="display:none;">
                <img src="images/jbtp4.jpg" style="float:left;"/>
                <div class="nrxq">
                    <dl>
                        <dt>Polyp đại tiện ra máu</dt>
                        <dd><b>Biểu hiện triệu chứng:</b> máu màu đỏ tươi, máu không lẫn vào phân, người bệnh không có cảm giác đau.</dd>
                        <dd><b>Phân tích bản chất:</b> polyp trực tràng tổ chức bề mặc niêm mạc phát triển bất thường, khi loại bỏ viêm nhiễm hoặc cắt bỏ polyp sẽ hết triệu chứng này, cần điều trị kịp thời.</dd>
                        <dd><b>Giới thiệu điều trị:</b> cắt bỏ polyp nội soi, sau khi cắt bỏ bệnh nếu phát hiện còn bênh hoặc biến thành ung thư cần phải điều trị bằng thủ thuật.</dd>
                    </dl>
                    <a href="<?= $link_tuvan;?>" class="btn_vt">Rốt cuộc là có chuyện gì, click tư vấn</a>
                </div>
            </div>
            <div class="nrli">
                <ul>
                    <li class="li_no" id="jbqhjs1" onmousemove="Tall(1,5,'jbqhjs','li_pl','li_no')"></li>
                    <li class="li_pl" id="jbqhjs2" onmousemove="Tall(2,5,'jbqhjs','li_pl','li_no')"></li>
                    <li class="li_no" id="jbqhjs3" onmousemove="Tall(3,5,'jbqhjs','li_pl','li_no')"></li>
                    <li class="li_no" id="jbqhjs4" onmousemove="Tall(4,5,'jbqhjs','li_pl','li_no')"></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="main5">
    <div class="m5s">
        <div class="comm item_tit">
            <!--<img src="images/sb_bt.gif" width="821" height="58"/>-->
            <span>Tạm biệt đi ngoài ra máu,</span> kiểm tra chính xác, quy phạm 100% không sai sót
        </div>
        <div class="bannerbox">
            <div id="focus">
                <ul>
                    <li>
                        <div class="m5_min" >
                            <h3><a href="<?= $link_tuvan;?>" >Chẩn đoán hậu môn bằng ngón tay</a></h3>
                            <div class="m5nr">
                                <div style="width:506px; float:left;"><a href="" ><img src="images/sb3.jpg" width="481" height="179" class="l"/></a></div>
                                <div class="nrxq" style="width:283px; float:left; margin-left:25px;" >
                                    <p>Bác sỹ dùng ngón tay tiến hành sờ vào bên trong hậu môn người bệnh, có thể phát hiện và chẩn đoán đa số các bệnh về hậu môn. Có thể sớm phát hiện ra các bệnh về trực tràng hậu môn, căn cứ thống kê trong nước, có đến 80% tỷ lệ ung thư trực tràng thông qua việc kiểm tra bằng ngón tay.</p>
                                    <b>Đại tiện ra máu kiểm tra có đau không? Cần bao nhiêu tiền?</b>
                                    <a href="<?= $link_tuvan;?>" class="btn_vt">Click tư vấn</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="m5_min">
                            <h3><a href="<?= $link_tuvan;?>" >Máy soi hậu môn DR.C Hàn Quốc </a></h3>
                            <div class="m5nr">
                                <a href="" ><img src="images/sb1.jpg" class="l"/></a>
                                <div class="nrxq">
                                    <p style="padding-right: 15px;"> Máy kiểm tra trực tràng hậu môn tiên tiến nhất hiện nay. Áp dụng kỹ thuật đầu quay cao tần rõ nét dùng trong y tế với 1.2 triệu pixel tiên tiến quốc tế, có ưu điểm rõ nét, không sai sót, kiểm tra chính xác; có thể tiến hành chẩn đoán chính xác và lấy hình ảnh ở sâu bên trong trực tràng hậu môn.</p>
                                    <dl>
                                        <dd>- Rõ nét: máy quay điện tử hình thức thu nhỏ</dd>
                                        <dd>- Không sai sót: 1600 lần quang học định vị vị trí bệnh, chẩn đoán chính xác</dd>
                                        <dd>- Độ thích ứng rộng: có thể kiểm tra ra 108 loại bệnh trực tràng hậu môn</dd>
                                        <a href="<?= $link_tuvan;?>" class="btn_vt">Click tư vấn</a>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="m5_min">
                            <h3><a href="<?= $link_tuvan;?>" >Máy soi kết tràng điện tử không đau</a></h3>
                            <div class="m5nr">
                                <a href="" ><img src="images/sb2.jpg" class="l"/></a>
                                <div class="nrxq">
                                    <p>- Ứng dụng của máy soi kết tràng điện tử không đau là bước tiến triển quan trọng trong bệnh học dạ dày, nâng cao rõ rệt tỷ lệ chẩn đoán chính xác, tránh chẩn đoán sai sót, thông qua máy soi kết tràng điện tử tiến hành liệu pháp phi thủ thuật giúp loại bỏ polyp, cầm máu...</p>
                                    <dl>
                                        <dd>- An toàn dễ chịu: ống soi mềm, giảm cảm giác đau cho người bệnh</dd>
                                        <dd>- Tỷ lệ phát hiện cao: hình ảnh vô cùng rõ nét, nâng cao tỷ lệ phát hiện bệnh</dd>
                                        <dd>- Tránh làm thủ thuật: có thể điều trị dưới máy soi, tránh thương tổn thủ thuật</dd>
                                        <a href="<?= $link_tuvan;?>" class="btn_vt">Click tư vấn</a>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="mina6">
    <div class="comm">
        <a href="<?= $link_tuvan;?>" class="item_tit" >
        <span>Phòng khám 168 chuyên điều trị bệnh trực tràng hậu môn</span><br>
            hơn 200.000 bệnh nhân cùng kiểm chứng, có hiệu quả
        </a>
    </div>
    <div class="wits">
        <a href="<?= $link_tuvan;?>" >
            <img src="images/item6_1.jpg"/>
        </a>
    </div>
    <div class="wzms">
        <p>Phòng khám 168 có quy mô lớn, thiết bị toàn diện, nhiều bác sỹ, kỹ thuật tốt.... Từ ngày thành lập đến nay phòng khám luôn điều trị chẩn đoán các bệnh, có khoảng 300.000 bệnh nhân đã trải nghiệm chẩn đoán lâm sàng. Phòng khám 168 là phòng khám chuyên khoa điều trị các bệnh về trực trang hậu môn với trang thiết bị hiện đại, hiệu quả vượt trội, là nơi để giao lưu học thuật, đảm bảo sức khỏe, nghiên cứu khoa học, y tế lâm sàng...<a href="" style="color: red;">[Chi tiết]</a> </p>
    </div>
</div>
<?= cd_footer();?>
<!--<div class="foot">
    <div class="foot_main" style="width: 1187px;text-transform: uppercase;font-size: 13px;">
        <ol>
            <div style="width: 288px;height: 220px;overflow: hidden;float: left;">
                <div class="foot_logo"></div>
                <img src="http://trihanoi.com/public/images/phong-kham-bottom.png">
                <div class="foot_text"></div>
            </div>
            <div class="w565">
                <ul>
                    <h6>Trung tâm</h6>
                    <li><a href="http://trihanoi.com/gioi-thieu-phong-kham" target="_blank" title="">Giới thiệu</a></li>
                    <li><a href="http://trihanoi.com/thiet-bi-phong-kham" target="_blank" title="">Thiết bị</a></li>
                    <li><a href="" target="_blank" title="">Trường hợp khỏi bệnh</a></li>
                    <li><a href="http://chat.phongkham168.com/LR/Chatpre.aspx?id=KRX41100266&amp;lng=en" target="_blank" title="">Tư vấn chi phí</a></li>
                    <li><a href="http://chat.phongkham168.com/LR/Chatpre.aspx?id=KRX41100266&amp;lng=en" target="_blank" title="">Tư vấn bệnh</a></li>
                    <li><a href="<?/*= $link_tuvan;*/?>" target="_blank" title="">Liên hệ</a></li>
                </ul>
                <ul style="width: 142px;">
                    <h6>Hạng mục trị liệu</h6>
                    <li><a href="http://trihanoi.com/tri" target="_blank" title="">Trĩ</a></li>
                    <li><a href="http://trihanoi.com/nut-ke-hau-mon" target="_blank" title="">Nứt kẽ hâu môn</a></li>
                    <li><a href="http://trihanoi.com/ap-xe-hau-mon" target="_blank" title="">Áp xe hậu môn</a></li>
                    <li><a href="/eczema-hau-mon" target="_blank" title="">Eczema hậu môn </a></li>
                    <li><a href="http://trihanoi.com/ngua-hau-mon" target="_blank" title="">Ngứa hậu môn </a></li>
                    <li><a href="http://trihanoi.com/dai-tien-ra-mau" target="_blank" title="">Đại tiện ra máu</a></li>
                </ul>
                <ul class="w100" style="    width: 176px;">
                    <h6>Dịch vụ và giúp đỡ</h6>
                    <li><a href="/">Lộ trình phòng khám</a></li>
                    <li><a href="http://chat.phongkham168.com/LR/Chatpre.aspx?id=KRX41100266&amp;lng=en" target="_blank" title="">Tư vấn trực tuyến</a></li>
                    <li><a href="<?/*= $link_tuvan;*/?>" target="_blank" title="">Đăng ký hẹn khám</a></li>
                    <li><a href="skype:bacsy_tuvan168?chat" target="_blank" title="">Skype</a></li>
                    <li><a href="https://www.facebook.com/phongkham168" target="_blank" title="">Facebook</a></li>
                    <li><a href="http://trihanoi.com/dia-chi-phong-kham-da-khoa-168-ha-noi" target="_blank" title="">Tuyến đường</a></li>
                </ul>

            </div>
            <div class="qrcode">
                <div class="qrpic"></div>
                <div class="intro" style="color: white;">
                    <p>Đường dây nóng<br>Tư vấn sức khỏe<br><b style="    font-size: 21px;">1800 6166</b></p>
                </div>
                <div class="cl search" style="clear: both;overflow: hidden;">
                    <p style="font-size: 13px; color: #8d6e69;margin-top: 20px;"><b>Số điện thoại:</b> 04.3686.6888 - 0969 988 018</p>
                    <p style="font-size: 13px;color: #8d6e69;margin-top: 15px;"><b>Địa chỉ:</b> Số 709, Giải Phóng, Hoàng Mai, Hà Nội</p>
                </div>
            </div>
        </ol>
    </div>
    <div style="width: 100%;height: 40px;line-height: 40px;background: #000000;color:#8d6e69;font-size: 14px;text-align: center;">
        Sở hữu bản quyền phòng khám Đa Khoa 168 Hà Nội,nội dung website này chỉ để tham khảo không làm căn cứ chẩn đoán y tế.Tôn trọng ý kiến bác sĩ
    </div>
</div>-->
</div>
</body>
</html>
<!--<script type='text/javascript' src='http://cqalyy.cn/swt/swtal.js'></script>
&lt;!&ndash;电话&ndash;&gt;
<script type="text/javascript" src="http://cbjs.baidu.com/js/o.js"></script>
<script type="text/javascript" src="http://cqalyy.com/swt2014/alljs.js"></script>-->
