<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>apxe hậu môn</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="css/main.css" type="text/css" rel="stylesheet"/>
    <link href="css/custorm.css" type="text/css" rel="stylesheet"/>
    <base  target="_blank"/>
</head>
<?php require_once('../../define.php'); ?>
<body>
<?= cd_menu_top();?>
<div class="fram">
    <div class="banner">
        <div class="banner_c" style="">
            <div class="tvbs">
                <a href="<?= link_tuvan;?>" class="dkqm"></a>
                <a href="<?= link_tuvan;?>" class="bstv"></a>
            </div>
        </div>
    </div>
    <div class="nav_bg">
        <div class="nav">
            <div class="nav_1">
                <a href="#point_1" target="_parent">kiến thức về<br>apxe hậu môn</a>
                <a href="#point_2" target="_parent">bệnh tình apxe hậu môn<br>phát triển</a>
                <a href="#point_3" target="_parent" style="width:255px;">nguy hại của bệnh<br>apxe hậu môn</a>
                <a href="#point_4" target="_parent">phương pháp điều trị<br>tốt nhất apxe hậu môn</a>
            </div>
        </div>
    </div>
    <div class="main">
        <div class="main1"><a name="point_1"></a>
            <div class="commbt">apxe hậu môn<span> là bị làm sao？</span></div>
            <div class="m1sa">
                <img src="images/gznz_14.jpg" class="l"/>
                <div class="m1sa1 r">
                    <div class="m1a_bt">kiến thức bệnh apxe hậu môn</div>
                    <p>
                        <!--肛周脓肿是肛管、直肠周围软组织内或其周围间隙内发生急性化脓性感染，并形成脓肿，称为肛管、直肠
                        周围脓肿引。其特点是自行破溃，或在手术切开引流后常形成肛瘘。患者先感到肛门周围出现了一个小硬块或
                        肿块，继而疼痛加剧、红肿发热、坠胀不适等症状。若自行溃破或切开排脓后疼痛缓解或消失，体温下降，全
                        身情况好转，继而又复发，周而复始。-->
                    </p>
                </div>
            </div>
            <div class="m1sa2">
                <div class="zx"><a  href="<?= link_tuvan;?>" ><img src="images/gznz_18.png" alt="tu van"/></a></div>
                <div class="m1a_bt">triệu chứng thường gặp của apxe hậu môn</div>
                1.Hậu môn chứng tức
                <p>Do vị trí áp xe khá sâu, bệnh thường phát sinh ở khu vực thần kinh thực vật, đau không rõ rệt, biểu hiện là trướng tức, đau và trực tràng chịu ảnh hưởng…</p>
                2.Cục u cứng
                <p>Thời gian đầu, xung quanh hậu môn xuất hiện cục u cứng, dần dần to lên,<br> thời gian dài có thể sẽ tự loét</p>
                3.Đau
                <p>Đau là triệu chứng thường gặp nhất của áp xe hậu môn, dần dần đau nặng hơn, đau đột xuất hoặc đau sưng liên tục…</p>
                4.Sốt cao
                <p>người bệnh bị áp xe hậu môn, cục bộ sẽ xuất hiện hiện tượng sưng đỏ kèm sốt, thường là sốt nhẹ, có lúc xuất hiện sốt cao,  có người bệnh nhiệt độ có thể từ 37 – 40 độ. Ngoài ra, người bệnh sẽ có cảm giác toàn thân khó chịu, chán ăn, mất ngủ…
                </p>
            </div>
        </div>
        <div class="main2"><a name="point_2"></a>
            <div class="m2">
                <div class="commbt">apxe hậu môn<span> cần làm thủ tục sớm.</span></div>
                <div class="m2s">
                    <ul>
                        <li>
                            <dl>
                                <dt class="m2dd1">1.Thời kỳ viêm nhiễm<br/>
                                </dt>
                                <dd><img src="images/gznz_22.jpg"/></dd>
                                <dd class="m2dd3">Người bệnh bị đau dữ đội chính là gánh nặng tinh tần, ảnh hưởng đến việc nghỉ ngơi, không ngủ đủ giấc, dẫn đến tinh thần suy nhược.</dd>
                                <dd class="m2dd4">Mức độ ảnh hưởng sức khỏe <font color="#ff6c00">★★★☆☆</font></dd>
                                <dd class="m2dd5">Mức độ tiềm ẩn bệnh <font color="#ff6c00">★★★★☆</font></dd>
                            </dl>
                        </li>
                        <li>
                            <dl>
                                <dt class="m2dd1">2.Viêm nhiễm lây lan rộng<br/>
                                </dt>
                                <dd><img src="images/gznz_24.jpg"/></dd>
                                <dd class="m2dd3">Sợ đau khi đại tiện hình thành táo bón, để giảm thiểu đau đớn, không muốn đi đại tiện, vì vậy phân càng khô cứng.</dd>
                                <dd class="m2dd4">Mức độ ảnh hưởng sức khỏe <font color="#ff6c00">★★★★☆</font></dd>
                                <dd class="m2dd5">Mức độ tiềm ẩn bệnh <font color="#ff6c00">★★★★☆</font></dd>
                            </dl>
                        </li>
                        <li>
                            <dl>
                                <dt class="m2dd1">3.Hình thành áp xe hậu môn<br/>
                                </dt>
                                <dd><img src="images/gznz_26.jpg"/></dd>
                                <dd class="m2dd3">Khi đại tiện thường máu dính ở phân hoặc dính ở giấy vệ sinh khi lau, lâu dài dẫn đến thiếu máu</dd>
                                <dd class="m2dd4">Mức độ ảnh hưởng sức khỏe <font color="#ff6c00">★★★☆☆</font></dd>
                                <dd class="m2dd5">Mức độ tiềm ẩn bệnh <font color="#ff6c00">★★★★☆</font></dd>
                            </dl>
                        </li>
                        <li style="border:0px;">
                            <dl>
                                <dt class="m2dd1">4.Viêm nhiễm lặp lại hình thành bệnh</dt>
                                <dd><img src="images/gznz_28.jpg"/></dd>
                                <dd class="m2dd3">Kéo dài không điều trị sẽ xuất hiện viêm loét ống hậu môn, phì đại hậu môn, viêm hậu môn, rò hậu môn</dd>
                                <dd class="m2dd4">Mức độ ảnh hưởng sức khỏe <font color="#ff6c00">★★★★★</font></dd>
                                <dd class="m2dd5">Mức độ tiềm ẩn bệnh <font color="#ff6c00">★★★★★</font></dd>
                            </dl>
                        </li>
                    </ul>
                </div>
                <div class="m2s_swt">
                    <a  href="<?= link_tuvan;?>"><img
                            src="images/gznz_35.jpg"/>
                    </a>
                </div>
            </div>
        </div>
        <div class="main3"><a name="point_3"></a>
            <div class="commbt" style=" background: none; text-align:center;">Áp xe hậu môn<span> nguy hại lớn</span></div>
            <div class="main3a">
                <img src="images/gznz_38.png" class="l"/>
                <div class="main3b">
                    <p><strong>1.Hậu môn mất kiểm soát：</strong>do rò hậu môn phát triển, có thể gây thương tổn nghiêm trọng đến cơ vòm hậu môn, thậm chí có thể gây ra biến chứng hậu môn mất kiểm soát.</p>

                    <p><strong>2.Rò hậu môn：</strong>rò hậu môn tái phát nhiều lần, có thể biến thành rò hậu môn phức tạp, đa phát; gây ra nhiều khó khăn và ảnh hưởng đến chức năng sinh lý của hậu môn.</p>

                    <p><strong>3.Viêm nhiễm chảy mủ：</strong>sau khi rò hậu môn viêm nhiễm, hậu môn đau dữ dội, sau khi viêm loét mủ chảy ra quần lót, dịch mủ tác động vào lớp da ở hậu môn gây ra ngứa dữ dội.
                    </p>

                    <p><strong>4.Nguy hiểm biến chứng：</strong>rò hậu môn đa phát có thể hình thành rò trực tràng, rò niệu đạo trực tràng, rò bàng quang trực tràng, nguy hiểm đến cơ quan xung quanh và nếu không điều trị sẽ có khả năng chuyển biến thành ác tính.</p>
                </div>
            </div>
            <div class="main3c">
                <p>
                    <strong>Áp xe hậu môn nghiêm trọng có thể chuyển biến thành ung thư!</strong><br/>
                    rò hậu môn phát triển, có thể gây tổn thương nghiêm trọng đến cơ vòm hậu môn, thậm chí có thể gây ra biến chứng hậu môn mất kiểm soát.
                </p>
            </div>
        </div>
        <div class="main4"><a name="point_4"></a>

            <div class="commbt" style=" background: none; text-align:center;">
                <span>Phương pháp điều trị tốt nhất apxe hậu môn:</span>điều trị xâm lấn tối thiểu HCPT của Mỹ
            </div>
            <div class="m4bt">
                <h3>Hệ thống kỹ thuật xâm lấn tối thiểu HCPT của Mỹ<span> điều trị áp xe hậu môn với 3 bước đột phá:</span></h3>
                <ul>
                    <li>đột phá 1: không những điều trị cơ bản mà còn điều trị tổng thể</li>
                    <li>đột phá 2: làm thủ thuật với kỹ thuật không đau</li>
                    <li>đột phá 3: phạm vi điều trị rộng</li>
                </ul>
            </div>
            <div class="m4sa">
                <a href="<?= link_tuvan;?>" >
                    <img src="images/gznz_46.jpg" width="265" height="265" class="l"/>
                </a>
                <div class="m4sa1">
                    <h3>Kỹ thuật xâm lấn tối thiểu HCPT với 4 ưu thế lớn: </h3>
                    <strong>1, Chức năng toàn diện thích ứng rộng rãi </strong>
                    <p>Chức năng cao tần dưới thao tác môi trường vô khuẩn, tiến hành điều trị trĩ, rò hậu môn và áp xe hậu môn, toàn bộ quá trình tuyệt đối không gây viêm nhiễm chéo.</p>
                    <strong>2, Thủ thuật xâm lấn tối thiểu an toàn hiệu quả cao</strong>
                    <p>Lợi dụng nguyên lý sản sinh nhiệt điện trường điện rung cao tần, đạt được hiệu quả tốt nhất. điều trị trong thời gian ngắn nhất thu được hiệu quả tốt nhất.</p>
                    <strong>3, không đau hiệu quả cao loại bỏ hết bệnh</strong>
                    <p>Sản sinh nhiệt dao động dưới trường điện rung cao tần, khi hoàn thành tự động dừng lại, sinh nhiệt nhanh, có thể kiểm soát, không đau…</p>
                    <strong>4, Sau thủ thuật phục hồi nhanh, không biến chứng</strong>
                    <p>Hệ thống kỹ thuật số hóa định vị chính xác vị trí bệnh, thực hiện điều trị một lần, phục hồi nhanh không biến chứng.</p>
                </div>
            </div>
        </div>
        <div style="width: 100%;height: 30px;overflow: hidden"></div>
    </div>
</div>
<?= cd_footer();?>
</body>
</html>




