<?php 
$link_trangchu = "http://phongkhamgiaiphong.com/namkhoa/cdsuckhoe/chuyen-de-suc-khoe/index.phtml";
$link_tv = "http://swt.pk709.com/LR/Chatpre.aspx?id=KTF27288478&lng=en";
$link_gioithieu = "http://phongkhamgiaiphong.com/cd6/gioi-thieu/";
$link_tuyenduong = "http://phongkhamgiaiphong.com/cd6/lo-trinh-kham/";
$link_kythuat = "http://khamnamkhoahanoi.vn/ky-thuat";
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title> Chuyên đề ưu đãi - phòng khám đa khoa giải phóng  </title>
  <link rel="shortcut icon" type="image/x-icon" href="http://trihanoi.com/public/frontend/home/image/logo.png" />    <base target="_blank">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Patua+One" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.1/css/hover-min.css">
</head>
<body>
  <div class="page"> 
      <header class="header">
          <div class="container">
               <div class="row">
                    <div class="col-md-4">
                         <div class="img_logo">
                             <img src="images/logo.png" alt="">
                         </div>
                    </div>
                    <div class="col-md-4">
                         <div class="img_logo">
                             <img class="img_logo2" src="images/logo2.png" alt="">
                         </div>
                    </div>
                    <div class="col-md-4">
                         <div class="img_logo">
                             <img class="img_logo3" src="images/sdt_top.png" alt="">
                         </div>
                    </div>
               </div>
          </div>
      </header> <!-- end header  -->
      <div class="menu"> <!-- begin menu  -->
           <div class="container">
                <div class="row">
                    <div class="sub_menu">
                         <ul>
                              <li>
                                  <a href="<?= $link_trangchu;?>"> Trang chủ </a>
                              </li>
                              <li>
                                  <a href="<?= $link_gioithieu; ?>"> Giới thiệu</a>
                              </li>
                              <li>
                                  <a href="<?= $link_tv;?>"> Kỹ thuật </a>
                              </li>
                              <li>
                                  <a href="<?= $link_tv;?>"> Bác sỹ </a>
                              </li>
                              <li>
                                  <a href="<?= $link_tuyenduong;?>"> Tuyến xe </a>
                              </li>
                              <li>
                                  <a href="<?= $link_tv;?>"> Đăng ký trực tuyến </a>
                              </li> 
                         </ul>
                    </div>
                </div>
           </div>
      </div> <!-- end menu  -->
      <div id="carousel-id" class="carousel slide" data-ride="carousel">
         <ol class="carousel-indicators">
           <li data-target="#carousel-id" data-slide-to="0" class=""></li>
           <li data-target="#carousel-id" data-slide-to="1" class=""></li>
           <li data-target="#carousel-id" data-slide-to="2" class="active"></li>
         </ol>
         <div class="carousel-inner">
<!--            <div class="item">
  <img data-src="holder.js/900x500/auto/#777:#7a7a7a/text:First slide" alt="First slide" src="images/banner.jpg">
  
</div> -->
       <!--     <div class="item">
         <img data-src="holder.js/900x500/auto/#666:#6a6a6a/text:Second slide" alt="Second slide" src="images/banner.jpg">
       </div> -->
           <div class="item active">
             <img data-src="holder.js/900x500/auto/#555:#5a5a5a/text:Third slide" alt="Third slide" src="images/banner.jpg">
           </div>
         </div>
        <!--  <a class="left carousel-control" href="#carousel-id" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
        <a class="right carousel-control" href="#carousel-id" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a> -->
       </div> 
       <div class="home1">
          <div class="container">
             <div class="row">
              <div class="text">
                <div class="col-md-2"></div>
                  <div class="col-md-10">
                     <div class="text_2">
                        Sau một chặng đường phát triển, tới thời điểm này phòng khám đa khoa Giải Phóng đã khẳng định được uy tín trong lĩnh vực chăm sóc sức khỏe và luôn tự hào là địa chỉ được nhiều bệnh nhâm lựa chọn bởi chuyên môn và chất lượng dịch vụ chuyên nghiệp. 
  Với mong muốn tạo điều kiện thuận lợi cho quý khách hàng có thể đến khám chữa bệnh và trải nghiệm dịch vụ, phòng khám đa khoa Giải Phóng triển khai Chương trình lì xì sức khỏe chào đón năm mới 2018 dành riêng cho khách hàng đăng ký hẹn khám qua mạng. 
                     </div>
                  </div>
                 </div> 
             </div>
          </div>
       </div> <!-- end home 1 -->
       <div class="home2">
          <div class="container">
             <div class="row text-center">
              <div class="col-md-6 col-md-push-3">
                 <h2 class="title_home2"> Những hạng mục ưu tiên miễn phí </h2>
              </div>   
             </div>
             <div class="row">
                 <div class="bg_home2">
                   
                 </div>
             </div>
          </div>
       </div> <!-- end home 2 -->
       <div class="home3">
          <div class="container">
             <div class="row text-center">
                 <img src="images/30_kt.png" alt="">
             </div>
             <div class="row text-center">
             <div class="col-md-10 col-md-push-1">
                <h2 class="title_home2 custom">
                   Chúng tôi có thiết bị và môi trường thủ thuật mà những nơi khác không thể so sánh 
                </h2>
             </div>
             </div>
             <div class="row rowthu3">
                <div class="col-md-6">
                    <div class="baoquanh">
                         <img class="img-responsive" src="images/anh1_home2.jpg" alt="">
                         <div class="text_home2">
                           Khâu kiểm tra bệnh tại phòng khám được thực hiện theo đúng trình tự, gồm khâu kiểm tra lâm sàng đến làm xét nghiệm, điển hình như xét nghiệm máu, xét nghiệm nước tiểu, xét nghiệm mẫu vật...cùng nhiều xét nghiệm chuyên môn khác. Qúa trình kiểm tra được thực hiện trực tiếp bởi các bác sỹ đầu ngành, áp dụng máy móc kỹ thuật tân tiến, cho phép chẩn đoán bệnh chính xác trong thời gian ngắn nhất
                         </div>
                         <a href="<?= $link_tv;?>">
                         <div class="thengoai hvr-pulse-shrink">
                           <div class="thetrong">
                               Tư vấn trực tuyến 
                           </div>
                         </div>
                         </a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="baoquanh">
                         <img class="img-responsive" src="images/anh2_home2.jpg" alt="">
                         <div class="text_home2">
                           Vì sự an toàn của bạn, hi vọng mọi người nâng cao cảnh giác, lựa chọn cẩn thận! Không nên tin tưởng các phòng khám tư nhân nhỏ lẻ và không chính quy, khi làm thủ thuật nhất định phải lựa chọn phòng khám chính quy, có chất lượng, quy mô lớn... 
                         </div>
                         <a href="<?= $link_tv;?>">
                         <div class="thengoai hvr-pulse-shrink">
                           <div class="thetrong">
                               Tư vấn trực tuyến 
                           </div>
                         </div>
                         </a>
                    </div>
                </div>
             </div>
          </div>
       </div> <!-- end home 3 -->
       <div class="home4">
          <div class="container">
            <div class="row text-center">
                <img src="images/30_tt.png" alt="">
            </div>
            <div class="row rowhome4">
               <div class="nd_cold4">
                  <div class="col-md-6">
                       <img src="images/bs_home4.jpg" alt="">
                  </div>
                  <div class="col-md-6">
                    <div class="nd_baoquanh">
                      <div class="tt_baoquanh_home4">
                         THẤU HIỂU ĐƯỢC NHỮNG KHÓ KHĂN VÀ NHU CẦU KHÁM CHỮA BỆNH CỦA BỆNH NHÂN NGÀY CÀNG CAO.
                      </div>
                      <div class="nd_baoquanh_home4">
                        Sau chặng đường nhiều năm phát triển,phòng khám đa khoa Giải Phóng đã khẳng định được vị thế trong lĩnh vực chăm sóc sức khỏe, với phương châm đặt sức khỏe của bệnh nhân lên hàng đầu và nhằm giảm bớt gánh nặng cho người bệnh, phòng khám triển khai chương trình ưu đãi mừng xuân mới. Dành riêng cho những bệnh nhân có đặt hẹn trước với nhiều hạng mục hấp dẫn.
                      </div>
                    </div>
                  </div>
               </div>
            </div>
            <div class="row text-center">
              <a href="<?= $link_tv;?>">
               <button class="btn btn-danger nuttv hvr-pulse-shrink">
                  <span class="img_tab3">
                    <img class="img_tab3" src="images/phonetv.png" alt="">
                  </span>
                  <span class="tv_mienphi">
                     Tư vấn miễn phí trực tuyến 
                  </span>
               </button>
              </a>
            </div>
          </div>
       </div> <!-- end home 4  -->
       <div class="home4 custom2">
          <div class="container">
            <div class="row text-center">
                <img src="images/dt.png" alt="">
            </div>
            <div class="row rowhome4">
               <div class="nd_cold4">
                  <div class="col-md-6">
                    <div class="nd_baoquanh">
                      <div class="tt_baoquanh_home4">
                        THẤU HIỂU ĐƯỢC NHỮNG KHÓ KHĂN VÀ NHU CẦU KHÁM CHỮA BỆNH CỦA BỆNH NHÂN NGÀY CÀNG CAO.
                      </div>
                      <div class="nd_baoquanh_home4">
                        Phòng khám đa khoa Giải Phóng Hà Nội trong nhiều năm qua phòng khám đã và luôn là một đơn vị tiên phong trong lĩnh vực y tế, chăm sóc dịch vụ cộng đồng với nhiều phương pháp điều trị tiên tiến. Kết hợp với đội ngũ y bác sĩ hùng hậu, phòng khám đa khoa Giải Phóng đầu tư các trang thiết bị, máy móc, hiện đại, luôn được cập nhật và đổi mới không ngừng để nắm bắt các động thái, xu hướng chữa bệnh mới nhất của nền y học thế giới, trang thiết bị này đều được phòng khám nhập khẩu trực tiếp từ các quốc gia có nền y học phát triển như Anh, Mỹ, Đức, Nhật Bản, Hàn Quốc... thông qua sự kiểm định của bộ y tế Việt Nam. Nhờ áp dụng những kỹ thuật tân tiến, chúng tôi đã giải quyết dứt điểm một số căn bệnh phức tạp khó chữa và kết quả khám chữa bệnh được nâng cao một cách rõ rệt.
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                       <img src="images/bs_hom4.png" alt="">
                  </div>
               </div>
            </div>
            <div class="row text-center">
              <a href="<?= $link_tv;?>">
               <button class="btn btn-danger nuttv hvr-pulse-shrink">
                  <span class="img_tab3">
                    <img class="img_tab3" src="images/phonetv.png" alt="">
                  </span>
                  <span class="tv_mienphi">
                     Tư vấn miễn phí trực tuyến 
                  </span>
               </button>
               </a>
            </div>
          </div>
       </div> <!-- end home 4  -->
       <div class="home5">
           <div class="container">
              <div class="row text-center">
                 <div class="col-md-6 col-md-push-3">
                     <div class="tt_col6_home5"> Phòng khám chuyên nghiệp </div>
                     <div class="des_home5"> Chúng tôi luôn cố gắng nỗ lực để có thể phục vụ bệnh nhân tốt nhất </div>
                 </div>
              </div>
              <div class="row text-center rowhome5">
                 <div class="col-md-3">
                    <div class="baoquanh_home5">
                       <img src="images/cn1_home5.png" alt="">
                       <div class="tt_home5_hai">
                         phòng khám đa khoa <br> chuyên nghiệp 
                       </div>
                       <div class="des_home5_hai">
                         Chuyên điều trị các bệnh, bảo vệ sức khỏe bản thân
                       </div>
                    </div>
                 </div>
                 <div class="col-md-3">
                    <div class="baoquanh_home5">
                       <img src="images/cn2_home5.png" alt="">
                       <div class="tt_home5_hai">
                         Đội ngũ y tế  <br> lớn mạnh 
                       </div>
                       <div class="des_home5_hai">
                        tập hợp các bác sỹ nổi tiếng trong và ngoài nước, đội ngũ y bác sỹ hùng hậu 
                       </div>
                    </div>
                 </div>
                 <div class="col-md-3">
                    <div class="baoquanh_home5">
                       <img src="images/cn3_home5.png" alt="">
                       <div class="tt_home5_hai">
                        Kỹ thuật chẩn trị <br> tiên tiến toàn diện  
                       </div>
                       <div class="des_home5_hai">
                         Nhập khẩu các loại kỹ thuật chẩn trị, nâng cao hiệu quả điều trị bệnh
                       </div>
                    </div>
                 </div>
                 <div class="col-md-3">
                    <div class="baoquanh_home5">
                       <img src="images/cn4_home5.png" alt="">
                       <div class="tt_home5_hai">
                         Đến thăm khám  <br> là được ưu đãi 
                       </div>
                       <div class="des_home5_hai">
                         Người bệnh đến khám sẽ được hưởng ưu đãi, tiết kiệm chi phí 
                       </div>
                    </div>
                 </div>
              </div>
           </div>
       </div> <!-- end home 5 -->
       <div class="home6">
           <div class="container">
             <div class="row text-center">
                 <div class="col-md-6 col-md-push-3">
                    <div class="tt_home6">Thăm khám bệnh lưu ý  <br> phòng khám chuyên nghiệp </div>
                 </div>
             </div>
             <div class="row rowhome6hai">
                <div class="col-md-6">
                    <div class="tt_col6_hai">
                        Phòng khám đa khoa Giải Phóng với trang thiết bị hiện đại, kỹ thuật tiên tiến, điều trị hiệu quả cao, chi phí thấp
                    </div>
                    <div class="des_col6_home6">
                        Không phải phòng khám nào cũng có thể áp dụng kỹ thuật xâm lấn tối thiểu Chỉ có những phòng khám chuyên nghiệp, toàn diện, cơ cấu trang thiết bị và năng lực về y tế chính quy toàn diện mới có đủ tư cách áp dụng
                    </div>
                    <img style="width: 100%;" src="images/img_home6.jpg" alt="">
                    <a href="<?= $link_tv;?>"><button class="btn btn-danger nutview hvr-pulse"> <span class="nuttrongclick">Click tư vấn đặt hẹn</span> </button>
                      </a>
                </div>
                <div class="col-md-6">
                   <div class="row">
                      <div class="col-md-2">
                          <img src="images/so1.png" alt="">
                      </div>
                      <div class="col-md-10">
                          <div class="nd_col-10">
                             <div class="tt_col10">Năng lực được công nhận </div>
                             <div class="des_col10">
                                Phòng khám đa khoa Giải Phóng với trang thiết bị hiện đại, kỹ thuật tiên tiến, điều trị hiệu quả cao, chi phí thấp
                             </div>
                          </div>
                      </div>
                   </div>
                   <div class="row" style="margin-top: 40px;">
                      <div class="col-md-2">
                          <img src="images/so2.png" alt="">
                      </div>
                      <div class="col-md-10">
                          <div class="nd_col-10">
                             <div class="tt_col10"> bảo đảm an toàn  </div>
                             <div class="des_col10">
                                - Môi trường được đảm bảo - phòng thủ thuật sạch sẽ vô khuẩn <br>
                                - Bác sỹ được đảm bảo - với đội ngũ y bác sỹ có trên 20 năm  <br>
                                kinh nghiệm lâm sàng <br>
                                - Kinh nghiệm được đảm bảo - với hàng ngàn ca thủ thuật  <br>
                                  không sự cố <br>
                             </div>
                          </div>
                      </div>
                   </div>
                   <div class="row" style="margin-top: 40px;">
                      <div class="col-md-2">
                          <img src="images/so3.png" alt="">
                      </div>
                      <div class="col-md-10">
                          <div class="nd_col-10">
                             <div class="tt_col10">  yêu cầu về trình độ  </div>
                             <div class="des_col10">
                                Nhằm đảm bảo thực hiện thủ thuật an toàn và hiệu quả cao, bác <br> 
                                sỹ thực hiện thủ thuật cần có: <br> 
                                <div class="text_col6">
                                   1. Bác sỹ có Trình độ thực hiện thủ thuật <br>
                                   2. Bác sỹ thực hiện hàng ngàn ca thủ thuật không để  <br>
                                   xuất hiện sự cố <br>
                                   3. Làm việc trong ngành y từ 20 năm trở lên <br> 
                                </div>
                             </div>
                          </div>
                      </div>
                   </div>
                   <div class="row" style="margin-top: 40px;">
                      <div class="col-md-2">
                          <img src="images/so4.png" alt="">
                      </div>
                      <div class="col-md-10">
                          <div class="nd_col-10">
                             <div class="tt_col10"> Trang thiết bị hiện đại  </div>
                             <div class="des_col10">
                               Phòng khám đa khoa Giải Phóng, nhập khẩu trang thiết bị hiện đại, đảm bảo tính an toàn và hiệu quả điều trị
                             </div>
                          </div>
                      </div>
                   </div>
                </div>
             </div>
           </div>
       </div> <!-- end home 6 -->
       <footer class="footer">
          <div class="container">
             <div class="row rowft">
                  <div class="col-md-3 md3">
                    <a href="<?= $link_tv;?>">
                     <img src="images/icon_ft_1.png" alt="">
                     <span class="icon1"> Đăng ký khám </span>
                     </a>
                  </div>
                   <div class="col-md-3 md3">
                    <a href="<?= $link_tv;?>">
                     <img src="images/icon_ft_2.png" alt="">
                     <span class="icon1"> Tư vấn trực tuyến </span>
                     </a>
                  </div>
                   <div class="col-md-3 md3">
                    <a href="<?= $link_tv;?>">
                     <img src="images/icon_ft_3.png" alt="">
                     <span class="icon1"> Tư vấn điện thoại </span>
                     </a>
                  </div>
                   <div class="col-md-3 md3">
                    <a href="skype:phongkhamdakhoagiaiphong@gmail.com?chat">
                     <img src="images/icon_ft_4.png" alt="">
                     <span class="icon1"> Skyper </span>
                     </a>
                  </div>
             </div>
             <div class="row" style="margin-top: 50px;">
                <div class="col-md-4">
                    <img src="images/logo_ft.png" alt="">
                </div>
                <div class="col-md-4">
                   <img src="images/logo_2_ft.png" alt="">
                </div>
                <div class="col-md-4 text-center">
                  <img src="images/logo_ft_3.png" alt="">
                </div>
             </div>
          </div>
       </footer>
       <div class="footer2">
         <div class="container">
           <div class="row text-center">
                 Sở hữu bản quyền phòng khám đa khoa Giải Phóng  All rights reserved, Nôi dung website này chỉ để tham khảo, không làm căn cứ để chẩn đoán điều trị. Tôn trọng ý kiến bác sĩ.
           </div>
         </div>
       </div>
    </div>
<script language="javascript" src="http://swt.pk709.com/JS/LsJS.aspx?siteid=KTF27288478&amp;lng=en"></script>
</body>
</html>